### ISSUE TITLE
Replace Word with a Specific Word

### ISSUE THREAD

**Issue by nathanila** [richardfrost/AdvancedProfanityFilter#100]
## Description
For some words, I would like to replace the word with another specific word.  For example, I would like the flexibility to replace "poodles" with "puddles" and "rabbits" with "rodents".  This would allow me to replace offensive words and not trip up reading the sentence because there is a word missing.

### Details (Bugs Only)

Firefox Version: 61.0.2
Extension Version: 1.1.1
Operating System: Windows 10
Site(s) Affected: All

**Comment by richardfrost** [comment]
I believe what you are looking for is already possible if you switch to using the [Substitution Mode](https://github.com/richardfrost/AdvancedProfanityFilter/wiki#substitution-mode), and then add a substitution for each word you want. It might also be worth adjusting the matching method for the word, for instance if you match `rodent` using the `Exact Match Method` it will only match the word exactly, but if you do a `Partial Match Method` it would match `rodent` and`rodents`.

You can find more information on the available options on the [Wiki page](https://github.com/richardfrost/AdvancedProfanityFilter/wiki).

If that isn't what you are looking for please let me know and I can look into it.

**Comment by nathanila** [comment]
Thanks!  That works great!
