### ISSUE TITLE
Microsoft Edge Support

### ISSUE THREAD

**Issue by richardfrost** [richardfrost/AdvancedProfanityFilter#102]
I have done the work to get the extension to work on Microsoft Edge, but to publish it requires a one-time payment. I don't really use Edge, and I haven't gotten any requests for it yet, so I think I'm going to put its support on hold for now. If there is interest in it, please feel free to comment here so I can gauge demand.

**Comment by Psymatics** [comment]
I would be interested!

**Comment by richardfrost** [comment]
@Psymatics Thanks for expressing your interest. I will probably need to wait a few more weeks to get the money to register as money is tight right now, but I'll try to prioritize it. Out of curiosity, how did you find this? Just wondering if there is a way I might get more interested people to see this.

If anyone else is interested, still feel free to let me know!

**Comment by Psymatics** [comment]
I've heard all sorts of things about the requirements to get an extension on the Windows Store being really difficult (never looked myself though) so I figured: why not check GitHub for any extensions I use on Chrome for unofficial Edge-compatible builds.

I've been using Chrome for a while, but last month I decided to give Edge an honest-to-goodness shot. Mostly because a Dark mode extension finally cropped up (it's not Dark Reader, though...)

**Comment by richardfrost** [comment]
Well, I'm glad you found this then! I think its unfortunate that it costs money to publish an extension for Edge, but other than that I don't think there will be too much more work that needs to be done.

If you would like to test the extension on Edge, download the edge version from the [releases page](https://github.com/richardfrost/AdvancedProfanityFilter/releases), and then follow the direction to [load an unpacked extension](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Load-Unpacked-Extension). It should be considered beta right now. Let me know if you have any feedback on it. Thanks!

**Comment by Psymatics** [comment]
Sweet, thanks a bunch!

**Comment by tonyram57** [comment]
Would a greasemonkey script work for Edge.

Either way I don't care for Edge I use Firefox and Chrome which fully support this extension.

**Comment by richardfrost** [comment]
Thanks for the feedback! A userscript could probably work, but would not feature a way to expose any options. You could use a fully supported browser and copy the config from there into the user script (not super user friendly, but possible). I may tinker with the idea some more.

**Comment by tonyram57** [comment]
True but at least it is something using a script as Edge has no profanity filters at all which I why I don't use it at all.

**Comment by richardfrost** [comment]
I'm going to put this on the back burner and wait to see the dust settle after Microsoft's announced changes to Edge.

**Comment by richardfrost** [comment]
If you are looking to use the filter on the new version of Edge, you can find it on the [Microsoft Edge Addons page](https://microsoftedge.microsoft.com/addons/detail/lhnbdlbhcokmgpjenkjolnhdnkphnkam).

If you are looking for the legacy version of Edge, head over to the [releases](https://github.com/richardfrost/AdvancedProfanityFilter/releases) and look for the file named `extension-edge-legacy.zip`. To use it, you'll have to [load an unpacked extension](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Load-Unpacked-Extension). Unfortunately Microsoft is not allowing any new extension submissions for the legacy version of Edge.
