### ISSUE TITLE
Do Not Scroll the Page

### ISSUE THREAD

**Issue by nathanila** [richardfrost/AdvancedProfanityFilter#104]
## Description
As Advanced Profanity Filter replaces words in the page, it scrolls the page down so that the last word replaced is at the bottom of the screen.  Please change this so that the page does not scroll.

### Details (Bugs Only)
Firefox Version: 62.0.2
Extension Version: 1.1.2
Operating System: Windows 10
Site(s) Affected: all

### Steps to reproduce (Bugs only)
1. Setup a word replacement in Advanced Profanity Filter
2. Open a long page with the word to be replaced
3. Let the page fully load
4. Notice that the page is scrolled down and not at the top

**Comment by richardfrost** [comment]
Thanks for logging the issue. I just tested this on Firefox (`62.0.2`) and can't seem to replicate it. I went to a wikipedia page and at the bottom added a word from the bottom of the page to the filter. I scrolled to the top of the page (and the target word was off the page), and when I refreshed the page I was still at the top. I tested different scrolling positions and in every instance the browser properly remembered my scroll position between page refreshes or opening the page in a new tab.

Do you have any other extensions installed that might be changing the behavior, or have you modified the default Firefox settings to remember scroll position? By default the browser remembers where you were on the page if you refresh it.

This does sound like a pretty jarring situation, and I'd love to get to the bottom of it, but since I can't replicate it I will need some help to troubleshoot it.

**Comment by nathanila** [comment]
I opened a page with a word to be substituted.  The page scrolled so that the last substituted word is just barely off the bottom of the window.  I have to scroll 1 line to see it.

I then clicked on the Advanced Profanity Filter's icon in the toolbar and turned it off.  The page automatically reloaded.  The page did not scroll and stayed at the top.

I then clicked on the Advanced Profanity Filter's icon in the toolbar and turned it on.  The page scrolled to the last substituted word.

I disabled all of my addons except Advanced Profanity Filter.  I scrolled to the top of the page and selected some text at the top.  I reloaded the page.  The page scrolled to the last substituted word.

My Advanced Profanity Filter settings are at the bottom.  Backup your settings.  Please import these settings into your Firefox and see if the problem reproduces.

I opened about:support in Firefox.  I then copied the Important Modified Parameters section here.  Is there anything here that would cause a problem?

> Name 	Value
> accessibility.typeaheadfind	true
> accessibility.typeaheadfind.flashBar	0
> browser.cache.disk.capacity	1048576
> browser.cache.disk.filesystem_reported	1
> browser.cache.disk.hashstats_reported	1
> browser.cache.disk.smart_size.first_run	false
> browser.cache.disk.smart_size.use_old_max	false
> browser.cache.frecency_experiment	4
> browser.download.folderList	2
> browser.places.smartBookmarksVersion	8
> browser.search.useDBForOrder	true
> browser.sessionstore.upgradeBackup.latestBuildID	20180920131237
> browser.startup.homepage	about:blank
> browser.startup.homepage_override.buildID	20180920131237
> browser.startup.homepage_override.mstone	62.0.2
> browser.tabs.remote.autostart.2	true
> browser.tabs.warnOnClose	false
> browser.urlbar.daysBeforeHidingSuggestionsPrompt	3
> browser.urlbar.lastSuggestionsPromptDate	20180611
> browser.urlbar.matchBuckets	general:5,suggestion:Infinity
> browser.urlbar.placeholderName	Google
> browser.urlbar.timesBeforeHidingSuggestionsHint	0
> dom.forms.autocomplete.formautofill	true
> dom.push.userAgentID	ace2e562d75f4816bff723c56623a171
> extensions.formautofill.firstTimeUse	false
> extensions.lastAppVersion	62.0.2
> font.internaluseonly.changed	false
> gfx.crash-guard.d3d11layers.appVersion	52.8.1
> gfx.crash-guard.d3d11layers.deviceID	0x5916
> gfx.crash-guard.d3d11layers.driverVersion	23.20.16.4973
> gfx.crash-guard.d3d11layers.feature-d2d	true
> gfx.crash-guard.d3d11layers.feature-d3d11	true
> gfx.crash-guard.status.d3d11layers	2
> gfx.crash-guard.status.d3d11video	2
> layers.mlgpu.sanity-test-failed	false
> media.benchmark.vp9.fps	48
> media.benchmark.vp9.versioncheck	4
> media.gmp-gmpopenh264.abi	x86_64-msvc-x64
> media.gmp-gmpopenh264.lastUpdate	1528755209
> media.gmp-gmpopenh264.version	1.7.1
> media.gmp-manager.buildID	20180920131237
> media.gmp-manager.lastCheck	1537824223
> media.gmp-widevinecdm.abi	x86_64-msvc-x64
> media.gmp-widevinecdm.lastUpdate	1536325973
> media.gmp-widevinecdm.version	1.4.9.1088
> media.gmp.storage.version.observed	1
> media.hardware-video-decoding.failed	false
> network.cookie.prefsMigrated	true
> network.dns.disablePrefetch	true
> network.http.speculative-parallel-limit	0
> network.http.throttle.version	2
> network.predictor.cleaned-up	true
> network.predictor.enabled	false
> network.prefetch-next	false
> places.database.lastMaintenance	1538011887
> places.history.expiration.transient_current_max_pages	136534
> plugin.disable_full_page_plugin_for_types	application/pdf
> privacy.cpd.formdata	false
> privacy.cpd.sessions	false
> privacy.sanitize.pending	[{"id":"newtab-container","itemsToClear":[],"options":{}}]
> privacy.userContext.enabled	true
> privacy.userContext.extension	treestyletab@piro.sakura.ne.jp
> privacy.userContext.longPressBehavior	2
> privacy.userContext.ui.enabled	true
> security.disable_button.openCertManager	false
> security.sandbox.content.tempDirSuffix	{48ecc44a-0eaf-4e4a-a9f6-0a49787b5fae}
> services.sync.declinedEngines	adblockplus
> services.sync.engine.addresses.available	true
> services.sync.engine.prefs.modified	false
> services.sync.lastPing	1537977591
> services.sync.lastSync	Thu Sep 27 2018 09:18:17 GMT-0600 (Mountain Daylight Time)
> signon.importedFromSqlite	true
> signon.rememberSignons	false
> storage.vacuum.last.index	1
> storage.vacuum.last.places.sqlite	1536541387
> ui.osk.debug.keyboardDisplayReason	IKPOS: Keyboard presence confirmed.

Here are my Advanced Profanity Filter settings:

> {
>   "disabledDomains": [
>     "getthere.net",
>     "oracle.com",
>     "oraclecloud.com",
>     "oraclecorp.com",
>     "ticktick.com"
>   ],
>   "advancedDomains": [
>     "blogs.msdn.microsoft.com"
>   ],
>   "substitutionMark": false,
>   "filterMethod": 1,
>   "defaultWordMatchMethod": 1,
>   "defaultWordRepeat": true,
>   "preserveCase": true,
>   "password": null,
>   "showCounter": true,
>   "preserveLast": false,
>   "preserveFirst": false,
>   "globalMatchMethod": 3,
>   "defaultSubstitutions": [
>     "censored",
>     "expletive",
>     "filtered"
>   ],
>   "censorFixedLength": 0,
>   "censorCharacter": "*",
>   "words": {
>     "ass": {
>       "matchMethod": 0,
>       "words": [
>         "tail"
>       ]
>     },
>     "assed": {
>       "matchMethod": 0,
>       "repeat": true,
>       "words": [
>         "baked"
>       ]
>     },
>     "asshole": {
>       "matchMethod": 1,
>       "words": [
>         "meany"
>       ]
>     },
>     "asswipe": {
>       "matchMethod": 0,
>       "repeat": false,
>       "words": [
>         "meany"
>       ]
>     },
>     "badass": {
>       "matchMethod": 1,
>       "repeat": true,
>       "words": [
>         "awesome"
>       ]
>     },
>     "bastard": {
>       "matchMethod": 1,
>       "words": [
>         "imperfect",
>         "impure"
>       ]
>     },
>     "bitch": {
>       "matchMethod": 1,
>       "words": [
>         "meany"
>       ]
>     },
>     "bs": {
>       "matchMethod": 0,
>       "repeat": false,
>       "words": [
>         "baloney"
>       ]
>     },
>     "bullshit": {
>       "matchMethod": 1,
>       "repeat": true,
>       "words": [
>         "poop"
>       ]
>     },
>     "butt": {
>       "matchMethod": 0,
>       "repeat": true,
>       "words": [
>         "rear"
>       ]
>     },
>     "crap": {
>       "matchMethod": 0,
>       "words": [
>         "poo"
>       ]
>     },
>     "dammit": {
>       "matchMethod": 0,
>       "repeat": false,
>       "words": [
>         "dang it"
>       ]
>     },
>     "damn": {
>       "matchMethod": 2,
>       "words": [
>         "dang"
>       ]
>     },
>     "dick": {
>       "matchMethod": 1,
>       "repeat": true,
>       "words": [
>         "meany"
>       ]
>     },
>     "dickhead": {
>       "matchMethod": 1,
>       "repeat": true,
>       "words": [
>         "meany"
>       ]
>     },
>     "dumbass": {
>       "matchMethod": 1,
>       "repeat": true,
>       "words": [
>         "dumb person"
>       ]
>     },
>     "fuck": {
>       "matchMethod": 1,
>       "words": [
>         "fudge"
>       ]
>     },
>     "fucked": {
>       "matchMethod": 0,
>       "repeat": false,
>       "words": [
>         "fudged"
>       ]
>     },
>     "fucked up": {
>       "matchMethod": 0,
>       "repeat": false,
>       "words": [
>         "fudged"
>       ]
>     },
>     "god damn it": {
>       "matchMethod": 2,
>       "repeat": true,
>       "words": [
>         "it"
>       ]
>     },
>     "hell": {
>       "matchMethod": 0,
>       "repeat": false,
>       "words": [
>         "nowhere"
>       ]
>     },
>     "hells sakes": {
>       "matchMethod": 1,
>       "repeat": true,
>       "words": [
>         "goodness sakes"
>       ]
>     },
>     "jackass": {
>       "matchMethod": 1,
>       "repeat": true,
>       "words": [
>         "meany"
>       ]
>     },
>     "omg": {
>       "matchMethod": 1,
>       "repeat": true,
>       "words": [
>         "oh"
>       ]
>     },
>     "penishood": {
>       "matchMethod": 0,
>       "repeat": true,
>       "words": [
>         "priesthood"
>       ]
>     },
>     "piss": {
>       "matchMethod": 1,
>       "words": [
>         "pee"
>       ]
>     },
>     "pissed": {
>       "matchMethod": 0,
>       "words": [
>         "ticked"
>       ]
>     },
>     "sh*t": {
>       "matchMethod": 1,
>       "repeat": true,
>       "words": [
>         "poop"
>       ]
>     },
>     "shit": {
>       "matchMethod": 1,
>       "words": [
>         "poop"
>       ]
>     },
>     "slut": {
>       "matchMethod": 1,
>       "words": [
>         "imperfect",
>         "impure"
>       ]
>     },
>     "turd": {
>       "matchMethod": 0,
>       "repeat": true,
>       "words": [
>         "poop"
>       ]
>     },
>     "whore": {
>       "matchMethod": 1,
>       "words": [
>         "tramp"
>       ]
>     },
>     "wtf": {
>       "matchMethod": 0,
>       "repeat": true,
>       "words": [
>         "what"
>       ]
>     }
>   }
> }

**Comment by richardfrost** [comment]
Did you figure out if it might have been the Feedpro addon?

**Comment by richardfrost** [comment]
Sounds good! I'm glad its working, at least for now!
