### ISSUE TITLE
Offensive words in 

### ISSUE THREAD

**Issue by tonyram57** [richardfrost/AdvancedProfanityFilter#106]
I notice now when go into the extension to show how many words are blocked it censors the words but when I just move my mouse cursor just to get into options it shows the offensive word.  It is annoying because all I have to do is move my mouse cursor over by accident very easy to do by trying to go into options  and the swear word shows clear as day.

I don't see the purpose of **** or s*** the word but the word shows up simply my highlighting it.  Would be better if there was a warning maybe double click or something to show the word.
![2018-10-28_155532](https://user-images.githubusercontent.com/39742654/47621177-4de67d00-daca-11e8-9914-36710a8e37c3.jpg)
![2018-10-28_155615](https://user-images.githubusercontent.com/39742654/47621178-50e16d80-daca-11e8-9ae5-c5d75c350886.jpg)

**Comment by tonyram57** [comment]
Also censoring the word hell is not needed either.

**Comment by richardfrost** [comment]
@tonyram57 I agree that the current method to reveal the summary words is not great. I'd love your opinion: Do you prefer having a checkbox that would reveal all words, or, click on the row to reveal the single word (row) that was clicked on?

As far as the word `hell` goes, it was requested by a few other users as being default. I know everyone has different thresholds of sensitivity, but that makes it hard to please everyone. I have been brainstorming on an idea to compile a repository of configurations that people could use. Then we could have a default config, a strict config, other languages (which users would have to submit, because I only speak English), etc. In the mean time, if you remove that word from your config it shouldn't bother you again.

**Comment by tonyram57** [comment]
An checkbox would be better also you can add an option in settings to hide the filtered words not get rid of the number of swear words on the icon but an option to set it the way it was before.

Also having different config's for levels for swear words like some game chat's have would be great.  Hell does not bother me but the b** word does as damn when it is used as godd**m so a leveled filter would work out fine for everyone.

**Comment by richardfrost** [comment]
1. I will work on adding some kind of switch to the summary interface.

2. I don't quite understand what feature is missing, could you elaborate?
> also you can add an option in settings to hide the filtered words not get rid of the number of swear words on the icon but an option to set it the way it was before.

Do you just mean add an option to not show the summary in the popup?

3. I will see what I can do. I know everyone has different preferences, and I want to make it as universal and simple as possible. I think my first attempt will be to dial back the defaults a little bit, but then provide a link for users to go try out different configurations (more strict, different languages, etc.)

4. I will add the N-word. It hasn't been requested before, and thankfully I haven't happened upon it to much in my own use, but its definitely a good one to filter. As far as variants go, did you add the word with an `exact` match? The behavior you are describing sounds like it. I would recommend using a `Partial Match` instead, which should match both examples that you gave. You can go a step further and set it to match repeated characters too, which might match a few other alternate spellings. For that word I think it would be a good fit.

If you are interested, you can read more about the different options in the [wiki](https://github.com/richardfrost/AdvancedProfanityFilter/wiki).

**Comment by tonyram57** [comment]
Ignore number 2 request I just meant a switch to the summary interface.

**Comment by richardfrost** [comment]
Sorry this has taken so long, but I did make the Popup summary optional now. You can turn it off in the settings if you would like to.
