### ISSUE TITLE
Filter issue with motherboard.vice.com

### ISSUE THREAD

**Issue by tonyram57** [richardfrost/AdvancedProfanityFilter#114]
Issues with this site
https://motherboard.vice.com/en_us/article/wjmqmq/upcoming-version-of-google-chrome-will-make-it-harder-to-block-ads
The word "pissed" is not filtered however when refreshing the page the word is filtered then after the page fully loaded it is uncensored again.

Thanks.

**Comment by richardfrost** [comment]
Sorry for the delay, I've been really swamped. I can definitely reproduce this, so thank you for reporting it. I am working on a fix. This actually uncovered a pretty big whole in the extension, so it may take a bit to get it all worked out.

**Comment by tonyram57** [comment]
No problem.  Thanks for the great extension and I did donate $5 BTW.

**Comment by richardfrost** [comment]
Sorry for the delay, I've gone ahead and released version 2.0.0 and it should address this issue (and similar ones). It was a very large change, so if you notice any regressions please don't hesitate to let me know. In my testing it works in the instance you gave, but if you have trouble please let me know.
