### ISSUE TITLE
Not filtering on highlight.

### ISSUE THREAD

**Issue by tonyram57** [richardfrost/AdvancedProfanityFilter#120]
Warning this is a stupid site did not visit on purpose found it doing a Bing search of Doctor Who
http://www.landoverbaptist.net/showthread.php?t=93085
but noticing it does not filter on highlight word "slut" however it is filtered on the actual site so it might affect legitimate sites.
![2019-03-06_154659](https://user-images.githubusercontent.com/39742654/53912627-54ac7000-4027-11e9-95cf-e4a07aae7ff0.png)

**Comment by richardfrost** [comment]
I didn't have a chance to look at this before you closed the issue. Is it still a problem?

**Comment by tonyram57** [comment]
Sorry reopened issue.  Yes but only on certain forums.  I noticed that any that use vBulletin.  However many use the newer XenForo don't have that issue.

**Comment by richardfrost** [comment]
Do you have any examples of how to get to a page that doesn't work? When I click on that link it seems to work as expected to me.

**Comment by tonyram57** [comment]
I have not found any other issues which is why I am going to close it for now.  All the "normal" forms I visit work fine so it is not an issue now.

**Comment by richardfrost** [comment]
Okay, sounds good. Thanks for keeping an eye out for issues and reporting them!
