### ISSUE TITLE
Feature request: how long to mute when using auto-generated subtitles

### ISSUE THREAD

**Issue by qwertychouskie** [richardfrost/AdvancedProfanityFilter#121]
Audio filtering ideally should have an option to configure how long a word is muted as it doesn't always quite mute the whole word.

BTW, thanks for such an awesome addon!

**Comment by richardfrost** [comment]
Thanks for the feedback. I'm glad you are enjoying the filter.

Are you thinking that each word should have an option to specify a mute time, or just a general rule for if a word is muted, the audio must be muted for at least the specified amount of time?

**Comment by qwertychouskie** [comment]
The main thing I notice is that with youtube's auto-generated subs, the period the filtered word shows in the subtitles before the next word appears is sometimes like a couple milliseconds, meaning the filter only mutes for a couple milliseconds, which obviously won't do much good. :)  Any way to work around this would be good.

**Comment by richardfrost** [comment]
Version [2.1.2](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.1.2) has been published and should be available soon with a feature to hopefully address this. You can find the setting in the at the bottom of the Audio options page. Let me know if it works for you, or if you have other suggestions to make it better.

**Comment by qwertychouskie** [comment]
Thanks!

**Comment by richardfrost** [comment]
You're welcome! Fell free to comment here or open a new issue if its not working for you. Thanks again for the suggestion.
