### ISSUE TITLE
Issue with less-than sign

### ISSUE THREAD

**Issue by ClaytonFabiano** [richardfrost/AdvancedProfanityFilter#124]
## Description

I'm trying to write an expression with less-than sign (lookbehind), and anything from the less-than sign is cropped in "Words & Phrases" list, and the expression is not displayed properly in popup summary, when detected in page.

The expression works, this is only a visual issue, affecting only the visualisation in popup summary.

### Details (Bugs Only)

Chrome Version: 73.0.3683.75 (Versão oficial) 64 bits
Extension Version: 2.0.3
Operating System: Windows 7 x64

### Steps to reproduce (Bugs only)

1. Settings/"Filter word list in Options" unchecked. Using "Censor" filter method.
2. In "Word/Phrase" i add "a<b", using Exact match, showing only "a" in "Words & Phrases" list. I tested writing "a<b" in www.regextester.com, showing nothing in popup summary, and when i hover, showing "a[censor character]".
3. In "Word/Phrase" i add "(?<!un)censored", using Regex match, showing only "(?" in "Words & Phrases" list. I tested writing "censored" in www.regextester.com, showing nothing in popup summary, and when i hover, showing "(?(?".

### Screenshots

![less-than sign 1](https://user-images.githubusercontent.com/48736243/54646695-b84e8880-4a7e-11e9-863a-ef9cd175a3f3.png)
![less-than sign 2](https://user-images.githubusercontent.com/48736243/54646696-b8e71f00-4a7e-11e9-8191-7b531833e33b.png)
![less-than sign 3](https://user-images.githubusercontent.com/48736243/54646697-b8e71f00-4a7e-11e9-8b4a-6587c17955a6.png)
![lookbehind 1](https://user-images.githubusercontent.com/48736243/54646698-b8e71f00-4a7e-11e9-817f-358db085a3c1.png)
![lookbehind 2](https://user-images.githubusercontent.com/48736243/54646699-b8e71f00-4a7e-11e9-9852-632c250ff44c.png)
![lookbehind 3](https://user-images.githubusercontent.com/48736243/54646700-b97fb580-4a7e-11e9-8d74-c11e0dc69fe8.png)

**Comment by richardfrost** [comment]
Wow, thank you so much for all the wonderful info and examples! It made it really easy to spot the problem. I'll get it fixed right away.

**Comment by richardfrost** [comment]
This should be addressed in version `2.0.4`, which has been submitted to the stores. Let me know how it works for you @ClaytonFabiano.

**Comment by ClaytonFabiano** [comment]
Thanks for the update! It works good now with my lookbehind expressions. See the screenshots.

Screenshots:
![resolvido 1](https://user-images.githubusercontent.com/48736243/54716333-40429a00-4b34-11e9-88f7-c78fac4529d2.png)
![resolvido 2](https://user-images.githubusercontent.com/48736243/54716334-40db3080-4b34-11e9-9b56-09de51fb29c7.png)
![resolvido 3](https://user-images.githubusercontent.com/48736243/54716335-40db3080-4b34-11e9-884d-f8ecb54765e1.png)

**Comment by richardfrost** [comment]
@ClaytonFabiano Thanks for reporting back!
