### ISSUE TITLE
Extension does not  work in search engine pages

### ISSUE THREAD

**Issue by LeetJack** [richardfrost/AdvancedProfanityFilter#132]
## Description
The extension does not work in Google, Bing, DuckDuckGo and Yandex search pages.

### Details
Opera Version: 60.0.3255.27
Extension Version: 2.1.0
Operating System: Windows 7 Ultimate x64.
Site (s) Affected: Google, Bing, DuckDuckGo and Yandex search pages.

### Steps to reproduce
1. Open a search engine like Google, Bing, DuckDuckGo or Yandex.
2. Make a search using a word that you previously blocked.
3. See that the word is not blocked or modified like in other sites.

## Other details
The Opera version is irrelevant, that bug exists since when i started using this extension in Opera 57.

### Screenshots
Word blocked on extension
![3](https://user-images.githubusercontent.com/15880193/56073201-917e2c00-5d76-11e9-9d60-9f4a87919026.png)

Google page opened ready to search
![1](https://user-images.githubusercontent.com/15880193/56073199-917e2c00-5d76-11e9-88a9-7162dc33e4f8.png)

The Google search page with word not blocked in any case
![2](https://user-images.githubusercontent.com/15880193/56073200-917e2c00-5d76-11e9-89ec-de5db63bc60d.png)

Ramdom website with the word blocked right
![4](https://user-images.githubusercontent.com/15880193/56073202-9216c280-5d76-11e9-90be-6d4e3c205578.png)

**Comment by richardfrost** [comment]
This is actually caused by an Opera setting. If you go the the Extension dashboard that lists your extensions you should see a similar page. Simply give the extension permissions to run on search result pages:

![image](https://user-images.githubusercontent.com/1507205/56074011-9d62f180-5d68-11e9-9201-d15d7003654a.png)

Let me know if that works for you, or if you have any other questions.

**Comment by LeetJack** [comment]
Works fine ^^

Thanks.

**Comment by richardfrost** [comment]
No problem! I actually didn't know about that option before you brought up the issue, so thanks for helping me learn something new! Glad its working for you now.
