### ISSUE TITLE
Experimental Audio Muting Stopped Working on YouTube

### ISSUE THREAD

**Issue by ElectricDrake** [richardfrost/AdvancedProfanityFilter#134]
Issues are used primarily to track bugs in the project. Feature requests can be submitted either as an issue or [here](https://goo.gl/forms/LTqFpJ0mCTsrgGgf2).

## Description

Experimental Audio Muting was working quite well on YouTube Videos with subtitles (muting was on target about 95% of the time!) It stopped muting all together recently. Please bring it back!

### Details (Bugs Only)

Chrome Version: Version 73.0.3683.103 (Official Build) (64-bit)
Extension Version: 2.1.1 (latest as of this writing)
Operating System:
Site(s) Affected: YouTube with cc on

### Steps to reproduce (Bugs only)

1. Play YouTube Video with Experimental Audio on
2. Turn on cc
3. Browser does not mute at all (note: I know the timing wasn't perfect before and I'm ok with that - it was still really awesome muting like ~95%!) but now it stopped muting at all.
4.

## Other details

This has been this way for a little while, I think at least two versions ago it stopped.

**Comment by ElectricDrake** [comment]
Note: I also checked with Firefox and found the same result. Thanks!

**Comment by richardfrost** [comment]
Hi @ElectricDrake, I'm glad that you have found the audio muting useful (at least when it was working). I just tested it on a couple videos, and it actually worked as expected for me. Would you be able to give me an example video that it isn't working for?

**Comment by ElectricDrake** [comment]
Absolutely! -  the truth is I am an absolute nerd and love to watch Critical Role, but sometimes they swear like sailors and your app turns like 250 swears into 2-3 (which is nice). Example is here:
https://www.youtube.com/watch?v=P-cQdxZB5Kk&t=41s 
Maybe I don't have the settings right - but then that doesn't make sense because I had it working before. Thank you for your response.

**Comment by richardfrost** [comment]
Thanks for sending the example. We all gotta nerd out sometimes! 😄 For some reason I had it in my head  that you said the auto subs stopped working, which uses a different process for audio muting. That's what I tested, and it seems like its still working. It does look like the regular subtitles broke from an update to the site, so I'll try and get that addressed today!

I'm glad that you have found it useful so far. Its always encouraging to hear other people find it useful.

**Comment by ElectricDrake** [comment]
Yeah I'm just using regular subtitles. Awesome thank you - indeed I have found it very nice!

**Comment by richardfrost** [comment]
Alright, version [2.1.2](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.1.2) has been published and should be available soon with the issue fixed. Let me know if it solves the problem for you!

**Comment by ElectricDrake** [comment]
Awesome thank you! Yes it is fixed!
