### ISSUE TITLE
Substitution Filter Typo

### ISSUE THREAD

**Issue by ExpletiveNotExplative** [richardfrost/AdvancedProfanityFilter#138]
Issues are used primarily to track bugs in the project. Feature requests can be submitted either as an issue or [here](https://goo.gl/forms/LTqFpJ0mCTsrgGgf2).

## Description
For some of the default substitution filters, "explative" is not the correct spelling.  The correct spelling is "expletive."

See https://en.wiktionary.org/wiki/expletive

### Details (Bugs Only)

Browser Name: All
Browser Version: All
Extension Version: All
Operating System: All
Site(s) Affected: All

### Steps to reproduce (Bugs only)

1.
2.
3.
4.

**Comment by richardfrost** [comment]
Good catch! I'll get the defaults fixed.

**Comment by richardfrost** [comment]
Keeping this open until the fix is released.

**Comment by richardfrost** [comment]
Version [2.1.4](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.1.4) has been released now.
