### ISSUE TITLE
Hulu Support

### ISSUE THREAD

**Issue by notanewbie** [richardfrost/AdvancedProfanityFilter#141]
Issues are used primarily to track bugs in the project. Feature requests can be submitted either as an issue or [here](https://goo.gl/forms/LTqFpJ0mCTsrgGgf2).

## Description

Any plans on adding support for Hulu? So far the extension only modifies the captions--which is really nice BTW because that means I can have captions but not worry about people around me seeing the language I'm hearing, if I have headphones on like I usually do--but I'm watching Atlanta and I'd like to be able to show scenes to my brother without having to make him wade through all the cursing.

**Comment by richardfrost** [comment]
I don't have a subscription there, but it looks like there is a free trial, so that's nice. I will try to get to it in the next couple days. Thanks for the suggestion.

**Comment by richardfrost** [comment]
Its not released yet, but I think I have it working.

dd80feb15f5f627de48c778345abff5301994933 Support for Hulu Audio Muting

**Comment by notanewbie** [comment]
Thank you!

**Comment by richardfrost** [comment]
Version [2.1.4](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.1.4) has been released now.
