### ISSUE TITLE
Audio Silencing: Tab stays muted if reloaded

### ISSUE THREAD

**Issue by JayH2971** [richardfrost/AdvancedProfanityFilter#146]
#### :bug: Description
Silencing remains effective when tab is reloaded at precise point. (Tab muting)

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Find a point in a Youtube video at which audio silencing happens.
2. Pause the video.
3. Right-click on the video and choose "Copy video URL at current time."
4. Paste and go into address bar.
5. The video on this tab will remain silenced when it resumes, even if APB is disabled. The tab options "Mute site" and "Unmute site" do not remedy.

#### :heavy_check_mark: Expected behavior
The silencing should cease when the video is reloaded.

#### :computer: Details
 - **OS:** Linux Mint 19.1
 - **Browser:** Chromium
 - **Browser Version:** Version 74.0.3729.169
 - **Affected site(s):** www.youtube.com

#### :pencil: Additional context
Videos in other tabs are not affected.

**Comment by richardfrost** [comment]
Good catch. Thanks for reporting the issue. I'll get an update to address this soon!

**Comment by richardfrost** [comment]
This should be fixed in [2.1.5](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.1.5). Feel free to comment if you want to provide feedback, or if the issue has still not been addressed.
