### ISSUE TITLE
Include spacing

### ISSUE THREAD

**Issue by JayH2971** [richardfrost/AdvancedProfanityFilter#149]
Is there a way to include spacing as part of a prohibited phrase? For example:

I don't want to censor "lord" or "my lord" but I do want to censor "oh my lord." Does APF support inclusion of spaces?

**Comment by richardfrost** [comment]
Yes, it does support spaces inside a phrase. Is it not working for you? In your case, it should match with either the Exact or Partial match method.

You should be able to add it either in the options page, or by selecting the text on a page, open the context menu (Right-click menu) and then selecting `Advanced Profanity Filter` -> `Add selection to filter`.

Words/phrases are trimmed (outside/surrounding spaces removed) when saved.

Example: The phrase '  hello there  ' will be saved as 'hello there'.

**Comment by JayH2971** [comment]
I added it to APF and tried both Exact and Partial, but neither are working. Here's the time stamp I'm trying it on: https://youtu.be/qYNlSVVQSKI?t=36

Maybe it's because the words show up gradually in the captions?

**Comment by richardfrost** [comment]
Ah. Yes, YouTube auto-generated subtitles are filtered word by word, meaning that it only filters on the specific word that is "active". I can look into other possibilities and report my findings.

**Comment by JayH2971** [comment]
Sorry, I forgot to mention it was on the audio matter. No rush, all the most important words to censor are short and simple :smile:

**Comment by richardfrost** [comment]
Uunfortunately I don't think this will be possible right now. I'll try to update if something changes in the future. Thanks again for reporting this, and feel free to report other issues or feature requests in the future!
