### ISSUE TITLE
Hulu subtitles

### ISSUE THREAD

**Issue by nunyabeeswax7** [richardfrost/AdvancedProfanityFilter#153]
#### :bug: Description
Something is causing the hulu subtitles to not show up when the filter is on. When the filter is off, the subtitles are back.

#### :computer: Details
 - **Device:** [e.g. MacBook Pro, Google Pixel]
 - **OS:** [e.g. MacOS 10.14, Windows 10]
 - **Browser:** [e.g. Chrome, Firefox]
 - **Browser Version:** [e.g. 50]
 - **Affected site(s):** [e.g. www.google.com]

**Comment by richardfrost** [comment]
Thanks for reporting the issue. I have a couple questions:

- In the Filter's settings page on the Audio tab, what is the "Subtitles" config set to?
- Is it only on Hulu (ex. not happening on Youtube)?
- Is the muting working?

**Comment by nunyabeeswax7** [comment]
Actually I just realized, the muting just isn't working.

**Comment by richardfrost** [comment]
@nunyabeeswax7 Can you answer the other questions I asked above (you can skip the last one)? I just want to make sure I understand the issue you are facing. Thanks!

**Comment by nunyabeeswax7** [comment]
They were on show filtered only and it's just Hulu that it's not working on.

**Comment by richardfrost** [comment]
Thanks for the information! If you turn it to "Show all" do the subtitles come back like normal? I will try to get with my coworker tomorrow and test on his Hulu account.

**Comment by nunyabeeswax7** [comment]
Yes, the subtitles are back. I had already figured out what my problem was hours ago.

**Comment by richardfrost** [comment]
Sounds good. So the muting still isn't working as expected though, right?

**Comment by nunyabeeswax7** [comment]
No

**Comment by richardfrost** [comment]
Do you have an example video that isn't working? I have tested on a few and they seem to be working okay for me. It might also help if you could [backup](https://github.com/richardfrost/AdvancedProfanityFilter/wiki#config) and attach your config here so that I can test with that.

**Comment by nunyabeeswax7** [comment]
I don't know how to do that.

**Comment by richardfrost** [comment]
You don't have to share your config, but can you give me an example of a video that doesn't work?

**Comment by nunyabeeswax7** [comment]
I think I know what the problem is, I had recorded the movie I was watching (Beetlejuice) when it was playing live. I just tested it on another video and the filter worked fine. I think it has something to do with the fact that Beetlejuice was recorded live.

**Comment by richardfrost** [comment]
Oh, yeah - that must be it. Sorry about that. So are we okay to close the issue then, or is there something else you'd like me to look at?

**Comment by nunyabeeswax7** [comment]
Yeah, you can close the issue. Thanks.
