### ISSUE TITLE
Sony Crackle Audio Support

### ISSUE THREAD

**Issue by richardfrost** [richardfrost/AdvancedProfanityFilter#159]
#### :movie_camera: The Site
_www.sonycrackle.com_

#### :speech_balloon: Subtitle Element/Node
_Example:_
```html
subtitle text
```

#### :pencil: Additional notes
This site uses plain-text nodes, which don't conform to the existing supported custom audio site properties.

**Comment by richardfrost** [comment]
This is a work in progress 🚧 ⚠️ 

To test it, please use one of the following packages:

[extension-chrome.zip](https://github.com/richardfrost/AdvancedProfanityFilter/files/3563111/extension-chrome.zip)
[extension-firefox.zip](https://github.com/richardfrost/AdvancedProfanityFilter/files/3563112/extension-firefox.zip)


Here is the custom config to test with:
```
{
  "www.sonycrackle.com": {
    "textNode": true,
    "textParentSelector": "div.clpp-subtitles-container"
  }
}
```

This is temporary, and config options are likely to change before a stable release.

**Comment by DarthFlappy** [comment]
I think you forget to add a note about this (wonderful) box:
![box](https://user-images.githubusercontent.com/51761369/64376571-95953980-cff6-11e9-80df-2ebca003c2a7.png)

**Comment by DarthFlappy** [comment]
Works for me after adding that string to the box.
When will you make this feature not "experimental"?

**Comment by richardfrost** [comment]
Thanks for testing it out! I'm hoping very soon to put this in the official release. I'm just trying to finish up a couple last minute things and I'll get a new version released. I did forget to mention the box on this issue, because I was hoping to get a release out before this, but that didn't happen unfortunately.

For those wanting to test it now, here is the documentation about the [custom sites](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Custom-Audio-Muting-Site) feature.

@DarthFlappy Do you have any other suggestions or comments regarding this (or another) feature?

**Comment by DarthFlappy** [comment]
Thanks for answering, but what I meant was: when would the Audio Muting feature not be off by default?

**Comment by richardfrost** [comment]
Ah, sorry I missed that. I actually don't have plans to make the audio muting on by default, but I'm open to reasons for it. My thought is that it could be confusing for someone who didn't enable it intentionally, and then have the audio cut out. The next version (hopefully only a day or two away now) should have the experimental notices removed, and hopefully make the page a little less confusing.

**Comment by richardfrost** [comment]
I've released a beta version to beta testers, and I'll post it here as well. If there are no problems reported, I plan on doing the official release tomorrow.

[extension-firefox-beta.zip](https://github.com/richardfrost/AdvancedProfanityFilter/files/3614336/extension-firefox.zip)
[extension-chrome-beta.zip](https://github.com/richardfrost/AdvancedProfanityFilter/files/3614337/extension-chrome.zip)

You can load this by following the instructions [here](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Load-Unpacked-Extension). Remember to disable the current version before testing the beta, and then remove the beta version when you are done testing. Only one filter should be active at a time.

To see the changes, take a look at #157. The bulk of the changes revolves around audio muting. Support for new sites has been added, a button that lists supported sites is available in the options page.

If anyone does decide to give it a try, feel free to report your experience here, or if you find a problem feel free to open an issue. Thanks!

**Comment by richardfrost** [comment]
Version 2.2.0 has been released, and should now support Sony Crackle by default.
