### ISSUE TITLE
Nitpicky Bug Report 

### ISSUE THREAD

**Issue by DarthFlappy** [richardfrost/AdvancedProfanityFilter#160]
**This is a nitpicky bug report**
1. On the settings page, go to the "Words" tab
2. Click on the drop-down "Words & Phrases" and click on a word on the list

At this point, while the word is selected in the drop-down list, it is not in the "Word/Phrase" box for editing as it should be.
![image](https://user-images.githubusercontent.com/51761369/64569015-41f25b00-d32a-11e9-89a6-ede9eb7fa233.png)

At this point, if you were to repeat the the process without refreshing the page, it would work as expected.

**Comment by richardfrost** [comment]
Interesting... I can't seem to replicate this behavior. What browser are you seeing this in? What OS are you using? What mode is the filter on (censor or remove)?

I'll look through the code to see if there could be a timing issue or something that might be causing it to happen for you.

**Comment by DarthFlappy** [comment]
Ok, sorry to not say what I found it on. The bug I found was in Chrome on MacOS. 
On Firefox, in both windows and mac, there were no problems.

**Comment by richardfrost** [comment]
Sorry this has taken so long. I don't have easy access to a Mac, but I did see a minor mistake in the code that _could_ have caused this issue. If you have some time, I'd love it if you could test this build and see if it resolves the issue. If it does, I'll get it put in an official release.

[extension-chrome.zip](https://github.com/richardfrost/AdvancedProfanityFilter/files/3719067/extension-chrome.zip)

[Loading unpacked extensions](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Load-Unpacked-Extension#testing-a-development-build)

**Comment by DarthFlappy** [comment]
Yes it fixes it. Thanks for dealing with my nitpicking!
