### ISSUE TITLE
script causing firefox to slow down

### ISSUE THREAD

**Issue by tischenkob** [richardfrost/AdvancedProfanityFilter#161]
#### :bug: Description
Website taking too long to load unless the extension is stopped

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Go to vk.com
2. Wait a couple seconds
3. See error

#### :heavy_check_mark: Expected behavior
I expect it to load well. There's no such problem in Chrome

#### :camera: Screenshots
![Screenshot_4](https://user-images.githubusercontent.com/47475386/66113778-264f3d00-e5d6-11e9-9222-4d9c64514964.png)

#### :computer: Details
 - **Device:** PC, Xiaomi Mi Notebook Pro 15''
 - **OS:** Windows 10, Ubuntu 18.04
 - **Browser:** Firefox
 - **Browser Version:** 69
 - **Affected site(s):** vk.com

**Comment by richardfrost** [comment]
Thanks for reporting the issue. Could you share the config your are using, or estimate the number of words that you have in your filter list? It is possible that a large filter lists can lead to slowdowns.

Could you also try allowing Advanced Profanity Filter in incognito, disable any others that might be enabled for incognito temporarily, and then try the check again in incognito mode? I just want to narrow down the issue, and unfortunately I haven't been able to re-create the issue with default settings.

**Comment by tischenkob** [comment]
I deleted all the English words and let the script run longer, it didn't help. You should probably be logged in, because there's no such problem in the incognito. The website is a Russian social network, perhaps the add-on has to process to many words when I sign in. There's no such problem while navigating through different sections but it reappears when I reload the page. Again, no such problem in Chrome.

**Comment by richardfrost** [comment]
Thanks for getting back to me. I have a few more questions:

In Firefox's private browsing (incognito), could you try logging in to vk and see if it still happens? If it doesn't, it is likely that another browser extension/add-on is conflicting with the filter. If so, would you mind sharing a list of the add-ons you have installed?

Now that you have deleted all the English words, do you have an estimate on how many words you are trying to filter? The way that the filter works, it has to check each of the words/phrases you want to filter, so the more words you are filtering, the longer it takes to work. If you don't mind, it might be easier for you to just export/copy your config and share it here. That way I can try to reproduce the problem more accurately. [Exporting config](https://github.com/richardfrost/AdvancedProfanityFilter/wiki#config).

Firefox has a more aggressive check for add-on performance than Chrome, so it doesn't come as much of a surprise that you don't see the message in Chrome. Really Chrome only shows a message when an extension stops responding.

So far I haven't been able to get that message to appear, but I will keep trying and if I can I will try to figure out where its seeing the slowdown, and do what I can to optimize that code path.

Sorry this isn't a very easy bug to address, but thanks for your help in trying to track it down.

**Comment by tischenkob** [comment]
It still happens in incognito and there are no other add-ons allowed in it. Thank you, too, here's the config:
[config.txt](https://github.com/richardfrost/AdvancedProfanityFilter/files/3703727/config.txt)

**Comment by richardfrost** [comment]
Thanks for sending that over. I am now able to replicate the issue, and I'll try to see if I can improve performance. The performance issue has to do with the "Advanced Mode" code. Does the site need to be set to advanced? All that really does is handle matching text that is split between multiple elements on the page.

Example:
```html
<span>some text to fil</span><span>ter</span>
```

On the page, this would look like: "some text to filter", but the add-on (without advanced mode) would see "some text to fil", and "ter". If you were trying to filter the word `text`, it would work as expected. If you were trying to filter the word `filter`, it would fail without Advanced mode being turned on.

Unfortunately the advanced mode is much more intense as it has to look at the elements around it, which greatly increases the amount of time it takes to check for words to filter.

**Comment by tischenkob** [comment]
Hm, I remember clicking it but I never really got to know what it does. Now I do, thanks! Guess there's no need for such complex filtering in my case. Thank you!

**Comment by richardfrost** [comment]
Awesome! So does the warning go away once advanced mode is turned off? Unfortunately I don't see much of a way to optimize the "Advanced feature". Thankfully, there are very few times it is needed.

**Comment by DarthFlappy** [comment]
Perhaps you could put your explanation of Advanced Mode on the wiki? It doesn't really explain it right now.

**Comment by richardfrost** [comment]
Great idea! I've put up an update of the wiki. If you have a minute, is there anything you think could use clarification, or anything else to add to it?

https://github.com/richardfrost/AdvancedProfanityFilter/wiki#advanced-mode

**Comment by DarthFlappy** [comment]
Looks great to me!

**Comment by tischenkob** [comment]
Yeah, there's no warning and the site loads significantly faster. Thanks!

**Comment by richardfrost** [comment]
Thanks @DarthFlappy for taking a look too! I'll go ahead and close this, but feel free to reply, or open a new issue if you have any trouble.
