### ISSUE TITLE
Amazon Video - Small Part of Subtitle Not Hidden

### ISSUE THREAD

**Issue by DarthFlappy** [richardfrost/AdvancedProfanityFilter#163]
This has been sighted on Firefox and Chrome:

On Amazon Video, with the Mute Audio setting being on and substitutes being set to "Hide All". A Small square still appears when the subtitle is supposed to be hidden.
![Screenshot 2019-10-07 at 6 52 54 PM](https://user-images.githubusercontent.com/51761369/66354730-c4733800-e933-11e9-9feb-65abc12dbc60.png)

I believe that this is part of the subtitle that is not hidden, as when there is no talking it goes away.

**Comment by richardfrost** [comment]
Thanks for bringing this to my attention. Now with more sites being supported, it has become harder for me to test everything, and unfortunately I missed this one. I can confirm that bug is present, and I'll try to get the fix in tonight and get a new version released.

**Comment by richardfrost** [comment]
Sorry I didn't have as much time as I was hoping, but it _should_ be fixed now. When you get some time, let me know if it is fixed for you.

**Comment by richardfrost** [comment]
Actually - I think it might be broken completely. 😦

I'll try to see why it isn't working for me anymore.

**Comment by DarthFlappy** [comment]
Yes, while the subtitle is hidden correctly, the muting does not turn on when a banned word is used.

**Comment by richardfrost** [comment]
Okay - I've submitted `2.3.1`, so once you have updated to it, can you see if the muting is working, as well as hiding the subtitles?

**Comment by DarthFlappy** [comment]
Yep, works great!
