### ISSUE TITLE
Filter has trouble with "smartwatch"

### ISSUE THREAD

**Issue by JJRicks** [richardfrost/AdvancedProfanityFilter#164]
_Instructions: This template is written in Markdown. Click the "Preview" tab to see what it will look like when submitted. Fill in the applicable sections (you can erase the examples if you'd like)._

#### :bug: Description
I think the filter needs an exception for "smartwatch." I can probably figure this out in settings easily, but the default setting censors it. 

#### :twisted_rightwards_arrows: Steps To Reproduce
Go to https://www.reddit.com/r/Android/comments/dfdeib/samsung_made_the_smartwatch_google_couldnt/ and it shows up in the title, for an example.

#### :heavy_check_mark: Expected behavior
Expected for the filter to ignore the word "smar_twat_ch"
#### :computer: Details
 - **Device:** [e.g. MacBook Pro, Google Pixel] HP Pavilion 15 
 - **OS:** [e.g. MacOS 10.14, Windows 10] Windows 10 Home 1903
 - **Browser:** [e.g. Chrome, Firefox] Firefox 69.0.2 (64-bit)
 - **Browser Version:** [e.g. 50]
 - **Affected site(s):** [e.g. www.google.com] All with the word on them

#### :pencil: Additional context
Thanks!

**Comment by richardfrost** [comment]
Thanks for pointing that out. I'll get a fix for it and include it in the next release. I'm hoping to get it out tonight.

**Comment by richardfrost** [comment]
Just wanted to check in and see if the issue was resolved in the latest version (3.3.0)?

**Comment by JJRicks** [comment]
Confirmed it works, thank you so much for the quick response and update!


//Joel

**Comment by richardfrost** [comment]
No problem! Thanks for reporting it, and helping to test!
