### ISSUE TITLE
Disney Plus

### ISSUE THREAD

**Issue by nunyabeeswax7** [richardfrost/AdvancedProfanityFilter#170]
_Instructions: This template is written in Markdown. Click the "Preview" tab to see what it will look like when submitted. Fill in the applicable sections (you can erase the examples if you'd like)._

#### :loudspeaker: The Shortcoming
Disney Plus has launched and the text filter doesn't work on it. 

#### :microscope: Describe the solution you'd like
Maybe you should try to make this compatible with DP. With the muting feature if you can, as well.

**Comment by DarthFlappy** [comment]
Here is the [link](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Audio#site-requests) to request that

Here the [link](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Custom-Audio-Muting-Site) to do it yourself if you want to, I am not sure if Richard Frost has D+ or not, but he is very fast responding to stuff like this. 

Here is the [link](https://github.com/richardfrost/AdvancedProfanityFilter/issues/new?assignees=&labels=Enhancement&template=muting_request.md&title=) for sending the data

**Comment by richardfrost** [comment]
Hello friends!

Thanks @DarthFlappy for sharing those links. I still haven't decided what the best way is to handle these requests. The main purpose for the google sheets was to make it so people without a github account had a good way of sending the requests. I'd probably rank ways of communicating in general from best to worst:

- Github issues (Keeps things all in one place)
- Google Form links (Especially for those without a github account)
- Email
- Chrome/Firefox Web Stores (I don't get notified)

Anyway, thanks again for stepping in and responding, I really appreciate it!

Now onto the issue: Unfortunately I don't have DisneyPlus, but thankfully they do offer a free trial, so I signed up for that. If @nunyabeeswax7 (or anyone else) would like to try it out and confirm that would be very helpful. Put this in the Custom Audio Sites box in the options page:

```JSON
{
  "www.disneyplus.com": {
    "mode": "cue",
    "videoSelector": "video.btm-media-client-element"
  }
}
```

**Comment by nunyabeeswax7** [comment]
Now there's another glitch. In watching an episode of Goof Troop I have the subtitles turned off but a line still got muted. I have the word "dick" as one of my forbidden words, and the line had "Moby Dick" in it. That's a safe use of the word, so unless I have the filter turned off, the line gets muted, subtitles or no.

**Comment by DarthFlappy** [comment]
> Now there's another glitch. In watching an episode of Goof Troop I have the subtitles turned off but a line still got muted. I have the word "****" as one of my forbidden words, and the line had "Moby ****" in it. That's a safe use of the word, so unless I have the filter turned off, the line gets muted, subtitles or no.

#171 Talks about this

**Comment by nunyabeeswax7** [comment]
No, it's different from that issue. It mutes the audio even when the subtitles are turned off. And it's all the words that I've got on my list.

**Comment by richardfrost** [comment]
Yeah, I think there are a few things at play here. 

1. On Disney+ it looks like they always send subtitles with the video, even when they are not active. The filter is currently just checking to see if there are subtitles/captions, and if there are it filters them. So it will probably need to get better at knowing when to filter/mute.
2. #171 would have some effect in that one instance of a "false positive".

I will take a look as soon as I get some time.

**Comment by richardfrost** [comment]
Version [2.5.1](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.5.1) has been submitted to the various web stores. Chrome will likely be the slowest to roll out and may take a number of days. If you would like to try the it out now, you can download the appropriate `.zip` file for your browser at the link above, and then follow the instructions to load an [unpacked extension](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Load-Unpacked-Extension).

This should fix problem 1 that I mentioned in my last comment. By default, the filter will not filter unless you specifically set the subtitles to show. This release also includes built-in support for Disney+, so you can remove the custom rule if you'd like.
