### ISSUE TITLE
Exact case

### ISSUE THREAD

**Issue by JayH2971** [richardfrost/AdvancedProfanityFilter#171]
#### :loudspeaker: The Shortcoming
Some words change meaning based on lower or upper case letters. My principal example is the ordinary name Dick, which is almost never used well in lowercase.

#### :microscope: Describe the solution you'd like
The ability to set "exact case" when choosing a word to filter.

#### :pencil: Additional context
This is the greatest extension! Thank you!

**Comment by richardfrost** [comment]
Thanks for the request, and especially for bringing an example with it! I dug into this for a few hours and really didn't feel ready to add an option for specifying "exact case". I'm not saying it couldn't be useful, I just don't think it fits well with the rest of the filter right now. If you have more examples, do let me know and I can try to work through them. Anyway, I think having an per-word option on whether it should match if it starts with a capital (proper name/capitalized word) does fit more in line with the rest of the filter's structure, so I went with that approach for now.

Working through this caused me to rewrite a large portion of the filter and pattern builder, which should hopefully make it easier to work with that portion of code in the future. Anyway, with this new version, all words will continue matching like they always have (case insensitive), but you can change a specific word to not match a capitalized version of itself (like the one in your example).

I'll try to get the new package built and available here tomorrow, and then get it published to the stores soon after that.

**Comment by DarthFlappy** [comment]
Perhaps a case-sensitive while list for words might work?

**Comment by richardfrost** [comment]
It definitely could work. I have played around with adding a word whitelist before, and every time ended up deciding against it in favor of preferring more options for words to filter. I do feel like this would fit the bill quite well here though.

I'm curious to know if a whitelist would be preferable to adding a "match capitalized" option? The main concern I have with the whitelist is just having it grow too large, but that is probably not very likely. I'm thinking it would be simplest just to have it be a case-sensitive global whitelist. Other ways it could be implemented might be to have it optionally be case-insensitive, or set each word to have its own whitelists. Just wondering if there is any input on which way people would like to see this go, or if anyone has other examples of things that might end up in the whitelist?

**Comment by richardfrost** [comment]
I am going to go ahead and get this merged in. I am still happy to consider a whitelist if anyone feels it is necessary or preferred.

**Comment by DarthFlappy** [comment]
A white-list might be useful so that people can use "partial" instead of "exact" and not need to be annoyed by false positives like "assume" and "nutshell".

**Comment by richardfrost** [comment]
I submitted version [2.6.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.6.0) today, which has the new word whitelist feature. You can read more about it in the [wiki](https://github.com/richardfrost/AdvancedProfanityFilter/wiki#whitelist). When you get the update, let me know if you have any feedback on the feature.

**Comment by JayH2971** [comment]
The whitelist is working perfectly. Thank you! You can close this anytime you feel you have enough feedback.

**Comment by richardfrost** [comment]
Thanks for the feedback! I'll go ahead and close it.
