### ISSUE TITLE
Twitch support

### ISSUE THREAD

**Issue by meyeci8743** [richardfrost/AdvancedProfanityFilter#175]
It would be great if Advanced Profanity Filter were to work on Twitch.  Of course, it's impossible to have profanity filtered on livestreams, but you can have it work on completed livestreams.

Here's an example: https://www.twitch.tv/videos/462485818

**Comment by meyeci8743** [comment]
Twitch lacks subtitles.

Sorry.  I'm not that technical.

**Comment by richardfrost** [comment]
I looked into it a bit, and twitch does seem to have [Closed Captions](https://help.twitch.tv/s/article/guide-to-closed-captions) on specific streams, and optionally streamers can add them. If anyone find an example of one, I'd be happy to take a look.
