### ISSUE TITLE
Not censoring f bomb

### ISSUE THREAD

**Issue by nunyabeeswax7** [richardfrost/AdvancedProfanityFilter#177]
I was watching a video on YouTube, and at the 7:33 mark the word "f*cking" appeared, the whole word. I made sure it's on my list of blocked words. Here's the link for the video: https://www.youtube.com/watch?v=-tbbX1K6DZE. I got it on advanced mode and that didn't work.

**Comment by richardfrost** [comment]
Sorry that the filter didn't work in this instance. Would you be willing to share your config here? I tried it a few times with my usual config and it filtered/muted as expected. You should be able to either copy-paste it here, or export it to a file and simply drag-and-drop the file into a new comment in this issue.

**Comment by nunyabeeswax7** [comment]
{
  "advancedDomains": [
    "www.google.com",
    "www.hitthefloor.com",
    "www.shiftermagazine.com",
    "www.amazon.com",
    "timeline.com",
    "www.salon.com",
    "medium.com",
    "www.cbsnews.com",
    "www.hulu.com",
    "www.fanfiction.net",
    "www.buzzfeednews.com",
    "www.vulture.com",
    "michaelminett4atgmail.blogspot.com",
    "seekeroftheparanormal.blogspot.com",
    "www.exclusivelygames.com",
    "tvtropes.org",
    "www.ranker.com",
    "observationdeck.kinja.com",
    "www.reeltoreelblog.com",
    "www.disneyplus.com",
    "www.vice.com",
    "www.youtube.com"
  ],
  "censorCharacter": "*",
  "censorFixedLength": 0,
  "customAudioSites": null,
  "defaultSubstitution": "censored",
  "defaultWordMatchMethod": 0,
  "defaultWordRepeat": true,
  "disabledDomains": [
    "myths.e2bn.org",
    "insearchofthinplaces.blogspot.com",
    "seeksghosts.blogspot.com"
  ],
  "enabledDomains": [],
  "enabledDomainsOnly": false,
  "filterMethod": 0,
  "filterWordList": false,
  "globalMatchMethod": 0,
  "muteAudio": true,
  "muteAudioOnly": false,
  "muteMethod": 0,
  "muteCueRequireShowing": true,
  "password": null,
  "preserveCase": true,
  "preserveFirst": false,
  "preserveLast": false,
  "showCounter": true,
  "showSubtitles": 0,
  "showSummary": true,
  "showUpdateNotification": true,
  "substitutionMark": false,
  "words": {
    "$h!t": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "$hit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "a$$": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "a$$h0£e": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "a*shole": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "a*sholes": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "apeshit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "arse": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "arsed": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "as*hole": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "ass": {
      "matchMethod": 0,
      "repeat": true,
      "sub": "butt"
    },
    "asscrackmactictac": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "assed": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "asses": {
      "matchMethod": 0,
      "repeat": false,
      "sub": "butts"
    },
    "asshat": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "asshats": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "asshattery": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "asshole": {
      "matchMethod": 1,
      "repeat": true,
      "sub": "jerk"
    },
    "assholery": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "assholes": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "asspull": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "b i t c h": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "b*ich": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "b*tch": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "b*tches": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "backthefuckupoffme": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "baiis": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "balless": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "balls": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "ballshit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "ballsiest": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "ballsy": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bastard": {
      "matchMethod": 1,
      "repeat": true,
      "sub": "idiot"
    },
    "bastardisation": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bastardise": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bastardised": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bastardization": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bastardize": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bastardized": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bastardizing": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bastardlyduck": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bastards": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "basterd": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "basterds": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "batshit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bejesus": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bi.t.ch": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "biching": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bicth": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bitch": {
      "matchMethod": 1,
      "repeat": true,
      "sub": "bench"
    },
    "bitchass": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bitchbot": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bitchcraft": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bitches": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bitchfest": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bitchier": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bitchiest": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bitchin": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bitchin'": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bitching": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bitchmedia": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bitchslap": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bitchslapped": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bitchslappin": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bitchslappin'": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bitchslaps": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bitchy": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bull$hit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bullshiat": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bullshit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bullshite": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bullshiting": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bullshittery": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bulshit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "buttdicks": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "bytch": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "c*nts": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "campersfuckoff": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "cavebitch": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "celebitchy": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "cheapass": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "chrissake": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "chrissakes": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "christ": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "christs": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "clausterfuck": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "clusterfuck": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "cock": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "cocks": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "cocksucker": {
      "matchMethod": 1,
      "repeat": true,
      "sub": "suckup"
    },
    "cocksuckers": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "cocksuckin": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "cocksuckin'": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "cocksucking": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "comicbastards": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "cowshit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "cum": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "cunt": {
      "matchMethod": 1,
      "repeat": true,
      "sub": "expletive"
    },
    "cunts": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dafuq": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dammit": {
      "matchMethod": 1,
      "repeat": false,
      "sub": "dangit"
    },
    "dammitjanet": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "damn": {
      "matchMethod": 1,
      "repeat": false,
      "sub": "dang"
    },
    "damned": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "damnit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "deadass": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dick": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dickbutt": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dickbutts": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dickdrip": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dickhead": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dickheads": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dickin": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dickin'": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dicking": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dickish": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dicks": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dickwad": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dinofuck": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dipshit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dispshit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dogshit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dragonagebullshit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dumbass": {
      "matchMethod": 1,
      "repeat": true,
      "sub": "idiot"
    },
    "dumbasses": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dumbfuck": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dumbfucks": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dutchbastards": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dyke": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "dykes": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "f u c k": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "f*ck": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "f*cking": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "f-u-c-k-e-d": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fag": {
      "matchMethod": 0,
      "repeat": true,
      "sub": "gay"
    },
    "faggot": {
      "matchMethod": 1,
      "repeat": true,
      "sub": "gay"
    },
    "faggotface": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "faggots": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fags": {
      "matchMethod": 0,
      "repeat": true,
      "sub": "gays"
    },
    "fanfuckintastic": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fatfuckfrank": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuck": {
      "matchMethod": 1,
      "repeat": true,
      "sub": "freak"
    },
    "fuckbag": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckbags": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckboi": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckbois": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckboy": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckboys": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fucked": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fucken": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fucker": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckers": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckery": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckgamergate": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckgoogle": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckhead": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckheaded": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckheads": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckice.com": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckig": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckin": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckin'": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fucking": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckity": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckles": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckn": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fucknut": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fucks": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fucksake": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fucktard": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fucktards": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckup": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckups": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckwad": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckwads": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckwit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuckwits": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fuking": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "furshit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "fvck": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "g*ddamn": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "gainerbitch": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "geniusbastard": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "god dam": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "god dammed": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "god dmn": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "godammit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "goddam": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "goddamit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "goddammed": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "goddammit": {
      "matchMethod": 1,
      "repeat": true,
      "sub": "dangit"
    },
    "goddamn": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "goddamned": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "goddamnit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "gossipingbitches": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "halfassed": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "hell": {
      "matchMethod": 0,
      "repeat": true,
      "sub": "heck"
    },
    "hella": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "helluva": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "hollywoodbitchslap": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "holyshit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "horseshit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "inurdreamsbitch": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "itsclydebitches": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "jacka*s": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "jackass": {
      "matchMethod": 1,
      "repeat": true,
      "sub": "jerk"
    },
    "jackshit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "jacobhymenshits": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "jerkass": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "jesus": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "kunt": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "lilbitch": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "lookinassjokes": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "magasshole": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "manshit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "mindfuck": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "mindfucker": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "mothafucka": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "mothafucker": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "motherfucked": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "motherfucker": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "motherfuckers": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "motherfuckin": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "motherfuckin'": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "motherfucking": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "muhfuckin": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "muthfuckin": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "nerdbastards": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "nigga": {
      "matchMethod": 0,
      "repeat": true,
      "sub": "bruh"
    },
    "niggas": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "niggaz": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "nigger": {
      "matchMethod": 0,
      "repeat": true,
      "sub": "man"
    },
    "niggers": {
      "matchMethod": 0,
      "repeat": true,
      "sub": "people"
    },
    "oneeyedbitch": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "piss": {
      "matchMethod": 1,
      "repeat": true,
      "sub": "pee"
    },
    "pissant": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "pissants": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "pissed": {
      "matchMethod": 1,
      "repeat": true,
      "sub": "ticked"
    },
    "pisses": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "pissin": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "pissin'": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "pissing": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "pissy": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "prick": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "pricks": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "pu*sies": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "pussies": {
      "matchMethod": 0,
      "repeat": true,
      "sub": "softies"
    },
    "pussy": {
      "matchMethod": 0,
      "repeat": true,
      "sub": "softie"
    },
    "r/quityourbullshit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "retard": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "retarded": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "retards": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "s h i t": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "sh*t": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "sh*thead": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "sh*theads": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "sh*ts": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shat": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shit": {
      "matchMethod": 1,
      "repeat": true,
      "sub": "crap"
    },
    "shitbag": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitbags": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitbred": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitcanned": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitcrisps": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shite": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shithead": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitheaded": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitheads": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shithole": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitholes": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shithouse": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitless": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitlibs": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitload": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitmomgroupssay": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitmuzzle": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitpost": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitposted": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitposter": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitposters": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitposting": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitposts": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shits": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitstain": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitstorm": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitter": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitters": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shittier": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shittiest": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shittily": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shittin": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shittin'": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitting": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitton": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shitty": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shittyadvice": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "shity": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "sickofyourfandombullshit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "skank": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "skanks": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "slickshit": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "smartass": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "smartasses": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "smartbitches": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "smartbitchestrashybooks": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "somebitch": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "sonbitch": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "sonofab*tch": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "sonuvabitch": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "stfubitchassrat": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "sunofabitch": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "thebitchysideoflife": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "ticketbitch": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "tits": {
      "matchMethod": 1,
      "repeat": true,
      "sub": "chest"
    },
    "titty": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "toodamnfilthy": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "twat": {
      "matchMethod": 0,
      "repeat": true,
      "sub": "dumbo"
    },
    "twats": {
      "matchMethod": 0,
      "repeat": true,
      "sub": "dumbos"
    },
    "unfuckable": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "whothefuckareyou?": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    },
    "worldclassbullshitters": {
      "matchMethod": 0,
      "repeat": true,
      "sub": ""
    }
  },
  "youTubeAutoSubsMin": 0
}

**Comment by richardfrost** [comment]
Okay, this is likely due to just how long it takes to process your wordlist, which is definitely on the large side. I'm exploring adding levels to words, I would expect it to work as expected if you took a backup of your config, restored the defaults, and then test it again. If it is the wordlist size then I think that will prove it. If you know it, it might help to know what kind of computer/device this is on, and what operating system (and version).

I'll see what can be done to try and speed it up a bit, but no promises. Semi-related, I'm also going to look into setting up some kind of level/profile for words. Still just exploring (no code written), but I'm thinking of maybe having a normal level (where you would specify your most commons words that you would like filtered), a strict level (with all words enabled), and an video/audio level (only used for muting purposes). If you have any other ideas or questions, let me know.

**Comment by richardfrost** [comment]
As a follow up to this, there was a bug that will be fixed in the next release where advanced mode was running even when it shouldn't have been. Advanced mode is slower, and may have been the cause of this. When the new version is released, I'd be interested to see if the problem you found is resolved or not. I'll update here when its released, and I'd love to hear back if you'd be willing.

**Comment by nunyabeeswax7** [comment]
Turning off advanced mode did the trick.
