### ISSUE TITLE
Substitution text duplicated multiple times between multiple <span> elements

### ISSUE THREAD

**Issue by AndroVGG** [richardfrost/AdvancedProfanityFilter#178]
For the example from Wiki:
`<span>some text to fil</span><span>ter</span>`

If substitution text for the word `filter` is `fix>`, then outcome is:

> **some text to fix>fix>**

That is, the substitution occurs for each `<span>` element.

**Comment by richardfrost** [comment]
Thanks for bringing this up! I found the issue and will get it fixed soon.
