### ISSUE TITLE
Filter Images

### ISSUE THREAD

**Issue by tonyram57** [richardfrost/AdvancedProfanityFilter#189]
Any plan on adding a filter for images.  You have one for removing it on videos.

Your extension removes all text profanity however I quite often still encounter it on images which are not filtered and I don't want to disable images in my browser.

It can be a beta opt on feature like with the videos and it may not be 100% effective can be improved by submitting images not being filtered but it will be something.

**Comment by richardfrost** [comment]
This would indeed be a useful feature, and has been requested before. The last time I investigated it, unfortunately I couldn't find any javascript libraries that would be able to handle the translation from images to text, and I don't have the expertise/time to build one. When I get some more time I'll look around and see if that has changed, because there are always new projects becoming available.

Thanks again for the suggestion!

**Comment by richardfrost** [comment]
Closing this for now, because its still not really possible. I've added it to a long-term task though, so I'll re-evaluate it if things change.

**Comment by richardfrost** [comment]
I know there is a lot of demand for this feature, but unfortunately it just still doesn't seem very feasible. I'll go ahead and re-open it for more visibility, and to see if anyone has new ideas that haven't been explored yet.

I also wanted to report that I have tested Tesseract.js, and while its really cool that it can all be done in the browser, its a very intense process. You can see an [example](https://omed.hplar.ch/webocr/#/home) of it, and a pretty [good writeup](https://golb.hplar.ch/2019/07/ocr-with-tesseractjs.html). But if you try that example, you'll see even on a pretty powerful machine (Intel i7 8700K), It's taking seconds to get results back. With it being that long for a single process, it just wouldn't work well for a browser extension unfortunately.

Another option would be to have dedicated OCR servers that could help with that load, but I don't have the infrastructure to support that load.

All this being said, once we had an OCR'd image, it isn't trivial to censor just the filtered text in it, so it would likely require simply hiding that image in full.

If it was just one image it might be tolerable to wait 3-4 seconds while a page was loading, but unfortunately there are many websites out there that are very image-heavy, and doing all that processing could mean loading times on a page being measured in minutes.

**Comment by richardfrost** [comment]
Also: https://xkcd.com/1425/

**Comment by tonyram57** [comment]
Thanks for trying to take care of the images. As I said your extension rarely fails and most of the time I encounter profanity is in images.

**Comment by richardfrost** [comment]
Yeah, its definitely an area that would have a big impact. I will continue to do what research I can on it.

**Comment by tonyram57** [comment]
What's the progress on this? As I said 99% I see profanity it's in images.

**Comment by richardfrost** [comment]
Unfortunately its about in the same place as before. I haven't had much time to experiment with things. Just want to set the expectation that this is not an easy task, and that it will definitely take some time. Also, I worry that there won't be a good way to accomplish it at a large scale (ie scanning every image on a page, or having it run on all pages).

I wanted to point out [my comment](https://github.com/richardfrost/AdvancedProfanityFilter/issues/189#issuecomment-703261545) from earlier. Try the tesseract example and you'll see what I mean about doing the processing in the browser and how long it takes. It is definitely outside the scope of this project (and my ability) to build an OCR library, so I will be required to use one that already exists.

I do think it might be possible on specific pages to perhaps do some image filtering. We could probably set it to only filter pictures over a certain size. Its definitely not something you would want on every page. I'm not trying to dismiss the importance of this feature, just trying to relay how hard of an issue it is to solve.

**Comment by tonyram57** [comment]
Just thought of this app for macOS 
https://textsniper.app/
It's able to take text from images and translate it into text.  Couldn't something be implemented similar to the filter.  So far it was able to capture most text I translated.

**Comment by richardfrost** [comment]
That's really cool. I'll have to see if they publish anything on the technology they use, and see if it might be helpful with this feature.

**Comment by richardfrost** [comment]
I'm going to consolidate all image/graphic filtering requests to issue #287
