### ISSUE TITLE
After changing anything in Config > Inline editor, two words revert back to default

### ISSUE THREAD

**Issue by CreeperPookie** [richardfrost/AdvancedProfanityFilter#194]
When I change something in the Inline editor, the f-word changes to "freak" and the b-word changes to "bench", even though I had both of those set to a different word before I had edited it.

**Comment by richardfrost** [comment]
Thanks for reporting the issue! I just tried to re-create it by:

1. Click on `Inline editor`
2. Modify substitutions for both the f-word and b-word
3. Click "Import" and then answer yes to save the changes
4. Then I modified the `showCounter` option, clicked "Import". The new substitutions seem to have been preserved, and did not revert to the defaults.

Can you share more detailed steps on how to re-create the issue? I'll double check the code, but so far I haven't been able to re-create this behavior.

**Comment by richardfrost** [comment]
Actually.. did you change them to `fudge` and `jerk`? If so, I found the issue.

**Comment by CreeperPookie** [comment]
Hello! Yes, those were the words I changed the words to.

**Comment by richardfrost** [comment]
Alright, I'll get that fixed in the next version. Thanks again for reporting it!

**Comment by richardfrost** [comment]
Released with [2.6.1](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.6.1)

If you notice any trouble after getting the update, feel free to comment and re-open this issue.
