### ISSUE TITLE
Official way to change capitalization of a filtered word

### ISSUE THREAD

**Issue by CreeperPookie** [richardfrost/AdvancedProfanityFilter#200]
Though minor, sometimes I want to filter some words with a specific capitalization on top of the auto-detect capitalization, for example: replacing "test" with "Test" or "foo" to "FoO". The only way I was able to fix this was to use the inline editor, and change it that way, which while isn't hard to do, would be nice if there was an official way to do so.

**Comment by richardfrost** [comment]
This feature has been released in version [2.22.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.22.0). You'll find it in the word editor (and bulk editor) next to the substitution text box. If you turn on "Case-sensitive" it will save the case you specify and override the `preserveCase` option.

I also boosted the `preserveCase` option to handle phrases (multiple words), if you're interested. Let me know if you get a chance to try it out how it works for you. Feel free to reply here in the issue, even if its closed. Thanks for your contributions!
