### ISSUE TITLE
Facebook beta - censoring breaks "see more" functionality

### ISSUE THREAD

**Issue by wmq** [richardfrost/AdvancedProfanityFilter#201]
#### :bug: Description
In new Facebook beta interface (available to some people), having this extension ON breaks the functionality of "See more" link on comments inside groups. When I click such a link on a comment with filtered words in it, it will simply cut everything that was already hidden "under" the _See more_ link.

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Have access to new Facebook beta interface.
2. Find a comment on Facebook that is long enough that it has "See more" link at the end of it – and at the same time contains a filtered word.
3. Click the "See more" link.
4. All of the expected additional text is missing.

#### :heavy_check_mark: Expected behavior
Facebook should load the rest of the comment.

#### :camera: Screenshots
With extension enabled:
![Extension enabled](https://i.imgur.com/QbidPTD.png)
After clicking "See more" link – the rest of the comment is missing:
![Extension enabled - effect](https://i.imgur.com/VeN5JPF.jpg)
Expected behaviour, with extension disabled:
![Extension disabled](https://i.imgur.com/shPZoV3.png)
 
#### :computer: Details
 - **Device:** Desktop
 - **OS:** Windows 10
 - **Browser:** Chrome
 - **Browser Version:** 80
 - **Affected site(s):** www.facebook.com (beta version only)

#### :pencil: Additional context
Extension is in _Censor_ mode, _Per Word_ matching, _Partial_ match method.

Comments that do not contain any filtered word are expanding normally – even with extension enabled.

**Comment by richardfrost** [comment]
Thanks for the great description, and the screenshots! Unfortunately I don't have access to the beta version of facebook right now, so this might have to wait until I get access to it.

**Comment by richardfrost** [comment]
I still haven't seen this yet, so I'm going to close it. Feel free to comment here if someone can help me re-create the issue, or open a new issue. Thanks.
