### ISSUE TITLE
Wild cards or regex allowed in whitelist words

### ISSUE THREAD

**Issue by skeets23** [richardfrost/AdvancedProfanityFilter#208]
#### :loudspeaker: Wild cards and / or regex in whitelist words
There are a lot of Japanese names that end in "shita" as in "Yamashita". I'd like to whitelist "*shita", so that I don't get "Yamacrapa" instead of "Yamashita" (can cause some really embarrassing copy paste errors 😱).

#### :microscope: Add an option to add regex for a whitelisted word, or for a wild card (*)
Could fix the problem if adding "*shita" as a whitelist word was allowed.

#### :triangular_ruler: Alternative solution
I suppose I could just remove the problem word from the black list. But that's a pretty common swear word, I'd rather whitelist the exceptions.

**Comment by richardfrost** [comment]
Sorry, I've just been really busy lately. I will try to take a look at this soon!

**Comment by nunyabeeswax7** [comment]
I'm having this problem too. I've no issue with the word "damnation" but it's filtering out the first half of the word, when I don't want it to.

**Comment by richardfrost** [comment]
I'm hoping to take a look at this soon.

For your exact case @nunyabeeswax7, you might try adding `damnation` to the case-insensitive whitelist.

@skeets23 Perhaps for now you can change the match method of the `s---` word to exact.

**Comment by nunyabeeswax7** [comment]
I tried putting it on exact, and it doesn't work.
