### ISSUE TITLE
www.funimation.com

### ISSUE THREAD

**Issue by oo7goofy** [richardfrost/AdvancedProfanityFilter#210]
_Instructions: This template is written in Markdown. Click the "Preview" tab to see what it will look like when submitted. Fill in the applicable sections (you can erase the examples if you'd like). For more information, please see [this page](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/New-Audio-Muting-Site)._

#### :speech_balloon: Subtitle Element/Node
_Example:_
```<div class="vjs-text-track-display" aria-live="off" aria-atomic="true"><div style="position: absolute; left: 0px; right: 0px; top: 0px; bottom: 0px; margin: 1.5%;"><div style="text-align: center; font: 14.65px sans-serif; white-space: pre-line; position: absolute; direction: ltr; writing-mode: horizontal-tb; left: 0px; width: 612.094px; top: 253.094px; bottom: 8px; right: 0px; height: 32px; background-color: rgba(0, 0, 0, 0);"><div style="color: rgb(255, 255, 255); background-color: rgb(0, 0, 0); position: relative; left: 0px; right: 0px; top: 0px; bottom: 0px; display: inline; writing-mode: horizontal-tb; unicode-bidi: plaintext; font-family: sans-serif;">I'm gonna roast that
damn nerd today!</div></div></div></div>
```

#### :pencil: Additional notes
_Add any other context or screenshots about the request here._

**Comment by oo7goofy** [comment]
I was able to get the replacement working for subtitles but it still doesn't mute the volume. I've tried both tabs and volume.

**Comment by oo7goofy** [comment]
{
  "www.funimation.com": {
    "mode": "element",
    "subtitleSelector": "div.vjs-text-track-display",
    "tagName": "DIV"
  }
}

**Comment by richardfrost** [comment]
Good job trying to find a config that works! You actually weren't too far off. Unfortunately the existing filter code isn't capable of doing everything it needs to, so it won't work without an update.

If you'd like to test what I have right now, I can share a development build of the filter. Just let me know what browser(s) you would prefer.

I am just putting on the finishing touches for version `2.7.0`, so hopefully support for Funimation will be official very soon.

**Comment by oo7goofy** [comment]
I’d be happy to test a build for you. I subbed over on Patreon also. Do you have the discord up and running?

**Comment by richardfrost** [comment]
Thank you so much for the support!

You've caught me off guard a bit with still getting Patreon and Discord setup. But, here is an invite to the [Discord server](https://discord.gg/MpE5Z3f). In the next couple days I'll get things moving!

Brave should work fine, but if you do run into trouble with it, maybe give it a quick try in Chrome. Let me know if it does give you trouble! Amazon does have some issues with the current version, but I'm hoping that this new version should resolve those too (if you'd like, feel free to test that as well with this test version).

[Here](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Load-Unpacked-Extension) are some quick instructions on how to load an unpacked (or development) extension/add-on. If those instructions don't directly apply to your browser, usually a quick search online can find specific directions. If all else fails, let me know!

To re-iterate what is on that page, don't forget to **Disable the current version of Advanced Profanity Filter**, as having both running will cause conflicts.

Here is the filter: This one should work on Chrome and any Chromium based browser (like Brave):

[apf-2.7-alpha.zip](https://github.com/richardfrost/AdvancedProfanityFilter/files/4626229/apf-2.7-alpha.zip)

Thanks again!

**Comment by oo7goofy** [comment]
I was able to get it loaded. The directions were fairly straight forward. It automatically fixed the subtitles which was new. However, the audio still wasn't muted. I put more info in Discord.

**Comment by richardfrost** [comment]
I think we got this working, but I'll leave it open until I hear back for sure with the official release.
