### ISSUE TITLE
Regex not working

### ISSUE THREAD

**Issue by ClaytonFabiano** [richardfrost/AdvancedProfanityFilter#218]
If i try to create a Regex expression, the Regex do not work in this last version of APF.

For example, i created an expression for censor "cat" or "cut", "c(a|u)t", and, if i try to test, or detect the word in page, APF returns nothing.

But no one of Regex expressions i created in older versions of APF is working now. All my Regex expressions are in Regex match method.

I'm using Chrome 83.0.4103.61 64 bits in Windows 7.

**Comment by richardfrost** [comment]
Thanks for reporting the bug! I think it will be a quick fix, but I'll update here when I get it fixed.

**Comment by dc1800** [comment]
Having the same issue. I tried out the regex "w+t+" on the string "wwwttt" and nothing happened. However, the string "w+t+" was caught by the "regex" and substituted instead, for what that's worth.
 
I'm using Firefox 76.0 64 bits on Ubuntu 20.04. Thanks for this amazing add-on!

**Comment by richardfrost** [comment]
Thanks again for reporting this! And thanks for the kind words as well, I'm glad you like the project!

This should be fixed now. Once you update to version `2.7.4`, let me know how it goes for you.

**Comment by ClaytonFabiano** [comment]
My Regex expressions is working now, thanks for the update!

**Comment by richardfrost** [comment]
@ClaytonFabiano thanks for letting me know. Take care!

**Comment by dc1800** [comment]
Update just came through, works perfectly! Thanks a ton! :+1:

**Comment by richardfrost** [comment]
Thanks for the feedback!
(That is funny.. I do that all the time. I usually do my development, especially the audio stuff, with words like `the`, `man`, `he`, etc. Pretty silly when I forget to remove them. I still haven't bothered removing `c(a|u)t` from my wordlist yet.... Its amazing how many matches there are for that. I should remove it now.)
