### ISSUE TITLE
Gmail craziness

### ISSUE THREAD

**Issue by Smottz** [richardfrost/AdvancedProfanityFilter#22]
For some reason, this extension interferes with composing emails in Gmail. If you use Ctrl+B or Ctrl+I to format the text, it will switch to bold/italics, and then move the cursor backwards one space so you're typing immediately before the first bolded letter. I've tested this extensively now. I disable the extension, refresh the page, and I can compose fine. I then enable the extension, refresh the page, and the bizarre behavior strikes again. The same occurs on both my home and work machines.

![vivaldi_2017-06-09_11-48-39](https://user-images.githubusercontent.com/29311696/26987666-ac9cf61c-4d09-11e7-937f-bd516f18eb5a.png)

**Comment by richardfrost** [comment]
Sorry for the delay, I will have to look into this, but that is definitely a weird behavior!

**Comment by richardfrost** [comment]
Alright @smottz, I believe I have a fix for this. I was able to reproduce the described behavior and am no longer seeing it on the latest beta. If you would like to help me I can add you as a beta tester, or I should be publishing the update in a couple days.

**Comment by Smottz** [comment]
I'd be happy to test it for the privilege of being able to use this again! Thank you, Richard.

**Comment by richardfrost** [comment]
@Smottz Awesome! To see how to sign up as a beta tester please see the [wiki](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Beta-Testing#obtaining-access).

**Comment by richardfrost** [comment]
@Smottz I have gone ahead and published the new release as no other beta testers reported issues. If you get some time to try the extension again please let me know if the gmail issue is resolved for you. Thanks!

**Comment by richardfrost** [comment]
@Smottz Have you had a chance to see if the bug is still present on the latest version?
