### ISSUE TITLE
HBO Max

### ISSUE THREAD

**Issue by richardfrost** [richardfrost/AdvancedProfanityFilter#222]
#### :movie_camera: The Site
`play.hbomax.com`

#### :speech_balloon: Subtitle Element/Node
_Example:_
```html
<span style="font-family: font0; font-size: 45px; font-style: normal; text-decoration: none; text-transform: none; letter-spacing: 0px; color: rgb(255, 255, 255);">"Massah William!</span>
```

#### :pencil: Additional notes
Requested through the Chrome Web Store support page.

**Comment by richardfrost** [comment]
This is a tough one to get all the current features working on it. I prefer using mutation-based rules because they are more timely than a watcher-based rule, which is simply based on time. With some new changes, I was able to get muting to work, but caption hiding is problematic. I don't think there is a way to make it work relying solely on mutations, and as such will probably have to move to a "watcher" mode for that.

The issue is that on multi-line captions, each is in its own mutation, so there isn't a good way to know if there is another line coming.

**Comment by richardfrost** [comment]
If anyone has a subscription to HBO Max and would be willing to help test this, I would appreciate it!

[How to load an unpacked/development extension](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Load-Unpacked-Extension)

### Pre-release Builds:
- [extension.zip](https://github.com/richardfrost/AdvancedProfanityFilter/files/4741449/extension.zip)
- [extension-firefox.zip](https://github.com/richardfrost/AdvancedProfanityFilter/files/4741450/extension-firefox.zip)

**Comment by richardfrost** [comment]
This is now included in version [2.7.5](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.7.5), but with the same caveat as above (Can't selectively hide or show captions/subtitles).

**Comment by richardfrost** [comment]
One note here.. I've had a few times now where the muting won't work until I refresh the page. I'm not sure why that's happening, but it might be worth it to add a word like `the` temporarily to the filter to test it on a video, just to be sure its working for your viewing session.

**Comment by richardfrost** [comment]
For now, it looks like you have to click on "RESET" in the CC/subtitles menu for muting to work.

Alternatively, add this to your custom audio config:
```json
{
  "play.hbomax.com": [
    {
      "mode": "elementChild",
      "parentSelectorAll": "div.class28 > span",
      "showSubtitles": 0,
      "tagName": "SPAN"
    }
  ]
}
```

**Comment by richardfrost** [comment]
I'm curious if anyone could give this new config a try:

```json
{
  "play.hbomax.com": [
    {
      "mode": "elementChild",
      "parentSelectorAll": "div.class3 > span, div.class28 > span",
      "showSubtitles": 0,
      "tagName": "SPAN"
    }
  ]
}
```

I don't currently have an account, but I'll try to it when I'm able.

**Comment by erichca** [comment]
I can't get the audio muting to work on hbo max.  The captions do replacement successfully but no audio mute.

**Comment by richardfrost** [comment]
Hey @erichca, sorry for such a slow response. I thought I replied, but obviously I didn't. Anyway! I appologize that filtering on HBO Max still has some quirkiness. Can you share a screenshot of your caption/subtitle settings on HBO Max?

![image](https://user-images.githubusercontent.com/1507205/105207983-6c028280-5b05-11eb-8fff-5126752e5610.png)

If you would rather, maybe just try pressing the Reset button, and then refresh the page and see if it works. Right now the filter is only working with the defaults/reset config. If you have a specific setup that you'd like to use, let me know and I can probably setup a custom config for you to use.

**Comment by richardfrost** [comment]
Version [2.19.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.19.0) changed the method that HBO Max is using. This new mode was designed to handle different subtitle options (where before it needed to be the default, or every once in a while the subtitle settings for HBO Max had to be reset). I had a few people test it with success, but if you try it out, please let me know how it works for you. Thanks!
