### ISSUE TITLE
Overflow issues

### ISSUE THREAD

**Issue by Imveryweird** [richardfrost/AdvancedProfanityFilter#225]
Sometimes, the profanity filter freezes my browser by going up into the 9,000's and I have to open task manager to even get it to stop.

**Comment by richardfrost** [comment]
That sounds like there is some kind of an endless loop. likely a website repeated puts an element on the page with a word to filter, which then gets filtered, and then gets replaced by the website again. It is definitely something that can happen, but if you have any more details it would be helpful to try and pinpoint what is happening.

Do you have a specific site that it happens on? If its reproducible, could you try turning off the counter option and see if it still applies? I'll go ahead and put a cap on the counter (probably 999+).

**Comment by Imveryweird** [comment]
Usually it happens in Gutenberg.org when opening a book. 
![2020-06-24 12 38 34](https://user-images.githubusercontent.com/66542108/85605056-7b752800-b617-11ea-9172-0653e42603d2.jpg)

**Comment by richardfrost** [comment]
Is there a specific book that I should test (a link to it would be great)? Is the word (or words if more than one) that is getting filtered in the included/default word list, or one that you added? If it is a word you added, could you share it here so I can test it? If you'd rather, feel free to just export your config and attach it here to this issue.

**Comment by Imveryweird** [comment]
Usually it only happens while the page is loading. In Firefox the science fiction section in bookshelves is the worst one. How do I upload my config?

**Comment by richardfrost** [comment]
To share your config, just open the Filter's options page, go to the "Config" tab, and choose "Export". That should give you a `.json` file with your config that you can upload here.

In the meantime I'll go ahead and get started looking through that page.

**Comment by Imveryweird** [comment]
It was the asterik. It kept repeating through the page.

**Comment by richardfrost** [comment]
Interesting.. if you would still be willing, I'd like to check your config to try and add some protection to avoid a similar issue in the future.

If you would rather not share your config, could you tell me what the match method of the words are set to?

**Comment by Imveryweird** [comment]
I'll see if I can upload the file on my PC. It won't do it on my phone.

**Comment by richardfrost** [comment]
Thanks, I'd appreciate it. I still haven't been able to directly reproduce it because I'm not sure of how the words to filter are configured. I have seen similar behavior in the past with substituting a word with another word to filter (which results in an infinite loop), and there are some checks built in to try and prevent that, but its likely they may need to be enhanced based on your findings.

If you have trouble uploading a file, you can also check the "Inline editor" box on the Config tab, and then copy/paste the config into here as just text. Or, if you'd rather, you could go to the options page, then the "Words" tab, select one of those words (like pipe*) and send me a screenshot of the selected options that appear on the page.

**Comment by richardfrost** [comment]
@Imveryweird Just wondering if you think you'll have a chance to share either your config or those details on how one of the words was configured so I can try to build in more precautions into the filter. Thanks again for reporting the issue.

**Comment by Imveryweird** [comment]
Github would only allow me to do upload the zip file.
[apf-backup-2020-06-24_124510.zip](https://github.com/richardfrost/AdvancedProfanityFilter/files/4866021/apf-backup-2020-06-24_124510.zip)

**Comment by richardfrost** [comment]
Sorry about that, not sure why it would do that. But thank you for sending that over! I will try to add some more protections to prevent that from happening.

**Comment by richardfrost** [comment]
This has been added in version [2.8.1](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.8.1).
