### ISSUE TITLE
Peacock

### ISSUE THREAD

**Issue by NewToAPF** [richardfrost/AdvancedProfanityFilter#230]
_Instructions: This template is written in Markdown. Click the "Preview" tab to see what it will look like when submitted. Fill in the applicable sections (you can erase the examples if you'd like)._
I just signed up for 
#### :loudspeaker: The Shortcoming

Peacock TV has launched and there is no filter for it.

Your default set-up actually caught the profanity in the subtitles and made the word substitutions, but did not mute the audio.

#### :microscope: Describe the solution you'd like

Please add a filter for peacocktv.com to the Supported Sites list that will catch words in the subtitles AND mute the audio.

#### :triangular_ruler: Describe alternatives you've considered

I tried adding a filter under custom sites using the DisneyPlus example in your response to "nunyabeeswax7" in Disney Plus #170, as follows:

{
  "www.peacocktv.com" [and also without the 'www.']: {
    "mode": "cue",
    "videoSelector": "video.btm-media-client-element"
  }
}

but it did not mute the audio.

#### :pencil: Additional context

Thank you!

**Comment by richardfrost** [comment]
Thanks for the suggestion!

I spent a few minutes looking at a few videos tonight, and this seemed to work alright:

```json
{
  "www.peacocktv.com": {
    "mode": "elementChild",
    "parentSelector": "div.video-player__subtitles > div",
    "tagName": "div"
  }
}
```

If you could give that a try and let me know how that goes @NewToAPF, that would be great!

**Comment by NewToAPF** [comment]
Hi, Richard.

It WORKED! Thank you so much for looking into this so quickly!

@NewToAPF

**Comment by richardfrost** [comment]
You're welcome! Thanks for the suggestion, and for testing it and letting me know how it went. I'll add that config into the next version of the filter. I would recommend removing the custom config once it is built into the filter, but leave it in there for now so you can use it. I'll update this issue again when it has been released.

**Comment by NewToAPF** [comment]
Good evening, Richard.

I want to pass along an anomaly with the subtitles when watching Peacock TV that didn't "click" when I first checked it.
Lines with substituted words are appearing in a slightly larger font than the normal subtitle lines.

Sorry I didn't notice that the first thing.

Thanks.
Carlton


________________________________

**Comment by richardfrost** [comment]
Hello again Carlton! Thanks for reporting the issue. I'll take another look at it, but I've got a lot on my plate this coming week and might not get to it until the following week. Hopefully it is still workable for you until then.

**Comment by richardfrost** [comment]
This has been added in version [2.8.2](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.8.2).
