### ISSUE TITLE
Not working expected on FamilySearch

### ISSUE THREAD

**Issue by richardfrost** [richardfrost/AdvancedProfanityFilter#232]
#### :bug: Description
There are areas on the [FamilySearch](https://www.familysearch.org/) site that the filter doesn't work.

#### :pencil: Additional context
This was reported by a user.

**Comment by richardfrost** [comment]
They are using a very interesting combination of technologies, and the filter is not handling it well. The site appears to be using Angular, Polymer, and possibly some web components. Its also heavily using Shadow DOMs. I've spent some time trying to track down where the filter is breaking down, but still don't have a clear answer yet. I have made some progress, but there are still lots of mutations that are being missed, and nested Shadow DOMs as well, so the filter doesn't even know they exist. I'll continue to investigate this, but it is definitely a deep problem, and the solution will likely require a lot of testing because it will be a fundamental change.

**Comment by d-kj** [comment]
Off-topic, but somebody's family tree must be more spicy than mine. Hard to imagine needing this filter there.

**Comment by richardfrost** [comment]
lol, I know it does sound funny @d-kj. I had similar thoughts when I first heard about the issue, but turns out that the user was wanting to use the filter to hide some family names/sensitive details while training people on the site.  Although this extension is built to filter profanity, there are actually several people that use it for other things, for instance hiding political figure names (or replacing them).

**Comment by richardfrost** [comment]
Support for this has been added in [2.9.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.9.0). See [deep mode](https://github.com/richardfrost/AdvancedProfanityFilter/wiki#deep-mode) for more information.
