### ISSUE TITLE
Criterion Channel

### ISSUE THREAD

**Issue by CrazyDuck49** [richardfrost/AdvancedProfanityFilter#236]
I'm wondering if there is anyway to get the audio filter on the Criterion Channel

**Comment by richardfrost** [comment]
Thanks for the suggestion! I'll take a look at it as soon as I get some time to investigate it and I'll report back here.

**Comment by richardfrost** [comment]
Alright, so after some investigation, it seems like several of the videos have the captions/subtitles burned in, which the filter can't support. If the video does have captions that can be turned on and off, this custom config seemed to work though:

```json
{
  "www.criterionchannel.com": {
    "mode": "cue",
    "videoCueRequireShowing": false,
    "videoCueHideCues": true
  }
}
```

This is added in the Options page > Audio tab in the Custom Audio Sites area.

If you get a chance to test it, please let me know your experience with it.

**Comment by richardfrost** [comment]
After testing briefly with the following videos:
- The Magnificent Ambersons (1942)
- Puberty Blues (1981)
- The Sweet Hereafter (1997)

I think its working now. There were a few changes that enhanced the hiding of the captions, and this site will be included on the next release.

**Comment by richardfrost** [comment]
This has been added in version [2.8.2](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.8.2).
