### ISSUE TITLE
Youtube video not filtering audio or closed caption

### ISSUE THREAD

**Issue by sullijwiii8** [richardfrost/AdvancedProfanityFilter#238]
Youtube video not filtering audio or closed caption

**Comment by richardfrost** [comment]
Hello! I'm sorry to hear it's not working for you. I have a few questions to get started:

- Is there an example video that you could share that it's not working on?
- What browser are you using the filter on?
- Is the audio feature enabled (Options page > Audio tab)?
- Have you tried it on any other sites with success?

Hopefully we can get it working for you soon!

**Comment by sullijwiii8** [comment]
Using Chrome, I tried it on multiple YouTube videos and got the same result, the audio feature was enabled. I have yet to try it on other sites as YouTube is the only thing that casts to my TV.

 

 

John Sullivan III

Office (757) 893-6356

**Comment by richardfrost** [comment]
Oh, is it not working while casting? Does it work if you are just watching on the computer directly? Unfortunately the way video casting works, it really just shares a link to the video, and then the device (TV) just plays the video at that link, leaving no way for the filter to run.

There is another issue [here](#206) discussing this, but maybe you could try [following these directions](https://github.com/richardfrost/AdvancedProfanityFilter/issues/206#issuecomment-635088851). Right now that is the only way to get the filter working while casting.

**Comment by sullijwiii8** [comment]
It's not working on my laptop.

**Comment by richardfrost** [comment]
Okay, do you think you could attach a copy of your config here? If you export your config (Filter's Option page > Config tab > Export button) you should be able to drag-and-drop it into a comment here on this issue.

**Comment by richardfrost** [comment]
Its been a while since your last response, so I'm going to close this. If you are still having trouble with this and would like to continue troubleshooting it, feel free to re-open this issue.
