### ISSUE TITLE
Support for Audio Muting on Embedded YouTube Videos

### ISSUE THREAD

**Issue by CreeperPookie** [richardfrost/AdvancedProfanityFilter#242]
On the actual YouTube site, the audio works _**VERY**_ well, especially with auto-generated subtitles. However, on sites where the video is embedded into the site, it does not mute the audio; while yes it filters the text, it does not mute the audio. On sites other than youtube.com, embedded audio muting would be _**SO**_ useful.

**Comment by richardfrost** [comment]
I'm glad that the YouTube muting is working well for you! As for muting on other sites, are you trying a supported site (The list can be found in the Options page > Audio tab > "View Supported Sites" button)? If so, can you let me know which on (or ones) aren't working?

If you are looking at a site that isn't on the list, I'm happy to take a look at it and try to add support for it. Basically we just have to tell the filter how to identify whether a section of text is part of the captions/subtitles or not so the filter can know when to mute the audio.

**Comment by richardfrost** [comment]
I'm sorry I think I completely misread your opening post. I have a dev build working with embedded YouTube videos as long as they are embedded in an `IFRAME`. So far that's worked on every video I have tried. I have a bit more work I want to get done on this branch, but let me know if you have any examples of sites with embedded YouTube videos @CreeperPookie.

Thanks!

**Comment by richardfrost** [comment]
Support for embedded (iframe) videos was added in version [2.23.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.23.0). As always, feedback and suggestions are welcome. Feel free to respond here in the issue, or open a new one. Thanks again for this suggestion.
