### ISSUE TITLE
Crunchyroll! Please :)

### ISSUE THREAD

**Issue by jesusisslord** [richardfrost/AdvancedProfanityFilter#245]
#### :loudspeaker: Crunchyroll
I really enjoy watching Japanese anime with my family on Crunchyroll, but it's really hard to find family friendly ones.
Please make it so we can censor the curse words!

**Comment by richardfrost** [comment]
Thanks for the suggestion. This has actually been requested before (#205), and unfortunately it will take a bit of work that I haven't had a chance to do yet. But I'll try to add priority to it when I have some more time.

**Comment by richardfrost** [comment]
@jesusisslord I'm consolidating this issue into #205. Please see that issue (or subscribe to it) for future updates, and for information how you can try the new experimental support. Thanks again for your suggestion!
