### ISSUE TITLE
Filter words are not filtered but the counter is counting them.  Netflix

### ISSUE THREAD

**Issue by davi875** [richardfrost/AdvancedProfanityFilter#248]

**Comment by richardfrost** [comment]
Thanks for reporting the issue. Could you share an example video/link on Netflix that this is happening on? Which browser are you using? Finally, it might be helpful if you could upload a copy of your config here so I can test with your same settings.

**Comment by davi875** [comment]
Google Chrome is the Browser.  I'm not sure where to get and copy the
config

**Comment by richardfrost** [comment]
To export your config: Open the filter's options page > Config tab and press the Export button.

For more information: https://github.com/richardfrost/AdvancedProfanityFilter/wiki#config

**Comment by richardfrost** [comment]
Its been a while since your last response, so I'm going to close this. If you are still having trouble with this and would like to continue troubleshooting it, feel free to re-open this issue.
