### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by Nuklon** [richardfrost/AdvancedProfanityFilter#25]
I'm using it in Firefox and it works fine (webext), can you upload it to AMO as well?

**Comment by richardfrost** [comment]
I haven't used Firefox for a long time, but I will see what it takes to get it published on AMO. Thats awesome that it is working for you there!

**Comment by richardfrost** [comment]
I have submitted the Add-on and it is currently awaiting a review.

**Comment by richardfrost** [comment]
Thanks for the great idea Nuklon! It has now been accepted to AMO: https://addons.mozilla.org/firefox/addon/advanced_profanity_filter

**Comment by Nuklon** [comment]
Awesome, thank you very much, now I can use the official version 😀

**Comment by richardfrost** [comment]
Sorry to bug you @Nuklon, but if it is working for you I would love a review on AMO! It looks like it even works on Firefox mobile for me too, which is cool!

**Comment by Nuklon** [comment]
Yes, will do when I'm at my desktop again 👍
________________________________
