### ISSUE TITLE
Firefox portable

### ISSUE THREAD

**Issue by FurmanSK** [richardfrost/AdvancedProfanityFilter#26]
## Description

Running latest beta firefox 57 and I have to run portable at work but when I load addon it says it can't save any settings. Is there a way to fix this? Where are the settings saved so I could try and manually save?

**Comment by richardfrost** [comment]
Sorry its not working for you. Do you have an exact error message? The Add-on uses the  `chrome.storage` api as it is primarily a Chrome Extension. A couple questions that might be helpful in diagnosing the problem: 
- When does the error arise?
- Are you are using Firefox Sync?
- Does the extension instal?
