### ISSUE TITLE
BritBox Audio Muting

### ISSUE THREAD

**Issue by netwinter** [richardfrost/AdvancedProfanityFilter#261]
_Instructions: This template is written in Markdown. Click the "Preview" tab to see what it will look like when submitted. Fill in the applicable sections (you can erase the examples if you'd like). For more information, please see [this page](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/New-Audio-Muting-Site)._

#### :movie_camera: The Site
_www.britbox.com_

#### :speech_balloon: Subtitle Element/Node
```html
<div id="bmpui-id-17" class="bmpui-ui-subtitle-overlay bmpui-controlbar-visible"><div class="bmpui-container-wrapper"><div id="bmpui-id-351" class="bmpui-subtitle-region-container bmpui-subtitle-position-bottom" style="top:10%;left:14.375%;width:71.25%;height:80%;padding:0%;"><div class="bmpui-container-wrapper"><span id="bmpui-id-350" class="bmpui-ui-subtitle-label"><p xml:id="sub222" xml:space="preserve" begin="00:09:12.96" end="00:09:15.60" region="bottom"><span style="color: rgb(255, 255, 255); background-color: rgb(0, 0, 0); --darkreader-inline-color:#f0ebe2; --darkreader-inline-bgcolor:#000000;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">[sirens blaring]</span></p></span></div></div></div></div>
```

#### :pencil: Additional notes
Successfully tested the same site setting used for www.dishanywhere.com by just replacing the domain name and pasting the modified json into the custom sites.
```{
  "www.britbox.com": [
    {
      "mode": "element",
      "className": "bmpui-ui-subtitle-label",
      "tagName": "SPAN"
    },
    {
      "mode": "element",
      "tagName": "div",
      "className": "bmpui-subtitle-region-container",
      "subtitleSelector": "div.bmpui-container-wrapper > span.bmpui-ui-subtitle-label"
    }
  ]
}
```

**Comment by richardfrost** [comment]
Awesome! Thank you so much for contributing this! I'll go ahead and get it added into the next version.

**Comment by richardfrost** [comment]
This was added in version [2.12.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.12.0). Feel free to respond and reopen this issue if you still have trouble related to this problem.
