### ISSUE TITLE
AcornTV Audio Muting

### ISSUE THREAD

**Issue by netwinter** [richardfrost/AdvancedProfanityFilter#262]
_Instructions: This template is written in Markdown. Click the "Preview" tab to see what it will look like when submitted. Fill in the applicable sections (you can erase the examples if you'd like). For more information, please see [this page](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/New-Audio-Muting-Site)._

#### :movie_camera: The Site
_acorn.tv_

#### :speech_balloon: Subtitle Element/Node
_Example:_
```html
<div class="vjs-text-track-display" aria-live="off" aria-atomic="true"><div style="position: absolute; left: 0px; right: 0px; top: 0px; bottom: 0px; margin: 1.5%;"><div class="vjs-text-track-cue vjs-text-track-cue-en-US" style="text-align: center; font: 23.59px sans-serif; white-space: pre-line; position: absolute; direction: ltr; writing-mode: horizontal-tb; left: 46.7969px; width: 842.453px; top: 438.844px; bottom: 7.03125px; right: 46.8125px; height: 26px; background-color: rgba(0, 0, 0, 0); --darkreader-inline-bgcolor:rgba(0, 0, 0, 0);" data-darkreader-inline-bgcolor=""><div style="color: rgb(255, 255, 255); background-color: rgb(0, 0, 0); position: relative; left: 0px; right: 0px; top: 0px; bottom: 0px; display: inline; writing-mode: horizontal-tb; unicode-bidi: plaintext; font-family: sans-serif; --darkreader-inline-color:#f0ebe2; --darkreader-inline-bgcolor:#000000;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">we need to talk about Marley.</div></div></div></div>
```

#### :pencil: Additional notes
Successfully used the same site muting data as www.funmation.com just replacing the domain name.
```{
"acorn.tv": [
    {
      "iframe": true,
      "mode": "elementChild",
      "parentSelector": "div.vjs-text-track-display",
      "simpleUnmute": true,
      "subtitleSelector": ":scope div > div",
      "tagName": "DIV"
    }
  ]
}
```

**Comment by richardfrost** [comment]
Wow! Another one! Thanks for sharing this as well. I'll go ahead and get it added as well.

**Comment by richardfrost** [comment]
This was added in version [2.12.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.12.0). Feel free to respond and reopen this issue if you still have trouble related to this problem.

**Comment by richardfrost** [comment]
Not sure if you're still around here @netwinter, but I just got a report that this has stopped working. Do you happen to still have access to AcronTV?

**Comment by netwinter** [comment]
Unfortunately not @richardfrost. I now access it via Amazon channels.

**Comment by richardfrost** [comment]
That's alright, thanks anyway @netwinter!
