### ISSUE TITLE
Filter Bypass using HTML img alt attribute

### ISSUE THREAD

**Issue by CreeperPookie** [richardfrost/AdvancedProfanityFilter#264]
#### :bug: Description
If you create an HTML with an `<img>` element with the `src` tag set to something invalid and set the `alt` attribute to a word on the filter, it will actually bypass the filter. While it seems to bypass it when it's already in the HTML if you dynamically change the `alt` attribute using JS, it seems to filter it sometimes, but not always.

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Make an HTML page
2. In `<body>`, create an `<img>` element
3. Set `src` attribute of the `<img>` to something invalid (i.e. "x"), and the `alt` attribute to a word that is currently on the filter
4. Load HTML page and notice how alt text isn't filtered

#### :heavy_check_mark: Expected behavior
Like normal text, APF should also filter text in `<img alt="text">`, as this is a pretty major way to bypass the filter.

#### :computer: Details
 - **Device:** Dell Inspiron 17-7779
 - **OS:** Windows 10
 - **Browser:** Microsoft Edge Chromium (should work in chrome too though)
 - **Browser Version:** 86
 - **Affected site(s):** Any website that can use the `<img>` HTML tag

**Comment by richardfrost** [comment]
Thanks for reporting the issue. Is there a site that this behavior is happening on, or did you just find this through executing javascript? This is happening because right now the filter is only watching for text changes. It can be fixed if it also watches attribute changes, but I'll need to see if I can find a performant way to handle that.

**Comment by richardfrost** [comment]
Adding `attributes` to the MutationObserver is a big change that will lead to a lot of extra processing. I just tested it on a couple sites and it lead to 5-10x the mutations observed. If there is a specific page that has this behavior I'd be willing to investigate it, and maybe it would make sense to add this change to one of the other modes (Advanced or Deep), but I don't want to add it to the normal mode.

I'm going to close this, but if you have any examples where the filter is failing, or have any other thoughts or questions feel free to reply here.
