### ISSUE TITLE
Asterisks Between Words

### ISSUE THREAD

**Issue by ssrr88** [richardfrost/AdvancedProfanityFilter#27]
I never had this problem before, but when I accidentally pushed the button to restore to default, there's an asterisk between each word. Is there a way to fix this?

**Comment by ssrr88** [comment]
Nevermind. I fixed the problem by uninstalling it, then reinstalling it.

**Comment by richardfrost** [comment]
Interesting, I'm not sure how that happened, but I'm glad that you were able to get it fixed. I just tried resetting the defaults and it seemed to work correctly for me. If it  happens again I would love a screenshot of your settings and the results you were seeing, but hopefully it doesn't happen again. Thanks for creating the issue!
