### ISSUE TITLE
Audio muting not working on Hulu

### ISSUE THREAD

**Issue by nunyabeeswax7** [richardfrost/AdvancedProfanityFilter#271]
I was watching this show called Atlas of Cursed Places, specifically the episode called The Curse of the Bayou. The line where the host says "for the h*** of it," the muting didn't work. What gives?

**Comment by richardfrost** [comment]
I'm sorry about that. It looks like Hulu has made an update to how they present the subtitles/captions, which broke the detection for the filter. Could you try adding this to your custom audio sites config?

Filter Options Page > Audio Tab > Custom Sites (Advanced) box on the right (remember to click "Save" after adding):

```json
{
  "www.hulu.com": [
    {
      "parentSelector": "div.CaptionBox",
      "displaySelector": "div.CaptionBox",
      "mode": "elementChild",
      "tagName": "P"
    }
  ]
}
```

I have tested it on a handful of videos with success. I'm planning on including it in a new release today, but if you have some time to test it and report back that would be great.

**Comment by nunyabeeswax7** [comment]
Yep, it worked. Thank you.

**Comment by richardfrost** [comment]
Perfect! Thanks for testing that. I'll get that update submitted today. I'd recommend you remove that custom config when you do get the update (`2.12.0`) to help you with getting future updates for Hulu automatically.

**Comment by richardfrost** [comment]
This bug was fixed in version [2.12.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.12.0). Feel free to respond and reopen this issue if you still have trouble related to this problem.

**Comment by nunyabeeswax7** [comment]
Nope, it's still not working.

**Comment by richardfrost** [comment]
It's not working on the latest version? Does it work if you put the config from earlier in the custom config? I'll try to test a bit later.

**Comment by nunyabeeswax7** [comment]
No it doesn't.

**Comment by richardfrost** [comment]
Can you give an example of a video (and timestamp) when it isn't filtering? I just tested on a few things and it worked as expected.

**Comment by nunyabeeswax7** [comment]
Okay, the video is "Most Terrifying with Jason Hawes", S1E3, "Prison of the Dead", timestamp is -20:56.

**Comment by nunyabeeswax7** [comment]
Here's another odd thing. When I move my mouse around the screen, the word counter goes up.

**Comment by richardfrost** [comment]
Unfortunately it looks like I can't access that video to test. Could you try adding this custom config?

```json
{
  "www.hulu.com": [
    {
      "className": "caption-text-box",
      "displaySelector": "div.caption-text-box",
      "mode": "element",
      "subtitleSelector": "p",
      "tagName": "DIV"
    },
    {
      "displaySelector": "div.CaptionBox",
      "mode": "elementChild",
      "parentSelector": "div.CaptionBox",
      "tagName": "P"
    }
  ]
}
```

**Comment by nunyabeeswax7** [comment]
No dice.

**Comment by nunyabeeswax7** [comment]
BTW is it Tuesday where you are? The video expires on Tuesday.

**Comment by nunyabeeswax7** [comment]
Here's another video I hope you do have access to so you can test it: It's the same show, but it's episode 4 "Blackbeard's Vengeance", the timestamp is 9:06.

**Comment by richardfrost** [comment]
I don't know how comfortable you are with browser developer tools, but if you want to give it a go:

1. Navigate to a video that isn't work (like the one you listed above)
2. When caption/subtitle text is visible, pause the video
3. Right-click on the caption/subtitle text and select "Inspect"
4. If you don't see the caption text in the revealed element, press `CTRL+F` to search, and type in a phrase shown in the caption/subtitle text
5. Once you have found the element(s) that contain the caption/subtitle text, go up a couple levels (parents), right-click on it and then select `Copy` > `Copy element`.
6. Paste that copy here in a response, and I'll see if I can craft a new config.

Alternatively, a more technical method has been documented [here](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Custom-Audio-Muting-Site#2-elementtext-mode) that could give a little better information.

Let me know if you have any questions. Thanks!

**Comment by richardfrost** [comment]
Good thought on the time difference. I'm in MST, so its still Monday here. I think its actually the level of my subscription that is the problem, unfortunately. Same issue with that second video as well. Is it in the "TV" area? As opposed to the normal streaming?

**Comment by nunyabeeswax7** [comment]
No. I think I have an inkling of what the problem really is. I remember a similar problem with a recording of the movie Beetlejuice. These episodes seem to be more like recorded ones rather than normal streaming ones. I think it's because the audio filter doesn't work with recorded material.

**Comment by richardfrost** [comment]
Oh, yeah. That could be. If the captions aren't actual text, then unfortunately there isn't anything for the filter to go on.

**Comment by nunyabeeswax7** [comment]
I just did a test on a non-recorded episode on another show, and the filter worked fine. I guess my hunch was right. Thanks for trying to help me anyway.

**Comment by richardfrost** [comment]
Of course! So in the case of the recorded videos, are the captions "burned in"? Meaning they aren't actually text on the page? Another giveaway can sometimes be if they can be turned on/off.

**Comment by nunyabeeswax7** [comment]
These ones were not "burned in" they could be turned on and off.

**Comment by richardfrost** [comment]
In that case, do you want to try following those steps I [outlined](https://github.com/richardfrost/AdvancedProfanityFilter/issues/271#issuecomment-751953880)? As long as it is text, it should be possible to add support for it.

**Comment by nunyabeeswax7** [comment]
I'm afraid I just don't get that technical stuff at all. I can wait for a properly streamed episode. Once again, thank you.

**Comment by richardfrost** [comment]
Sounds good. Thanks, and have a good night!

**Comment by richardfrost** [comment]
Turns out there are users that are still getting the older style for captions/subtitles.
