### ISSUE TITLE
Dark mode support for UI and Settings

### ISSUE THREAD

**Issue by CreeperPookie** [richardfrost/AdvancedProfanityFilter#274]
Your extension works great for audio muting and filtering text. However, one thing is that the settings in light mode; so if I need to go into the settings, it's VERY bright. Is there any chance for dark mode support to be added in the future?

**Comment by richardfrost** [comment]
Thanks for the feedback. I agree, it is very bright. I'll see what I can do when I get some time to put a dark theme together.

**Comment by richardfrost** [comment]
I've added a dark mode for the options page and popup window in version [2.15.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.15.0). To activate it, click the little Moon/Sun icon on the right-side of the menu bar on the Option's page. If you have any other feedback, please let me know and I'll try to address it. Thanks for the suggestion!
