### ISSUE TITLE
Add Discovery plus

### ISSUE THREAD

**Issue by nunyabeeswax7** [richardfrost/AdvancedProfanityFilter#276]
The new streaming site Discovery plus just launched today. Can you add it to the roster?

**Comment by nunyabeeswax7** [comment]
The new streaming site Discovery plus just launched today. Can you add it to the roster?

**Comment by richardfrost** [comment]
I'll try to take a look at it this weekend. Thanks for the suggestion!

**Comment by richardfrost** [comment]
If anyone gets some time to test this, I'd appreciate it:

```js
{
  "www.discoveryplus.com": [
    {
      "mode": "cue",
      "videoCueLanguage": "en"
    }
  ]
}
```

Like usual, this just goes in the Custom Audio Sites config (Option page > Audio tab > right side box). This should work for the muting, but I do have some additional code I need to finish up to handle hiding the captions/subtitles.

**Comment by stevenh1976** [comment]
I’m looking for discover plus for my kodi, new to the site. I didn’t know where else to look. I installed one, but it was in Spanish. 
thanks

**Comment by richardfrost** [comment]
Hi @stevenh1976, Sorry, but I'm not quite sure what your question is. If you are looking for a Kodi plugin, this project is a browser extension focused on removing profanity, and not really related to Kodi. If you are looking to get Kodi support for this extension, I would be happy to take a look at that. Let me know what you are looking for, thanks!

**Comment by stevenh1976** [comment]
Hi,
I found on google a add on for discovery plus for kodi, I can’t get it in Canada so I thought I would give it a try. I installed it to realize it was all Spanish.  I found this site on the page or linked to the page. I can’t remember for sure. 
I’m just trying to get discovery plus on my kodi to make my gf happy.  She loves the shows and wants to watch more.  
Thanks for your time

**Comment by richardfrost** [comment]
@stevenh1976 Ah, that makes more sense. Sorry that I probably won't be able to do much to help you on that front. I imagine you'd probably have to use a VPN if you wanted to watch it in an unsupported country. Best of luck!

**Comment by stevenh1976** [comment]
Ok thanks.
