### ISSUE TITLE
Uppercase is converted to lowercase when saving new filters (even regex filters)

### ISSUE THREAD

**Issue by skeets23** [richardfrost/AdvancedProfanityFilter#277]
#### :bug: Description
Using a regex filter, it's impossible to use special symbols like `\S` because they are converted to `\s` upon saving.

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Create a new rule
2. Set the rule to `example\S*` (or similar, as long as it has \S)
3. Press save
4. Open the rule for editing, you'll see it's changed to `example\s*`.

#### Current workaround
It's not ideal, but you can use `[^\s]` instead of `\S`. I don't think there's a workaround for every uppercase regex special character though, so it would be awesome if this was fixed.

**Comment by richardfrost** [comment]
Thanks for reporting this. I'll get it fixed for regex right away. I may add more options for case in the future for the other match methods, but for the regex it definitely makes sense to not change the case on save.

**Comment by richardfrost** [comment]
This should now be fixed in version [2.14.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.14.0).
