### ISSUE TITLE
Filler sound doesn't stop when the video is paused on YouTube

### ISSUE THREAD

**Issue by CreeperPookie** [richardfrost/AdvancedProfanityFilter#288]
#### :bug: Description
Hello! Your extension is great, and I recently upgraded it to v2.16.0, which added the filler sounds. This addition is great, but there is one problem: If the filter triggers and starts playing the sound and the video is paused, the sound continues. This happens for auto-generated captions as well as manual captions; I use the video muting exclusively for YouTube, so I am unsure if this impacts other sites.

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Play any video
2. Add a word from the captions into the filter
3. Ensure Audio Muting with filler is enabled correctly
4. Pause the video after the word has been said but before the next word appears
5. Sound keeps playing

#### :heavy_check_mark: Expected behavior
Personally, I think that instead of this, the sound should pause while the video is paused, and resume when unpaused until the next word appears.

#### :computer: Details
 - **Device:** Dell Inspiron 17-7779
 - **OS:** Windows 10 20H1
 - **Browser:**Microsoft Edge Chromium
 - **Browser Version:** 88.0.705.74
 - **Affected site(s):** www.youtube.com and possibly any other sites that support audio muting

**Comment by richardfrost** [comment]
Thanks for pointing this out. I definitely didn't plan out what the extension should do when the video was paused, so thanks for bringing this up. I think your suggested behavior makes sense, and I'll try to address it as soon as I can.

**Comment by richardfrost** [comment]
Released in version [2.22.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.22.0). Let me know if you get a chance to try it out how it works for you. Feel free to reply here in the issue, even if its closed. Thanks again for the bug report!
