### ISSUE TITLE
CWTV.COM Filtering subtitles but not audio

### ISSUE THREAD

**Issue by NewToAPF** [richardfrost/AdvancedProfanityFilter#291]
_Instructions: This template is written in Markdown. Click the "Preview" tab to see what it will look like when submitted. Fill in the applicable sections (you can erase the examples if you'd like)._

#### :bug: Description
I am using your filter to watch a show on cwtv.com. It is filtering the subtitles, but not the related audio. I have checked my settings, closed the window and reopened it (though not re-started the episode back at the beginning) and quit and restarted Chrome. However, it still is not muting the audio.
Thanks!

#### :twisted_rightwards_arrows: Steps To Reproduce
Here is the link:
https://www.cwtv.com/shows/superman-and-lois/pilot/?play=b0743114-4bda-47d6-8553-2bdd1b5c1b17

#### :heavy_check_mark: Expected behavior
Mute Audio along with blocking associated subtitle

#### :computer: Details
 - **Device:** MacBook Air 2017
 - **OS:** MacOS 10.14.6
 - **Browser:** Chrome
 - **Browser Version:** Version 89.0.4389.90 (Official Build) (x86_64)
 - **Affected site(s):** www.cwtv.com

#### :pencil: Additional context
Here is what my extension has for cwtv:
{
  "www.cwtv.com": [
    {
      "className": "ttr-container",
      "mode": "element",
      "subtitleSelector": "span.ttr-cue",
      "tagName": "DIV"
    }
  ]
}

**Comment by NewToAPF** [comment]
Well, sir, I discovered that CWTV has two English subtitle settings: "English" and "English [CC]. I was using the latter. When I switched it to just "English", your filter blocked the Audio.
So, looks okay when using that setting!

**Comment by richardfrost** [comment]
Thanks for the report! I'll take a look at the other one and see if I can add support for both types of captions.

**Comment by richardfrost** [comment]
If you use these rules in your Custom Audio config it should work for both variations. If you want to test it out and report your findings that would be helpful. Assuming it works for you, I'll make sure to include it in the next version.

```json
 {
   "www.cwtv.com": [
    {
      "className": "ttr-container",
      "mode": "element",
      "subtitleSelector": "span.ttr-cue",
      "tagName": "DIV"
    },
    {
      "className": "ttr-line",
      "mode": "element",
      "subtitleSelector": "span.ttr-cue",
      "tagName": "DIV"
    }
  ]
}
```

**Comment by NewToAPF** [comment]
Thank you for your quick response.
I tried it and it is working!
Thanks!

**Comment by richardfrost** [comment]
Thanks for reporting back! I'll get that added to the next release! Once the new version is out, feel free to remove that custom audio config if you'd like.
