### ISSUE TITLE
Add Support for Redbox.com Streaming

### ISSUE THREAD

**Issue by NewToAPF** [richardfrost/AdvancedProfanityFilter#292]
_Instructions: This template is written in Markdown. Click the "Preview" tab to see what it will look like when submitted. Fill in the applicable sections (you can erase the examples if you'd like)._

#### :loudspeaker: The Shortcoming
I don't see Redbox.com in your list of supported sites, but tried using it with Redbox Streaming to see if it would work. It did not block the words nor the audio..
Please consider adding it. Thanks!
#### :microscope: Describe the solution you'd like
Support for Redbox.com Streaming
#### :triangular_ruler: Describe alternatives you've considered
I tried using a "generic" profanity blocker to see if it would work with Redbox, but it did not.

**Comment by NewToAPF** [comment]
Correction. Your extension is blocking the subtitle, but not the audio.
Sorry for the confusion!

**Comment by richardfrost** [comment]
Thanks for recommending a new site! There are so many sites out there, and most I don't personally use, but I am always happy to try and add more support to the filter.

Can you try this custom audio setup:
```json
{
  "www.redbox.com": [
    {
      "mode": "elementChild",
      "parentSelector": "div.rb-text-container",
      "subtitleSelector": "SPAN",
      "tagName": "DIV"
    }
  ]
}
```

If you wanted to combine the others from #291, you can do it like this:
```json
{
  "www.cwtv.com": [
    {
      "className": "ttr-container",
      "mode": "element",
      "subtitleSelector": "span.ttr-cue",
      "tagName": "DIV"
    },
    {
      "className": "ttr-line",
      "mode": "element",
      "subtitleSelector": "span.ttr-cue",
      "tagName": "DIV"
    }
  ],
  "www.redbox.com": [
    {
      "mode": "elementChild",
      "parentSelector": "div.rb-text-container",
      "subtitleSelector": "SPAN",
      "tagName": "DIV"
    }
  ]
}
```
