### ISSUE TITLE
Statistics feature for tracking total filter count

### ISSUE THREAD

**Issue by CreeperPookie** [richardfrost/AdvancedProfanityFilter#295]
#### :microscope: Describe the solution you'd like
For this, I think it should probably be sorted, and be able to see statistics for different types of filtering (audio muting, text filtering) and an all-time count as well.

I don't consider this a priority by any means, but I do think it would be a nice thing to have in your extension.

**Comment by richardfrost** [comment]
Thanks for the cool suggestion! I'll keep it in mind and see what I can do.

**Comment by richardfrost** [comment]
A new "Stats" tab has been added to the Options page in version [2.21.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.21.0). As always, feedback and suggestions are welcome. Feel free to respond here in the issue, or open a new one. Thanks again for this suggestion.
