### ISSUE TITLE
How to regex till the end of word?

### ISSUE THREAD

**Issue by asakura42** [richardfrost/AdvancedProfanityFilter#301]
`\w+` doesn't work but `.*` works and blocks everything till the end of the line. what if i just want to block words with regex but not only the part if them?

**Comment by richardfrost** [comment]
If you can give a clearer example of what you are trying to do I'll try to give a more specific answer, but here are some examples:

Regex to filter words that start with "every": `\bevery\w+`
Test phrase (Can be entered at Options page > Test tab):  `This is everything I want.`
Expected result: `This is censored I want.`

So, if you have more specifics, please let me know and I'll take a look.

TIP: If you don't need regex, you can use the `whole` match method to match a whole word.

**Comment by asakura42** [comment]
Thank you.
