### ISSUE TITLE
Subtitles Won't Show Crunchyroll

### ISSUE THREAD

**Issue by ssSwan** [richardfrost/AdvancedProfanityFilter#302]
Bug
The subtitles always disappear on Crunchyroll, no matter how many times I change the subtitle options and refresh the page. Since the audio is in Japanese, I need to see the subtitles, but I would like to be rid of the curse words in both text and audio. The site offers some vids in English, but many are in Japanese only. Please, help.

**Comment by richardfrost** [comment]
It's likely that they may have changed something on their site which broke the filter. Could you share an example or two of videos that you have encountered this issue on?

**Comment by travislibby000000** [comment]
Hi Richard 


Sent from Yahoo Mail for iPhone


On Sunday, May 16, 2021, 11:07 AM, Richard Frost ***@***.***> wrote:




It's likely that they may have changed something on their site which broke the filter. Could you share an example or two of videos that you have encountered this issue on?

**Comment by ssSwan** [comment]
To whom it may concern,

Thank you for your prompt response. Here is a link to one of the videos on
crunchyroll.
https://www.crunchyroll.com/fruits-basket/episode-6-it-was-so-foolish-810786.
My family really enjoy these videos, so I hope the problem is an easy fix.
Thank you for your time and consideration.

Many blessings!

**Comment by richardfrost** [comment]
Thanks again for reporting the issue. I have released version [2.19.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.19.0) that should help to address this. Crunchyroll has an interesting routine on their site where they won't allow the TextTrack (subtitles) to be turned on for videos. That's typically how the filter has presented the captions to viewers. In this release, I set Crunchyroll to copy the captions from that TextTrack and put them on the page.

I had to add this feature specifically for this, so it may be rough around the edges. Please share feedback and I'll do what I can to address any issues you may face with it.

**Comment by ssSwan** [comment]
Dear Richard Frost,

Thank you for your work on that.  I tried the video on Crunchyroll to see
how the new version works. Crunchyroll has ads, and when they play, the
subtitles for the movie keep playing while the ad does, so that when the
movie comes back on, the subtitles are way ahead of the audio. In other
words, the subtitles play over the ads and leave the movie audio behind.
I tried turning the filter off and on and refreshing the page to see if
they would match up afterward, but the ads always replay when I refresh the
page, and the subtitles leave the audio behind again. So, there's the new
problem.

Thanks again, and best of luck!

**Comment by richardfrost** [comment]
How often do the ads show up? In my testing I never saw any ads.

**Comment by ssSwan** [comment]
Dear Richard Frost,

If you subscribe to crunchyroll, there are no ads; if not, then they start
showing up at times during the video or when you rewind, fast forward,
refresh the page, etc..

**Comment by richardfrost** [comment]
Do you have an ad blocker while you are playing it?


I do have a trial account, but I'm pretty sure I wasn't using it when I was testing. I am using [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en), and it seems to have blocked the ads for me. When I get some more time I'll try it with that disabled and see if I can get any ads to show.

**Comment by ssSwan** [comment]
Dear Richard Frost,

I do have an ad-blocker, but it doesn't stop the ads on crunchyroll and
YouTube. I think those ads are for funding purposes for the websites, so
I've never tried to get rid of them. Thanks!

**Comment by richardfrost** [comment]
That makes sense. After trying a new browser install with nothing installed but APF, I do see the ads play. Unfortunately the filter's focus is not to make adjustments for ads. On their site they have the main video marked as playing behind the ad, so the captions end up firing in the background. While it could be possible to capture the length of the ad and then increase all the caption/subtitle timings by that amount, at this point I don't really want to do that. 

To fix this issue, I would recommend either:
- Pay for a subscription to the service (**Recommended**)
- Use an ad blocker that can block the ads

With one of those methods in place, I believe the captions/subtitles should work as desired.

**Comment by ssSwan** [comment]
Dear Richard Frost,

Honestly, I'm not sure doing the thing about the ad-timing would even work.
Sometimes, they play six ads at a time. So, I think you're right; I can
just find another ad-blocker or subscribe to avoid the ads. Also, I found
the same series on another website where the filter worked. So, it's cool.
Thanks for your work on that. Wish you all the best.

Blessings,

Sarah

**Comment by richardfrost** [comment]
Glad you found a way to enjoy the show you wanted to. Thanks for reporting the issue and helping to make the filter better!
