### ISSUE TITLE
Apple TV Audio not muting

### ISSUE THREAD

**Issue by fun2bwade** [richardfrost/AdvancedProfanityFilter#307]
Hi! Thank you so much for creating such a wonderful extension. Unfortunately, I have run into issues muting audio on Apple TV+. I got the service specifically in order to watch the hit comedy Ted Lasso without the profanity. The subtitles do change but the audio has failed to mute. Do you have any troubleshooting suggestions?

**Comment by richardfrost** [comment]
@fun2bwade Did one of those suggestions work for you? Or have you had a chance to check them?

**Comment by angeloj92** [comment]
Hello I tested this on my own and it does not work with apple tv plus at all it does seem to work fine in apps like netflix where it censers the words and mutes apple tv plus just censers but no muting

**Comment by richardfrost** [comment]
@angeloj92 Could you share which video you are testing with? I have tested with Ted Lasso's pilot episode and it seemed to work fine for me. I will re-iterate that you have to use the `Browser tab`  mute method for it to work. I have also only tested with English captions/subtitles (I think there were 3 variations, and all 3 worked in that test).

**Comment by richardfrost** [comment]
Version [2.20.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.20.0) includes a fix for this issue.
