### ISSUE TITLE
Goes back to default

### ISSUE THREAD

**Issue by thaddeusrose** [richardfrost/AdvancedProfanityFilter#308]
Even after saving changes the next day the default settings come back.  Do I have do a import every day?

**Comment by richardfrost** [comment]
Can't say I've ever seen that happen before. I have a few questions for you so we can try to track down what is happening:

- Which browser are you using?
- Do you have extension/add-on sync turned on?
- Has it always done this for you, or is this a new development?
- Is it every day, or does it happen when you close the browser and then re-open it?

**Comment by thaddeusrose** [comment]
This issue has bee resolved with a exception in CCleaner.

**Comment by richardfrost** [comment]
Ah, that makes sense! Thanks for letting me know what the solution was, just in case anyone else has this same situation in the future.
