### ISSUE TITLE
www.fubu.tv

### ISSUE THREAD

**Issue by thaddeusrose** [richardfrost/AdvancedProfanityFilter#311]
I am in the process of dropping my cable service and replacing it with fubo.tv.  It has everything I want at 1/2 the price of what I was paying for cable.
Is it possible for you to send me the code for adding this site to your program?
I am using Win10 / Firefox browser.
I have tried following your instructions but I can not get it to work.  
Thank you.

**Comment by richardfrost** [comment]
Sorry for the delay. I've been really busy the last week. I will take a look at the site in the next few days and see if I can't figure out a config that will work for it.

**Comment by richardfrost** [comment]
Sorry that took so long.. I finally got around to it though!

Can you try this custom config and let me know how it works for you? (Option page > Audio tab > Custom Sites, and don't forget to click the "Save" button underneath).

```json
{
  "www.fubo.tv": [
    {
      "displayHide": "none",
      "displaySelector": "div.bmpui-ui-subtitle-overlay",
      "iframe": false,
      "mode": "watcher",
      "parentSelector": "div.bmpui-ui-subtitle-overlay",
      "subtitleSelector": "div.bmpui-ui-subtitle-overlay span"
    }
  ]
}
```

**Comment by richardfrost** [comment]
Version [2.20.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.20.0) includes the config from this issue. If you run into trouble, feel free to reply here, or create a new issue.
