### ISSUE TITLE
Not working on Amazon Prime Video

### ISSUE THREAD

**Issue by vindwyn** [richardfrost/AdvancedProfanityFilter#312]
I was trying to pull up Clarkson's Farm on Prime Video. The subtitles / closed-captioning worked fine by replacing the profanity, but it did not mute the audio. I tried with both Video Volume and Browser Tab options selected, but it will not mute the audio. Any ideas?

**Comment by richardfrost** [comment]
I'm sorry its not working for you. I just tested it with the first few minutes of episode one and it worked for me, so lets see if we can figure out what's different.

A few questions:
- When you are watching on Amazon, is the extension icon badge blue or green (little box next in the bottom-right corner)?
  - If its green, that means its trying to filter (mute) the audio. If it isn't green, it definitely won't work. If it is blue, please respond with a link/URL to the video you are watching.
- Have you tried the filter with other videos on Amazon with any success?
- Does it work on other sites? Netflix, YouTube, etc.?
- Would you be willing to share a copy of your config (either here or sending an email to support @ richardfrost.info)?

**Comment by vindwyn** [comment]
I retried it again today, and it is now working fine. I'm not sure what has changed. Thanks for this great service, though!

**Comment by richardfrost** [comment]
@vindwyn You're welcome! I'm glad that its working for you again. Its weird, but sometimes just restarting your computer or giving it a little time does the trick. Take care!
