### ISSUE TITLE
Crunchyroll filters

### ISSUE THREAD

**Issue by Commonman7** [richardfrost/AdvancedProfanityFilter#313]
Site just updated. Filters don't appear to work

**Comment by richardfrost** [comment]
Can you share what doesn't seem to be working? I just tested it with Fruits Basket and it seemed to work just fine. I'd be glad to test another episode/series to see if something might be different.

**Comment by richardfrost** [comment]
Just had another thought... did you switch to their beta/preview? If so, can you try putting this in the "Custom Sites" config (Options page > Audio tab)?

```json
{
  "beta.crunchyroll.com": [
    {
      "apfCaptions": true,
      "apfCaptionsSelector": "vilosVttJs",
      "displaySelector": "canvas#velocity-canvas",
      "externalSub": true,
      "externalSubTrackMode": "hidden",
      "externalSubVar": "window.v1config.media.subtitles",
      "iframe": true,
      "mode": "cue",
      "videoCueLanguage": "en-US",
      "videoCueRequireShowing": false
    }
  ]
}
```

**Comment by Commonman7** [comment]
As of the 15th, I think their entire site transitioned to beta. My account
shows beta with no option to switch back. (I did try it awhile back and
switched back). I'll try what you sent and let you know how it works.

Thanks

**Comment by richardfrost** [comment]
Ah, yeah mine still looks like it used to. I did test that config a couple weeks ago for the beta, and that did seem to work for me, but I was able opt out again after.

You may need to update the URL in that custom config based on what it shows in your browser address bar (ex: www.crunchyroll.com)

**Comment by Commonman7** [comment]
I just tried what you sent over and it seems to be working with the beta.


Thanks again

**Comment by richardfrost** [comment]
Awesome, thanks for reporting back! Did you end up needing to change the URL for it to work?

**Comment by Commonman7** [comment]
I don't. I also used a video that wouldn't filter before. No problems so
far.

**Comment by richardfrost** [comment]
Awesome! Thanks for helping with troubleshooting the issue! I'll get the beta config added to the extension in the next update. I imagine it could break again once they switch from beta.crunchyroll.com to www.crunchyroll.com, so if it stops working again, let me know and I'll get the new config rolled out. Enjoy!

**Comment by richardfrost** [comment]
Version [2.20.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.20.0) includes a fix for this issue.

**Comment by Commonman7** [comment]
I appreciate it. Thank so much

**Comment by Commonman7** [comment]
Does the profanity filter work with Firefox on Android phones? When you go
to there mobile  extensions it will not allow for a download.

Thank you

**Comment by richardfrost** [comment]
@Commonman7 it is possible on Android, but they made it a little painful to do on Firefox mobile. Check this comment for more info: https://github.com/richardfrost/AdvancedProfanityFilter/issues/243#issuecomment-726218625

You can also use a browser like Kiwi, which is a chromium-based mobile browser for Android that natively supports Chrome extensions.
