### ISSUE TITLE
Audio muting not working

### ISSUE THREAD

**Issue by Imveryweird** [richardfrost/AdvancedProfanityFilter#315]
Okay so I was watching [this video](https://www.youtube.com/watch?v=m6ydLCnG6BI&t=6s) and the audio will not mute. I've tried switching through all the settings for audio. I really don't know why this is happening. Mobile latest version of firefox nightly. M.youtube.com. I don't really know what's going on.
Edit:
I'm uploading an image, the text is censored but the Audio is not on [this video.](https://m.youtube.com/watch?v=4-u_I8o0VEk&t=548s) The first video linked has one in the first like 10 seconds that won't censor audio. Please fix this. 

![Screenshot_20210708-065854_Firefox Nightly](https://user-images.githubusercontent.com/66542108/124918244-71239300-dfba-11eb-9465-cf9c041fd147.jpg)

**Comment by richardfrost** [comment]
Thanks for opening this issue with such great details and for providing those examples.

It looks like the update I released last night caused this. I tested a YouTube video, but apparently I didn't check one with auto-generated captions. I'll get an update released ASAP, and reply here when its ready.

**Comment by Imveryweird** [comment]
Just in case these details help any ![20210708_151921.jpg](https://user-images.githubusercontent.com/66542108/124985382-f54c3980-dfff-11eb-9091-21d23005a721.jpg) in full screen mode they aren't censored, but out of the screen they are. ![20210708_151921.jpg](https://user-images.githubusercontent.com/66542108/124985455-09903680-e000-11eb-9910-b60629b6ad08.jpg)

**Comment by richardfrost** [comment]
Thanks again for reporting the issue, and for all the provided details. With what you described, I was able to pinpoint the issue and have released version [2.20.1](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.20.1) that should fix the bug.

Firefox has already approved it, so you should get the update soon. Once you get a chance to test it, let me know how it works here.

**Comment by Imveryweird** [comment]
The issue was fixed. Thanks very much.

**Comment by richardfrost** [comment]
You're very welcome! So glad you find this project useful!
