### ISSUE TITLE
"Bulk Editor" button not opening

### ISSUE THREAD

**Issue by Alex-Mirov** [richardfrost/AdvancedProfanityFilter#316]
Hello

While using the latest version of "Advanced Profanity Filter" both on phone and pc 
the "bulk editor" button not working at all even with default settings.

**Comment by richardfrost** [comment]
Thanks for reporting the issue. This bug was introduced recently, but thankfully it was an easy fix. I'll get it released today.

**Comment by richardfrost** [comment]
I just pushed version [2.20.2](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.20.2) which should fix this issue. Thanks again for reporting it! If for whatever reason it still doesn't work for you after getting the update, feel free to re-open this ticket.
