### ISSUE TITLE
Have a whitelist of good words

### ISSUE THREAD

**Issue by PrincessPandaSource** [richardfrost/AdvancedProfanityFilter#32]
## Description
Words such as "class", "grass", and "assassin" get unnecessary censors in them. It would be useful if there was a long, hidden whitelist of okay words.

**Comment by richardfrost** [comment]
Here is a good list of words that might be useful to use for the default word sets: https://github.com/dwyl/english-words/blob/master/words.txt

**Comment by richardfrost** [comment]
@PrincessPandaSource does the `exact match` method solve this concern?

**Comment by leemcd56** [comment]
I'm all for this. Words like "shell" and "assist" get censored on any setting except "Exact Match", using "Exact Match" allows certain words on [this page](https://en.wiktionary.org/wiki/Category:English_swear_words) to come through.

**Comment by richardfrost** [comment]
@leemcd56 If you use `Per-Word matching`, you should be able to get working in all cases. Let me know if that doesn't work for you, or if you have any other feedback.  Thanks!

**Comment by richardfrost** [comment]
I think this is satisfied for now. Please re-open if you need anything else.

**Comment by richardfrost** [comment]
This has come up again. When I get some time I'll try playing with this again.

**Comment by richardfrost** [comment]
Putting on the back burner again.. not sure its needed.
