### ISSUE TITLE
Failed to populate stats. [Error: TypeError: Cannot read properties of undefined (reading 'list')]

### ISSUE THREAD

**Issue by Jon-Ayden** [richardfrost/AdvancedProfanityFilter#329]
_Instructions: This template is written in Markdown. Click the "Preview" tab to see what it will look like when submitted. Fill in the applicable sections (you can erase the examples if you'd like)._

#### :bug: Description
"Failed to populate stats. [Error: TypeError: Cannot read properties of undefined (reading 'list')]"

Error pops up after saving a bulk edit. If I backup my list and restore to default settings, the error does not appear. When I restore my settings, the error appears. Despite the error message, my changes are saved, so the error does not seem to impact my settings

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Go to 'Bulk Editor'
2. Click on 'Save'
3. Add custom words

#### :heavy_check_mark: Expected behavior
List to save without issue or error

#### :computer: Details
 - **Device:*IdeaCentre AIO 3 24ARE05*
 - **OS:*Windows 10 Home* 
 - **Browser:*Chrome Beta* 
 - **Browser Version:*Version 93.0.4577.58 (Official Build) beta (64-bit)* 
 - **Affected site(s):*chrome-extension://piajkpdbaniagacofgklljacgjhefjeh/optionPage.html#* 
 - 

#### :pencil: Additional context
I have been able to save my own words to the bulk list without issue in the past, so this is a recent issue.

**Comment by Jon-Ayden** [comment]
**In case you did not get my file by email. As a side point, I understand that in the Bulk Editor the Substitution Case is meant to use your custom word as a substitution rather than censoring it if Censor is the selected Filter Method. If that understanding is correct, it is not substituting my selected words but instead censoring them along with the rest of the list that does not have Sub Case selected. I suppose I could just place asterisks as the replacement words for the whole list save for the few words and have the Filter Method on Substitute.**

{
  "audioWordlistId": 1,
  "censorCharacter": "*",
  "censorFixedLength": 1,
  "collectStats": false,
  "customAudioSites": null,
  "darkMode": false,
  "defaultSubstitution": "censored",
  "defaultWordMatchMethod": 0,
  "defaultWordRepeat": 0,
  "defaultWordSeparators": 0,
  "domains": {
    "jw.org": {
      "disabled": true
    }
  },
  "enabledDomainsOnly": false,
  "fillerAudio": "",
  "filterMethod": 0,
  "filterWordList": false,
  "iWordWhitelist": [
    "opposite sex"
  ],
  "muteAudio": true,
  "muteAudioOnly": false,
  "muteCueRequireShowing": false,
  "muteMethod": 0,
  "password": null,
  "preserveCase": true,
  "preserveFirst": false,
  "preserveLast": false,
  "showCounter": true,
  "showSubtitles": 0,
  "showSummary": true,
  "showUpdateNotification": true,
  "substitutionMark": false,
  "wordWhitelist": [],
  "wordlistId": 1,
  "wordlists": [
    "Wordlist 1",
    "Wordlist 2",
    "Wordlist 3",
    "Wordlist 4",
    "Wordlist 5",
    "Wordlist 6"
  ],
  "wordlistsEnabled": true,
  "words": {
    "ass": {
      "lists": [
        1
      ],
      "matchMethod": 0,
      "repeat": 1,
      "separators": 0,
      "sub": "butt",
      "case": 0
    },
    "asses": {
      "lists": [
        1
      ],
      "matchMethod": 0,
      "repeat": 0,
      "separators": 0,
      "sub": "butts",
      "case": 0
    },
    "asshole": {
      "lists": [
        1
      ],
      "matchMethod": 1,
      "repeat": 1,
      "separators": 1,
      "sub": "jerk",
      "case": 0
    },
    "badass": {
      "lists": [
        1
      ],
      "matchMethod": 1,
      "repeat": 1,
      "separators": 1,
      "sub": "cool",
      "case": 0
    },
    "bastard": {
      "lists": [],
      "matchMethod": 1,
      "repeat": 1,
      "separators": 0,
      "sub": "idiot",
      "case": 0
    },
    "bitch": {
      "lists": [
        1
      ],
      "matchMethod": 1,
      "repeat": 1,
      "separators": 0,
      "sub": "bench",
      "case": 0
    },
    "boob": {
      "lists": [
        1
      ],
      "matchMethod": 1,
      "repeat": 0,
      "separators": 0,
      "sub": "",
      "case": 0
    },
    "bullshit": {
      "lists": [
        1
      ],
      "matchMethod": 0,
      "repeat": 0,
      "separators": 1,
      "sub": "",
      "case": 0
    },
    "christ": {
      "lists": [],
      "matchMethod": 0,
      "repeat": 0,
      "separators": 0,
      "sub": "",
      "case": 0
    },
    "cocksucker": {
      "lists": [
        1
      ],
      "matchMethod": 1,
      "repeat": 1,
      "separators": 1,
      "sub": "suckup",
      "case": 0
    },
    "cunt": {
      "lists": [
        1
      ],
      "matchMethod": 1,
      "repeat": 1,
      "separators": 0,
      "sub": "expletive",
      "case": 0
    },
    "dammit": {
      "lists": [],
      "matchMethod": 1,
      "repeat": 0,
      "separators": 1,
      "sub": "dangit",
      "case": 0
    },
    "damn": {
      "lists": [],
      "matchMethod": 1,
      "repeat": 0,
      "separators": 0,
      "sub": "dang",
      "case": 0
    },
    "dick": {
      "lists": [
        1
      ],
      "matchMethod": 2,
      "repeat": 0,
      "separators": 0,
      "sub": "",
      "case": 0
    },
    "dumbass": {
      "lists": [
        1
      ],
      "matchMethod": 1,
      "repeat": 1,
      "separators": 0,
      "sub": "idiot",
      "case": 0
    },
    "fag": {
      "lists": [
        1
      ],
      "matchMethod": 0,
      "repeat": 1,
      "separators": 0,
      "sub": "gay",
      "case": 0
    },
    "faggot": {
      "lists": [
        1
      ],
      "matchMethod": 1,
      "repeat": 1,
      "separators": 0,
      "sub": "gay",
      "case": 0
    },
    "fags": {
      "lists": [
        1
      ],
      "matchMethod": 0,
      "repeat": 1,
      "separators": 0,
      "sub": "gays",
      "case": 0
    },
    "fuck": {
      "lists": [
        1
      ],
      "matchMethod": 2,
      "repeat": 1,
      "separators": 1,
      "sub": "freak",
      "case": 0
    },
    "fucked up": {
      "lists": [
        1
      ],
      "matchMethod": 0,
      "repeat": 0,
      "separators": 0,
      "sub": "messed up",
      "case": 1
    },
    "goddammit": {
      "lists": [
        1
      ],
      "matchMethod": 1,
      "repeat": 1,
      "separators": 1,
      "sub": "dangit",
      "case": 0
    },
    "goddamn": {
      "lists": [
        1
      ],
      "matchMethod": 0,
      "repeat": 0,
      "separators": 1,
      "sub": "",
      "case": 0
    },
    "hell": {
      "lists": [],
      "matchMethod": 0,
      "repeat": 0,
      "separators": 0,
      "sub": "heck",
      "case": 0
    },
    "jackass": {
      "lists": [
        1
      ],
      "matchMethod": 1,
      "repeat": 1,
      "separators": 1,
      "sub": "jerk",
      "case": 0
    },
    "jesus": {
      "lists": [],
      "matchMethod": 0,
      "repeat": 0,
      "separators": 0,
      "sub": "",
      "case": 0
    },
    "nigga": {
      "lists": [
        1
      ],
      "matchMethod": 0,
      "repeat": 1,
      "separators": 0,
      "sub": "bruh",
      "case": 0
    },
    "nigger": {
      "lists": [
        1
      ],
      "matchMethod": 0,
      "repeat": 1,
      "separators": 0,
      "sub": "man",
      "case": 0
    },
    "niggers": {
      "lists": [
        1
      ],
      "matchMethod": 0,
      "repeat": 1,
      "separators": 0,
      "sub": "people",
      "case": 0
    },
    "penis": {
      "lists": [
        1
      ],
      "matchMethod": 2,
      "repeat": 0,
      "separators": 0,
      "sub": "",
      "case": 0
    },
    "piss": {
      "lists": [],
      "matchMethod": 1,
      "repeat": 1,
      "separators": 0,
      "sub": "pee",
      "case": 0
    },
    "pissed": {
      "lists": [],
      "matchMethod": 1,
      "repeat": 1,
      "separators": 0,
      "sub": "ticked",
      "case": 0
    },
    "pussies": {
      "lists": [
        1
      ],
      "matchMethod": 0,
      "repeat": 1,
      "separators": 0,
      "sub": "softies",
      "case": 0
    },
    "pussy": {
      "lists": [
        1
      ],
      "matchMethod": 0,
      "repeat": 1,
      "separators": 0,
      "sub": "softie",
      "case": 0
    },
    "sex": {
      "lists": [
        1
      ],
      "matchMethod": 0,
      "repeat": 0,
      "separators": 0,
      "sub": "",
      "case": 0
    },
    "shit": {
      "lists": [
        1
      ],
      "matchMethod": 2,
      "repeat": 1,
      "separators": 0,
      "sub": "crap",
      "case": 0
    },
    "slut": {
      "lists": [
        1
      ],
      "matchMethod": 1,
      "repeat": 1,
      "separators": 0,
      "sub": "tramp",
      "case": 0
    },
    "tits": {
      "lists": [
        1
      ],
      "matchMethod": 1,
      "repeat": 1,
      "separators": 0,
      "sub": "chest",
      "case": 0
    },
    "twat": {
      "lists": [
        1
      ],
      "matchMethod": 0,
      "repeat": 1,
      "separators": 0,
      "sub": "dumbo",
      "case": 0
    },
    "twats": {
      "lists": [
        1
      ],
      "matchMethod": 0,
      "repeat": 1,
      "separators": 0,
      "sub": "dumbos",
      "case": 0
    },
    "vagina": {
      "lists": [
        1
      ],
      "matchMethod": 2,
      "repeat": 0,
      "separators": 0,
      "sub": "",
      "case": 0
    },
    "whore": {
      "lists": [
        1
      ],
      "matchMethod": 1,
      "repeat": 1,
      "separators": 0,
      "sub": "tramp",
      "case": 0
    }
  },
  "youTubeAutoSubsMax": 0,
  "youTubeAutoSubsMin": 0
}

**Comment by richardfrost** [comment]
Thanks for sending that in. I didn't get your previous email, but this helped me track down the bug. I'll try to get it patched tonight or tomorrow morning.

On to your question about the bulk editor, `Substitution Case` is simply an option for the substituted word to match the case (capitalization) of the word its replacing. This only applies when you are using the `Substitution` filter mode, and will be ignored if you are using another like `Censor`. As an example, it will replace `WORD` with `REPLACEMENT` instead of `replacement`. It helps make the substitution feel more natural.

Right now there is no way to have multiple filter modes active at the same time. Its not really something I'm planning to do unless I hear a pretty compelling use-case. You can do as you describe and manually "censor" a replacement word with `*` or whatever you'd like if that is helpful.

**Comment by richardfrost** [comment]
This should now be fixed when the extension updates (automatically) to version [2.24.1](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.24.1). Let me know once you get a chance to test it and if its resolved we'll go ahead and close this issue.

**Comment by Jon-Ayden** [comment]
I went in to the bulk editor, and pressed Save (without adding any word,
because in the past just clicking Save would bring the error message) and
the error message no longer appears! Thanks for quickly fixing this. Also,
thank you for your explanation of the other issue. Awesome work 👍🏻

**Comment by richardfrost** [comment]
You're welcome! Thanks for your sharing your config so I could track it down faster.
