### ISSUE TITLE
fubo.tv Subtitles

### ISSUE THREAD

**Issue by jcellswo** [richardfrost/AdvancedProfanityFilter#331]
_Instructions: This template is written in Markdown. Click the "Preview" tab to see what it will look like when submitted. Fill in the applicable sections (you can erase the examples if you'd like). For more information, please see [this page](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/New-Audio-Muting-Site)._

#### :movie_camera: The Site
_fubo.tv_

#### :speech_balloon: Subtitle Element/Node
_Example:_
```html
<div class="subtitle-container">
  <p class="subtitle-text">Subtitle text</p>
</div>
```

#### :pencil: Additional notes
_Add any other context or screenshots about the request here._

**Comment by richardfrost** [comment]
Is there an issue with the current audio muting rule for this site? What can I do to help with this issue?

**Comment by jcellswo** [comment]
Sorry, I wasn’t sure of the proper format for a question. I couldn’t get
the audio filtering to work on fubo.tv and didn’t see it in the list of
approved sites.

**Comment by richardfrost** [comment]
No worries! I think it did work a few months ago, but its possible something may have changed. Is the filtering working on other supported sites (youtube, netflix, etc.) for you?

I did a quick test and it seemed to be working for me, but if you can get me more details I'll try to take a closer look at it.

**Comment by richardfrost** [comment]
@jcellswo Hello, sorry its been so long, but I was able to test it again, and it looks like its working for me as configured. If you are still having trouble with it please let me know what movie or channel or type of program is giving you trouble. Otherwise, I'll go ahead and close this.
