### ISSUE TITLE
Recommended Extension

### ISSUE THREAD

**Issue by Alex-Mirov** [richardfrost/AdvancedProfanityFilter#332]
Hello

What are the chances to the extension to appear at the recommended list for
firefox android with the latest versions?

Thanks

**Comment by richardfrost** [comment]
Looking at the "Will more extensions be supported in the future?" section of [Find and install Add-ons on Firefox for Android](https://support.mozilla.org/en-US/kb/find-and-install-add-ons-firefox-android#w_will-more-extensions-be-supported-in-the-future), it sounds like they are still working through their process for adding more. I don't see any sort of submission process for add-ons, so I think all we can do right now is wait.

The most common ways I know to use this (or other add-ons) is to either use an older version of Firefox that supported them (not recommended), or use Firefox Nightly and follow the instructions [here](https://github.com/richardfrost/AdvancedProfanityFilter/issues/243#issuecomment-726218625).

**Comment by travislibby000000** [comment]
Hi Richard,This is Travis.I am working on the media player for my DVD movies. For Profanity Filtering. Can you help me with this

Sent from Yahoo Mail for iPhone


On Monday, August 30, 2021, 8:45 AM, Richard Frost ***@***.***> wrote:




Looking at the "Will more extensions be supported in the future?" section of Find and install Add-ons on Firefox for Android, it sounds like they are still working through their process for adding more. I don't see any sort of submission process for add-ons, so I think all we can do right now is wait.

The most common ways I know to use this (or other add-ons) is to either use an older version of Firefox that supported them (not recommended), or use Firefox Nightly and follow the instructions here.

**Comment by richardfrost** [comment]
Since right now this is just a waiting game, I'm going to close this. If there are any new developments we can re-open this.
