### ISSUE TITLE
Advanced Profanity Filter for iOS 15?

### ISSUE THREAD

**Issue by GameParrot** [richardfrost/AdvancedProfanityFilter#338]
_Instructions: This template is written in Markdown. Click the "Preview" tab to see what it will look like when submitted. Fill in the applicable sections (you can erase the examples if you'd like)._

#### :loudspeaker: The Shortcoming
With iOS 15, it is possible to run Advanced Profanity Filter on iPhones and iPads because iOS 15 added Safari extensions. However, it is not currently available. 

#### :microscope: Describe the solution you'd like
It would be nice if there was a version for iOS that doesn't expire after a week.

#### :triangular_ruler: Describe alternatives you've considered
An alternative would be to use safari-web-extension-converter and re-build it every week.

#### :pencil: Additional context
I got it working, but it will expire after a week.
![IMG_5900](https://user-images.githubusercontent.com/85067619/134089504-07742c80-a0da-4a88-9895-874e8de8410d.PNG)
![IMG_5901](https://user-images.githubusercontent.com/85067619/134089508-189a1113-fdd7-40ba-8b64-e26de8142cf4.PNG)

**Comment by richardfrost** [comment]
Hey that's awesome! I bought a Mac a couple months back to test this out, and then got really busy with other things and haven't had much of a chance to play around with it. I definitely would like to make it available for iOS.

What did you have to do to get it working? I was able to get it working in desktop Safari, but didn't have enough time to figure out how to test it in the iPhone/iPad simulator. I don't currently have a developer account, and I read you can't test on a device without one (but that may have been inaccurate). If I can be sure it will work without too much trouble/maintenance I'd be willing to pay the fee for a year and see how much interest there is.

Anyway, if you could share what steps you did I'd be happy to try and take a look at it. @Joghurtbecher08115 was the first one to bring this to my attention, so I'm sure he'd be really interested in seeing it running as well. That conversation is available here: https://github.com/richardfrost/AdvancedProfanityFilter/discussions/310.

**Comment by GameParrot** [comment]
I used the `xcrun safari-web-extension-converter --copy-resources --ios-only /path/to/extension` command. Xcode project:
[Advanced Profanity Filter.zip](https://github.com/richardfrost/AdvancedProfanityFilter/files/7199311/Advanced.Profanity.Filter.zip)

**Comment by richardfrost** [comment]
Sorry its taken so long @GameParrot, but I finally have a test build if you're still interested in taking a look. Please fill out the form here: https://forms.gle/nwfZRSTzXpWa5vsH6 to get access.

**Comment by richardfrost** [comment]
I'm excited to announce that Apple has approved the APF app, and it is available for purchase in the App Store here: https://apps.apple.com/us/app/advanced-profanity-filter/id1593810102

It is available for both iOS (15+) and macOS. Due to the cost of being an Apple developer, I won't be able share it for free at this time, so it will require a one-time purchase. The purchase will unlock it for iOS and macOS and can be shared with everyone in your "Apple Family".

Thanks @GameParrot for the suggestion and helping make this happen.

**Comment by taeuscherpferd** [comment]
Dude you're like my hero! I have loved having your extension on my desktop, and came here looking to see if I could port it to iOS, only to find that you had already finished it! Just bought the app a few days ago and have been very happy with the results. The only downside that I can see is that it doesn't seem to work while videos are in full-screen mode, but I'd imagine that it would be tough to find a way to filter words if Apple is loading videos into their own video player. At any rate, thank you so much for making my world a better place, and great work on this extension. Seems to me like you could close this one out 👍

**Comment by richardfrost** [comment]
@taeuscherpferd Thanks for the kind words! I'm so glad you are liking it. If you haven't had a chance, I definitely appreciate reviews on the store you downloaded it from 😉.

As for full-screen videos, are you talking about full-screen in Safari, or in another app? If its in Safari, it may be possible to help them work if they aren't now. If it is playing in Safari, could you give me an example and I'll take a look. Thanks again, and I do think I'll close this now, but please feel free to respond here even though its closed.

**Comment by taeuscherpferd** [comment]
Done! 

As far as the full screen mode filtering goes, yes I have been using Safari, but it seems as though it uses a different system than the in browser video player once you go full screen. It seems like it's built a bit deeper into the OS to allow things like Picture in Picture mode. Here's a screenshot of my settings just in case I've configured something wrong, and here's a screenshot of where to find the full screen button on YouTube just in case you haven't used it much 😉. The easiest way I can think of to try and test it would be to add "shark" to your list of words to filter and then pull up the baby shark video. You'll know pretty quick whether it's working or not 😂 Thanks again for working on this app, and let me know if there's anything else I can do to help 👍
![IMG_1759](https://user-images.githubusercontent.com/7101562/170179457-024282f3-2e00-4c76-8dd1-ee5b3eacb584.png)

![IMG_1760](https://user-images.githubusercontent.com/7101562/170180172-22d2f567-67a7-4006-8849-6e599de89851.jpeg)
