### ISSUE TITLE
(Issue) Censoring "God" without ruining pages that mentions a religious god.

### ISSUE THREAD

**Issue by RiffyDiffy** [richardfrost/AdvancedProfanityFilter#342]
#### :bug: Description
Here's the thing, I want to censor the word "God" ONLY in expressions (Ex: Oh My God"), but NOT in pages where they mention a god (Ex: "My disciples, rejoice! Behold, the God of Anemo, Barbatos has descended!" -Venti).

There's another issue within it, sometimes, people just say the expression without adding a comma at the end of the word "God" (Ex: "GOD that was a mouthful"), which was not affected by the profanity filter.

#### :twisted_rightwards_arrows: Steps To Reproduce
You get the idea, go to the affected site.

#### :computer: Details
 - Computer: HP Pavilion Computer
 - OS: Windows 11 Insider Beta Version 22000.194
 - Browser: Vivaldi
 - Browser Version: 4.2.2406.48
 - **Affected site(s):** https://gamebanana.com/tuts/14077

#### :pencil: Additional context
Please, please, _**PLEASE!!**_ Help me with this issue, this is a hair-pulling problem I've been facing for months!

**Comment by richardfrost** [comment]
Hello @RiffyDiffy, unfortunately its outside the scope of this project to be able to identify intent like that. Using the current tools available in the filter, hopefully you can find something that will work for you:

- Disable the filter on "religious" pages
- Add phrases like the ones you mentioned above to the filter, so it will only filter when it matches those words together.
- Setup different word lists and choose them according to the page you are on. Maybe default to a stricter wordlist for all sites, but then choose a wordlist that doesn't include religious words for sites more prone to using those religious terms correctly.

If you have any questions on how to implement one of these strategies, or if you have any follow up questions let me know.

**Comment by richardfrost** [comment]
Due to inactivity, I'm going to close this. If this is still an issue, feel free to respond and re-open this issue.
