### ISSUE TITLE
Slow page load on some reddit pages

### ISSUE THREAD

**Issue by Alex-Mirov** [richardfrost/AdvancedProfanityFilter#346]
Hello

When i'm trying to enter reddit page for example:  
"https://www.reddit.com/r/halo/comments/ecie3j/new_mcc_update_makes_me_reinstall_the_entire_game/"
it will result in a very slow load page or getting loop load.
This behavior will appear on some reddit pages but not all them which is makes hard to track the bug.

P.S: This bug also appears on stock settings.

Browser: Firefox (93.0 64-bit)
O.S: Win 10 64-bit
Extension version: 2.25.0

**Comment by richardfrost** [comment]
Sounds good. Thanks!
