### ISSUE TITLE
Support for Pale Moon.

### ISSUE THREAD

**Issue by RiffyDiffy** [richardfrost/AdvancedProfanityFilter#357]
To simply put in, since I believe that Pale Moon is one of the most lightweight browsers, I was a bit surprised that Advanced Profanity Filter was not in Pale Moon's addons list.

Will there be any support for Pale Moon? I would love to see this happen!

Here's a link to the website: [https://www.palemoon.org/](https://www.palemoon.org/)

**Comment by BE-Code** [comment]
Have you tried using the firefox version of the addon?

**Comment by RiffyDiffy** [comment]
@BE-Code You mean this one? https://addons.mozilla.org/en-US/firefox/addon/advanced_profanity_filter/

Sadly, it failed.
![palemoon_nbxSyqB7Ew](https://user-images.githubusercontent.com/81842790/142912289-92b746fa-c691-483d-86d2-63a9cdecda88.png)

**Comment by richardfrost** [comment]
I spent a few minutes looking into it, and it appears they [don't support WebExtensions](https://www.palemoon.org/roadmap.shtml). There isn't really a reason why it couldn't be supported with a fork, or even just a different build using their extension APIs, but I don't have time to take that on right now. If anyone is interested in taking a crack at it I'd be happy to try and help support.

**Comment by richardfrost** [comment]
Going to close this for now, as I have no time to maintain another extension, and there haven't been any volunteers. If anyone would like to, please let me know and I'm happy to discuss it and help out where I can.
