### ISSUE TITLE
Covering the blocked words with a rectangle

### ISSUE THREAD

**Issue by vadoler** [richardfrost/AdvancedProfanityFilter#358]
Hello, I'd like if this extension have the feature where I can notice the muted word as a red rectangular box covering the whole word, It's width depends on how long the blocked word is, If it's technically possible, will be much helpful if the user can choose which color the rectangle will be.

**Comment by richardfrost** [comment]
Thanks for the suggestion @vadoler. I've got a few other things I need to take care of before taking a deeper look at this, but I'll get to it as soon as I'm able.

**Comment by BE-Code** [comment]
This could be done by adding colored square emojis to the list of Censor Character options. That would have the effect of the swear word looking like this: 🟥🟥🟥🟥. Would that meet your need @vadoler?

**Comment by richardfrost** [comment]
That is a really awesome idea @BE-Code. You can test it now if you want by applying it to the config directly. Option page > Config > Inline Editor. Look for `censorCharacter` and just replace it with one of those colored emojis.

**Comment by BE-Code** [comment]
That works for me. If it doesn't need to be colored, the character "█" works even better.

**Comment by vadoler** [comment]
> This could be done by adding colored square emojis to the list of Censor Character options. That would have the effect of the swear word looking like this: 🟥🟥🟥🟥. Would that meet your need @vadoler? Those squares come in a decent number of colors: ⬛🟦🟫🟩🟧🟪🟥🟨⬜.

I like this trick! It really does the job, I also did the method @richardfrost said about Inline Editor, It Works like a charm, Thanks everyone!

**Comment by richardfrost** [comment]
Yeah! I think this is a cool idea and will add it to the extension officially. Thanks @vadoler and @BE-Code.

**Comment by richardfrost** [comment]
Just so you know, this feature should now be included in version [2.28.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.28.0). Thanks again for the suggestions @neolarbio and @BE-Code!
