### ISSUE TITLE
Never working on YouTube

### ISSUE THREAD

**Issue by tonyram57** [richardfrost/AdvancedProfanityFilter#363]
Your extension seems to never filter any profanity from YouTube.  It just plan does work.  I played this video
https://www.youtube.com/watch?v=K4a8Yj6rPN0
she says somewhere at the 7:00 mark "These are f**king nice."

**Comment by richardfrost** [comment]
Thanks for reporting the issue. Unfortunately the filter can only mute the audio when it detects words to filter in the captions/subtitles, and in your example it isn't present. YouTube has made some interesting choices with their auto-generated captions, where they will remove curse words from the captions, but obviously keep them in the audio. From what I understand the content creator can opt into generating the captions with the curse words, but by default its off.

There may be more information here in this thread starting with [this comment](https://github.com/richardfrost/AdvancedProfanityFilter/issues/251#issuecomment-703759499).

Just to re-iterate, this filter is only as good as the captions/subtitles accompanying the video, and there isn't a lot that the filter can do to help compensate when the timing is off, or words are spoken but not included in the text.

Let me know if you have any other questions or comments.

**Comment by tonyram57** [comment]
Thanks for explaining.

**Comment by richardfrost** [comment]
@tonyram57 Of course! Sorry I didn't have better news. If you see any video where the captions show the word but the filter misses it, please let me know! I hope that Google ends up re-evaluating their decision. It doesn't really make sense to me that they don't want to include the captions for what is actually being said, but I guess that's their choice.

**Comment by richardfrost** [comment]
I'm going to go ahead and close this, because at least in this example there really isn't anything I can change with the filter. Feel free to reply here if you'd like to re-open the issue, or start a new one. Thanks!
