### ISSUE TITLE
Not working on Redbox stream 

### ISSUE THREAD

**Issue by CrazyDuck49** [richardfrost/AdvancedProfanityFilter#364]
The audio editing isn't working on Redbox's streaming site

**Comment by richardfrost** [comment]
Thanks for reporting the issue. I'll take a look at it as soon as I can in the next few days. Do you have a specific title that it isn't working on? I like to have one (even if it doesn't seem to be working on any of them) because that gives me a good place to test and get it working.

**Comment by CrazyDuck49** [comment]
I was watching "Nobody"

**Comment by richardfrost** [comment]
Sorry it took so long, still playing catch-up from the holidays. Can you give this config a try? I tested it on a handful of free (with ads) videos with pretty good success.

To use this config, copy it into the Custom Sites box (Options page > Audio tab) and then click the save button underneath it:

```json
{
  "www.redbox.com": [
    {
      "mode": "elementChild",
      "parentSelector": "div.rb-text-container",
      "subtitleSelector": "SPAN > SPAN",
      "tagName": "DIV"
    }
  ]
}
```

**Comment by richardfrost** [comment]
I'm sorry its been a couple weeks, but I pushed [2.29.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.29.0) that should hopefully help with Redbox audio muting. If you get an opportunity to test it, I'd love to hear how it is working for you. Thanks!

**Comment by richardfrost** [comment]
@CrazyDuck49 Have you had a chance to see if the latest version of the filter is working? I'm going to go ahead and close this issue, but if you still have trouble with it feel free to re-open this issue, or create a new one.
