### ISSUE TITLE
BBC Uplayer

### ISSUE THREAD

**Issue by lukefarr** [richardfrost/AdvancedProfanityFilter#366]
_Instructions: This template is written in Markdown. Click the "Preview" tab to see what it will look like when submitted. Fill in the applicable sections (you can erase the examples if you'd like). For more information, please see [this page](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/New-Audio-Muting-Site)._

#### :movie_camera: BBC Iplayer
https://www.bbc.co.uk/iplayer/

#### :speech_balloon: Subtitle Element/Node
_Example:_
```html
<div class="p_cueDirUniWrapper"
</div>
```

#### :pencil: Additional notes
Im so sorry, i followed the instructions as best as i could to add this site. I identified the words as an element text mode but inserting a conditional break did not result in it hitting a break point. 

I tried this in the area to add a custom site but no joy, as likely i have done something wrong
```json
{
  "bbc.co.uk": {
    "textParentSelector": "div.p_subtitlesContainer"
  }
}
```

**Comment by richardfrost** [comment]
Thanks for reaching out for help @lukefarr! I will see if I can get on and take a look around the site soon.

**Comment by lukefarr** [comment]
Thanks Richard. I closed because I saw that someone had reached out for this site already. I used the code you had identified:
{
  "www.bbc.co.uk": [
    {
      "mode": "element",
      "tagName": "div",
      "subtitleSelector": "div.p_cueDirUniWrapper span"
    }
  ]
}

But for some wierd reason it *** the words in the subtitles but will not mute the audio

**Comment by richardfrost** [comment]
@lukefarr Ah, thanks for finding that [other issue](#336). We can use that one to hopefully get to the bottom of this.
