### ISSUE TITLE
Audio Muting for Shows and Movies on fxnow.fxnetworks.com

### ISSUE THREAD

**Issue by shwayzee0** [richardfrost/AdvancedProfanityFilter#372]
Hello,

Is it possible to get an update so that the audio muting feature is usable on https://fxnow.fxnetworks.com? I know that fox.com is already supported, but all of the on demand shows and movies from the FX, FXX, and Fox Movie channels are only hosted on the fxnetworks.com website.

Thanks for all the great support for this awesome extension!

**Comment by richardfrost** [comment]
@shwayzee0 You're welcome! Thanks for sharing the suggestion.

Unfortunately I don't have access to FX at this time, but its possible they may be using the same system for their captions/subtitles as Fox. Could you try adding the following to your Custom sites (Options page > Audio tab) and click the save button:

```json
{
  "fxnow.fxnetworks.com": [
    {
      "className": "jw-text-track-container",
      "mode": "element",
      "subtitleSelector": "div.jw-text-track-cue",
      "tagName": "DIV"
    }
  ]
}
```

After that, refresh the FX tab, or if you don't have one already open, go navigate to it and give it a try. Let me know how it works. Also, you can just add a word temporarily to the filter for testing like this if you'd like to not test on a word you don't want to hear.

**Comment by shwayzee0** [comment]
Thanks for the fast response!

Unfortunately though, that fix didn't do the trick. I tried restarting the browser a couple of times after saving the syntax to the custom audio tab, but it still didn't work.

**Comment by richardfrost** [comment]
Hello again @shwayzee0, could you give this config a try?

```json
{
  "fxnow.fxnetworks.com": [
    {
      "iframe": true,
      "mode": "cue",
      "videoSelector": "video"
    }
  ]
}
```

That worked on a few free trailers I was able to play on the site, and I'm hopeful that it will work on their full-length titles too. Let me know how it goes.

**Comment by richardfrost** [comment]
This should be added in version [2.33.4](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.33.4). I'm going to go ahead and close it, but feel free to reply here once you've had a chance to test it. I'm happy to re-open the issue if this doesn't work for you.
