### ISSUE TITLE
iview.abc.net.au audio muting / subtitle filtering

### ISSUE THREAD

**Issue by ahkelly** [richardfrost/AdvancedProfanityFilter#375]
_Instructions: This template is written in Markdown. Click the "Preview" tab to see what it will look like when submitted. Fill in the applicable sections (you can erase the examples if you'd like). For more information, please see [this page](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/New-Audio-Muting-Site)._

#### :movie_camera: The Site
iview.abc.net.au

#### :speech_balloon: Subtitle Element/Node
_Example:_
```html
<div class="jw-text-track-display jw-reset" style="text-align: center; white-space: pre-line; position: absolute; direction: ltr; writing-mode: horizontal-tb; unicode-bidi: plaintext; left: 256.5px; top: 552.656px; bottom: 45.5px; height: 87px;">
  <div class="jw-text-track-cue jw-reset" style="position: relative; padding-left: 0px; padding-right: 0px; left: 0px; top: 0px; bottom: 0px; display: inline; white-space: pre; writing-mode: horizontal-tb; unicode-bidi: plaintext;">VINNIE: (OVER PHONE) Yeah, yeah.
    No worries. What is it?
  </div>
</div>
```

#### :pencil: Additional notes
I tried the following so far without any success
```html
{
  "iview,abc.net.au": [
    {
      "mode": "element",
      "tagName": "div",
      "subtitleSelector": "div.jw-text-track-cue",
      "filterSubtitles": true
    }
  ]
}
```

**Comment by richardfrost** [comment]
Assuming the element that gets added/changed on the page is the one in the example, it looks like that config should work, aside from a typo (`,` instead of `.`) in the hostname there (should be `iview.abc.net.au`).

If it still doesn't work after making that change and refreshing, what is the parent of that `div` in your example?

**Comment by ahkelly** [comment]
Actually, yes that did work once I corrected the typo and refreshed. Cheers

**Comment by richardfrost** [comment]
@ahkelly Awesome, glad to hear it. I'll make sure to add this config into the extension so you won't have to use the custom audio config for it to work. You can keep it there if you'd like though if its working.

Thanks again for helping out, and for letting me know that its working for you.

If you have a few more minutes, it would be helpful if you could help me track down the video element on BBC (outlined in [this comment](https://github.com/richardfrost/AdvancedProfanityFilter/issues/336#issuecomment-1027210482). If not, that's okay too. Thanks!
