### ISSUE TITLE
Filter stops working after cleaning cache using third party programs using Google Chrome.

### ISSUE THREAD

**Issue by tonyram57** [richardfrost/AdvancedProfanityFilter#377]
I use CCleaner and Wise Disk Cleaner and whenever I run those programs to clear the browser cache APF stops working and stops filtering anything.  I must remove the extension and reinstall it then import my settings to get it working again.

If I clear Chrome cache in the browser settings it does not break the extension.

I attached my APF settings
[apf-backup-2020-08-28_175524.zip](https://github.com/richardfrost/AdvancedProfanityFilter/files/8036673/apf-backup-2020-08-28_175524.zip)
.

**Comment by richardfrost** [comment]
Is that your config before, or after you run those programs?

**Comment by richardfrost** [comment]
Are you getting any errors? Does the Options page load when its in that state?

**Comment by richardfrost** [comment]
That's definitely some pretty strange behavior. If you want to keep looking into it, here are the next questions:

1. Can you turn on error collection for the extension? (Right-click on extension and choose "Manage extension", then turn on "Collect errors", as shown in the image below:
    - ![image](https://user-images.githubusercontent.com/1507205/153309240-bb6440dc-3e6f-4768-86f9-c7b50dc01152.png)
    - Once those are on, and the filter stops working, see if there are any errors, available here: chrome://extensions/
2. Can you attach the config that takes place after running the cleaner, just to make sure it hasn't changed?
3. Have you tried completely restarting chrome after running the cleaner, and does it still not work? If it still doesn't work, how about restarting the computer? Does it work after that?

**Comment by tonyram57** [comment]
Thanks for getting back so quickly. Next time I am at my PC I will try those steps.

**Comment by tonyram57** [comment]
Recent update to the extention fixed the problem.  It continues working after cleaning the cache using CCleaner and Wize Disk Cleaner.

**Comment by richardfrost** [comment]
@tonyram57 Awesome! I'll go ahead and close this then. Feel free to re-open it or create a new issue if the problem comes back.
