### ISSUE TITLE
Channel 4 UK Audio Muting Support

### ISSUE THREAD

**Issue by ahkelly** [richardfrost/AdvancedProfanityFilter#379]
OK, latest challenge is channel 4 UK

I have added custom support which is working for filtering the subtitles but not the audio. You are excellent at seeing what I am missing. Please see snippet of subtitles below

```html
<div class="subtitles-container" aria-hidden="true">
  <span class="active-cue">
    <span class="cue-yellow">What? Help you make mum like your</span>
    <br>
    <span class="cue-yellow">horrible caravan?</span>
    <br>
    <span class="cue-cyan"> Yes.</span>
    <br>
  </span>
</div>
```

I have tried the following, which as I said does successfully filter the text but not the audio for some reason

```json
{
  "www.channel4.com": [
    {
      "filterSubtitles": true,
      "mode": "element",
      "subtitleSelector": "span.cue-yellow",
      "tagName": "span"
    }
  ]
}
```

**Comment by richardfrost** [comment]
If this happens to be the `node`  found by following this [guide](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Custom-Audio-Muting-Site#2-elementtext-mode), the I would recommend this rule:

```json
{
  "www.channel4.com": [
    {
      "mode": "element",
      "subtitleSelector": "span.active-cue > span",
      "tagName": "div",
      "className": "subtitles-container",
    }
  ]
}
```

Let me know if that works for you, or if you have any other questions.

**Comment by ahkelly** [comment]
Hi, thanks for the feedback. I tried this updated json and still no audio muting. Caption substituting is working great.
I did follow your direction in that link again and it and it returned only the inner element
```html
<span class="cue-white">She's drinking gin. That's what she</span>
```
Which is why I copied the parent element from the site tonight

```html
<div class="subtitles-container" aria-hidden="true">
  <span class="active-cue">
    <span class="cue-white">She's drinking gin. That's what she</span><br>
    <span class="cue-white">drinks when she's...</span><br>
  </span>
</div>
```

Any other thoughts

Below is my screenshot of the audio tab
![channel4-custom-audio](https://user-images.githubusercontent.com/7065207/154385866-92f8715c-053f-4a65-9f91-865a96911e4a.PNG)

Also the tab showing your extension filtering the words like a champion
![filter-words](https://user-images.githubusercontent.com/7065207/154386191-79454c6e-8079-4b62-8952-f6befdff28b0.PNG)

Finally here is a screenshot of the video and elements tab showing the subtitles in the source in case you see something I missed

![channel-4-video-elements](https://user-images.githubusercontent.com/7065207/154386331-8a021e58-ce91-4da5-a9ca-4f57fce64c72.PNG)

Thanks again for your help

**Comment by richardfrost** [comment]
Thanks for all those additional details, that was perfect! Unfortunately it may be a bit more complicated if they are splitting up the captions into separate elements like in your example.

I have a couple rules that I'd like you to try if you can.

### Preferred
If this works, it is definitely preferred because it gives better performance, and if you like hiding the captions will also work better as well. Try this one first and let me know how it goes. If it mutes really fast and then unmutes, there are a few other things that we can try with it, to just let me know how it goes.

```json
{
  "www.channel4.com": [
    {
      "mode": "elementChild",
      "parentSelector": "div.subtitles-container",
      "tagName": "SPAN"
    }
  ]
}
```

### Alternative
This is a pretty good option, and is more flexible for complex situations. This one checks the page every 20ms (or 50 times a second) for changes to the captions. Unfortunately this can lead to a delay in muting (it may be a bit later to mute/unmute).

```json
{
  "www.channel4.com": [
    {
      "displayHide": "none",
      "displaySelector": "div.subtitles-container",
      "displayShow": "",
      "mode": "watcher",
      "subtitleSelector": "div.subtitles-container > span > span"
    }
  ]
}
```

**Comment by ahkelly** [comment]
Once again, brilliant! I just did a brief test but the Preferred method worked great. Muting was just like others (mutes basically the whole sentence containing the filtered word). Now onto ITV! This one  seems a bit more of a challenge also.
Thanks again

**Comment by richardfrost** [comment]
You're very welcome! One thing to check quick before we celebrate too much:

Can you test with a filtered word in the first element, and then in the second element? You can add a temporary word just for this test, but I want to make sure it isn't just working on just one.

For example:
```html
<span class="cue-white">She's drinking gin. That's what she</span><br>
<span class="cue-white">drinks when she's...</span><br>
```

Try it once with `drinking` being filtered, and if it works, remove/replace that word with `drinks` and test it in that same spot. It should work, but I want to make sure.

Also, one other thing, if you could check if the hiding of the captions work that would be great. I usually set it to "Show only filtered", and just make sure the captions are hidden unless there is a filtered word.

Assuming that all works, I'll go ahead and get it added to the filter officially so you won't need this custom rule anymore (but it won't hurt anything to leave it either).

**Comment by ahkelly** [comment]
OK, So the verdict is both elements appear to be successfully filtered. Results are shown below. The only issues I see with the captions hidden there is a style display issue. In summary I believe it's working perfect. The display glitch is probably out of your control as far as changing styles on hidden captions.

First element drinking filtered

![first-element-filtered](https://user-images.githubusercontent.com/7065207/154611328-a6ee1a2d-27a2-4fc4-af64-76222fab4305.jpg)

Second Element drinks filtered

![second-element-filtered](https://user-images.githubusercontent.com/7065207/154611379-816685eb-74e8-4f79-8402-cc0be39317d3.jpg)

As you can see when captions are hidden the background on the captions remains

![captions-all-hidden](https://user-images.githubusercontent.com/7065207/154611691-adf043b4-02bc-4278-a463-1cd5b423d140.jpg)

**Comment by richardfrost** [comment]
Thanks for testing that! Could you give this a quick try and see if it removes the black box when the elements are hidden?

```json
{
  "www.channel4.com": [
    {
      "displaySelector": "div.subtitles-container",
      "mode": "elementChild",
      "parentSelector": "div.subtitles-container",
      "tagName": "SPAN"
    }
  ]
}
```

Also, feel free to create another issue if you have another site you'd like to support (like ITV).

**Comment by ahkelly** [comment]
Brilliant, so yes. That solved the display glitch! No everything is working perfect with "Show only filtered" selected. I just opened a new issue for ITV.

Thanks again, the list of supported sites continues to grow!

**Comment by richardfrost** [comment]
I just submitted version [2.32.2](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.32.2) which now includes this config.  You should be able to remove it from the custom sites if you'd like. I generally recommend using the rules included with the filter, just in case an update happens to the rule or the filter itself.

Thanks again @ahkelly for all your work and help in getting this working.
