### ISSUE TITLE
Filtering "smartwatch" and I can't find the word in settings

### ISSUE THREAD

**Issue by JacobChild** [richardfrost/AdvancedProfanityFilter#381]
#### :bug: Description
Every instance of the word "smartwatch" is replaced with smardumboch. I checked on the "test" page for the filter and saw that it was changing it. I was unable to find the word to remove it from the filter list.

#### :twisted_rightwards_arrows: Steps To Reproduce
I am on Opera and running the add on in Substitute mode.

Thanks for an otherwise fantastic Add On!

**Comment by richardfrost** [comment]
Sorry about that. Are you running the extension from the Opera store, or from the Chrome Web Store? Unfortunately I haven't been able to get an update released on Opera for almost a year now, and haven't heard anything back from their support as to why my updates aren't getting processed. My recommendation is to try installing it from the Chrome Web Store.

Here is an [post from the Opera blog](https://blogs.opera.com/tips-and-tricks/2021/10/using-addons-from-chrome-in-opera/) about how to install Chrome extensions in Opera. If you do decide to install the Chrome version in Opera (which I unless I can have them release the updates), you can export your configuration by clicking the "Export" button found on the Option's page > Config tab, and then import that file into the Chrome version.

Some related notes:
- This issue looks to be related to (#164), which was addressed in version [2.3.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.3.0)
- Currently Opera is only on version [2.1.6](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.1.6)
- The current version of the extension is [2.32.1](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.32.1)

At this point, I may just need to remove the extension from their store. I'll try reaching out again though and see if I can make any progress on getting updates released.

**Comment by richardfrost** [comment]
@JacobChild I was actually finally able to work with the Opera team and got the extension updated! Once you get updated to version 2.32.1 could you see if this issue still persists for you?

**Comment by JacobChild** [comment]
The update worked! Thanks so much!

**Comment by richardfrost** [comment]
You're welcome! Thanks for reporting the issue!
