### ISSUE TITLE
sync large settings error

### ISSUE THREAD

**Issue by Alex-Mirov** [richardfrost/AdvancedProfanityFilter#383]
Hello

When using windows 11 on firefox 97.0 (64 bit) with apf 2.32.1,
i'm getting this error when trying to select "sync large settings" 

Failed to update storage preference.
Error: Failed to save items: [domains, syncLargeKeys, words]. [QuotaExceededError: storage.sync API call exceeded its quota limitations.]

what is the limit for the sync and it will get larger in the future?

Thanks

**Comment by richardfrost** [comment]
The amount of sync-able storage is dictated by the browser, and is not something I can control. [Chrome](https://developer.chrome.com/docs/extensions/reference/storage/), [Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync).

Today, the standard that browsers have adopted seems to be `8192` bytes per item, with a maximum of `512` items. It might be possible to get a little more out of sync storage.

Now, on to what I can control. APF can split configs like words in multiple pieces, which is how it is able to handle storing quite a few (100+) words in sync storage. Right now there is a limit of 64 split items for large keys like `words`. That limit was a little conservative, and I could probably double that, at least for the words (which I'm assuming is the setting that is too large for you). If you want to share your config I'll take a look and see about increasing it.

**Comment by Alex-Mirov** [comment]
Hello

Here is the example config file that can produce this kind of error that i was mentioned above:
[APF Config File.txt](https://github.com/richardfrost/AdvancedProfanityFilter/files/8083364/APF.Config.File.txt)

Thanks

**Comment by richardfrost** [comment]
I just submitted version [2.32.2](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.32.2) which should address this issue. Thanks for reporting it. I'll leave this open until you've had a chance to test it and report back.

**Comment by richardfrost** [comment]
You're welcome! Thanks for reporting the issue @Alex-Mirov.
