### ISSUE TITLE
ITV UK Audio Muting Support

### ISSUE THREAD

**Issue by ahkelly** [richardfrost/AdvancedProfanityFilter#384]
I would like to open the conversation relating to audio muting of ITV UK. Unfortunately following the normal directions I cannot find the subtitles in the elements. 

![itv-find-no-results](https://user-images.githubusercontent.com/7065207/154613900-88dd6b39-dfef-4478-8572-9cf6ab383d5d.png)

Following `3. Video TextTrack Mode `  it does actually return the subtitles and below are the results. Hoping you can give some further guidance on what else I can try to get you the actual elements

![itv-text-to-find](https://user-images.githubusercontent.com/7065207/154613830-63188995-5264-4ab9-b147-0b8729864e27.png)

**Comment by richardfrost** [comment]
It looks like this site is using the Video TextTrack based on what you discovered, so there aren't traditional elements to filter like the other sites.

Did you try to test the possible config output by the script you ran? (bottom of last screenshot). If you'd like to keep the other sites active as well, you can do so like this:

```json
{
  "www.channel4.com": [
    {
      "displaySelector": "div.subtitles-container",
      "mode": "elementChild",
      "parentSelector": "div.subtitles-container",
      "tagName": "SPAN"
    }
  ],

  "www.itv.com": [
    {
      "mode": "cue",
      "language": "en"
    }
  ]
}
```

**Comment by richardfrost** [comment]
That's great! I just noticed that script was a little out of date, so I've updated it on the page. For the rule, you'd really want it to be `videoCueLanguage` instead of `language`, like this:

```js
  "www.itv.com": [
    {
      "mode": "cue",
      "videoCueLanguage": "en"
    }
  ]
```

**Comment by ahkelly** [comment]
I am yet to have any issues with this, all is working great.

**Comment by richardfrost** [comment]
That is awesome news! I'll make sure to get it added in the next version. Thanks for all your help in supporting these. Feel free to suggest another if one comes up.

**Comment by richardfrost** [comment]
I just submitted version [2.32.2](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.32.2) which now includes this config.  You should be able to remove it from the custom sites if you'd like. I generally recommend using the rules included with the filter, just in case an update happens to the rule or the filter itself.
