### ISSUE TITLE
sbs.com.au audio muting

### ISSUE THREAD

**Issue by ahkelly** [richardfrost/AdvancedProfanityFilter#388]
#### SBS Australia Audio Muting

Captions are present in the following element.

```html
<div class="bmpui-container-wrapper">
  <span id="bmpui-id-106" class="bmpui-ui-subtitle-label" style="position: absolute; overflow-wrap: break-word; overflow: hidden; flex-flow: column; display: inline-flex; writing-mode: horizontal-tb; bottom: 0px; text-align: center; width: 100%; left: 0px;">
    <span>I'm going to pee my pants! Dad, Petey needs the loo.</span>
  </span>
</div>
```

Without any custom audio site definition added profanity is filtered in the caption but no audio mute. Would be great to add this to the growing supported list. I would be happy to continue to test this site for you if you have any suggestion.

Many Thanks,
Andrew

**Comment by richardfrost** [comment]
Assuming that is the `node` ([guide](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Custom-Audio-Muting-Site#2-elementtext-mode)), the I would recommend this rule:

```json
{
  "sbs.com.au": [
    {
      "className": "bmpui-container-wrapper",
      "mode": "element",
      "subtitleSelector": "SPAN.bmpui-ui-subtitle-label > SPAN",
      "tagName": "DIV"
    }
  ]
}
```

**Comment by ahkelly** [comment]
OK, So I sent you the element using Guide 1. Identify Mode

Below is results from using 2. Element/Text Mode

```
<div id="bmpui-id-93" class="bmpui-subtitle-region-container bmpui-subtitle-position-vtt" style="position: static;">
	<div class="bmpui-container-wrapper">
		<span id="bmpui-id-92" class="bmpui-ui-subtitle-label" style="position: absolute; overflow-wrap: break-word; 			overflow: hidden; flex-flow: column; display: inline-flex; writing-mode: horizontal-tb; bottom: 0px; text-			align: center; width: 100%; left: 0px;">
			<span>Can you hold it?</span>
		</span>
	</div>
</div>
```
screenshot of scene and console below
![sbs-element-node-result](https://user-images.githubusercontent.com/7065207/155448871-40e9b21a-7012-4afc-bec7-fd7efccb89b5.png)

I also tried 3. Video TextTrack Mode and got no results

Here are my current settings with the custom setting you offered. 

![sbs-audio-settings](https://user-images.githubusercontent.com/7065207/155449284-611d3842-b0e3-4c91-9f52-d7296316b003.png)

It still does not mute the audio on filtered words. The caption text continues to be filtered. However without any custom settings at all the words are filtered curiously.
![sbs-caption-filter-no-mute](https://user-images.githubusercontent.com/7065207/155449190-3d0eee26-c5c9-46fe-beda-47ef94917f6c.png)

**Comment by richardfrost** [comment]
Thanks so much for those additional details @ahkelly. Can you try this?

```json
{
  "sbs.com.au": [
    {
      "className": "bmpui-subtitle-region-container",
      "mode": "element",
      "subtitleSelector": "SPAN.bmpui-container-wrapper > SPAN.bmpui-ui-subtitle-label > SPAN",
      "tagName": "DIV"
    }
  ]
}
```

**Comment by ahkelly** [comment]
Thank you for the follow up suggestion. Unfortunately still no audio mute. Caption filter is working fine though, I even tested again by adding words and they get filtered perfectly in the captions (only unfortunately).

**Comment by richardfrost** [comment]
Sorry! I had a typo in there. Could you test this:

```json
{
  "sbs.com.au": [
    {
      "className": "bmpui-subtitle-region-container",
      "mode": "element",
      "subtitleSelector": "DIV.bmpui-container-wrapper > SPAN.bmpui-ui-subtitle-label > SPAN",
      "tagName": "DIV"
    }
  ]
}
```

**Comment by ahkelly** [comment]
Sorry, still no audio mute. This is an odd site, I am actually using Brave browser (chrome based) as it has ad blocker built in but I usually disable it on streaming sites otherwise they complain. Strange thing is on the sbs website it complains when I have it turned off that I am using an adblocker so it throws an error. I have to enable the ad blocker then I have no problem, hope that doesn't have any bearing on the audio not working.

**Comment by richardfrost** [comment]
Hmmm, yeah, this one does seem quite stubborn. Are you testing in the same spot as you got the `node` from in step 2?

Here is a variation that is a little less specific that might work?

```json
{
  "sbs.com.au": [
    {
      "className": "bmpui-subtitle-region-container",
      "iframe": true,
      "mode": "element",
      "subtitleSelector": "SPAN.bmpui-ui-subtitle-label > SPAN",
      "tagName": "DIV"
    }
  ]
}
```

**Comment by richardfrost** [comment]
Can you double-check that the extension is even detecting this as an audio-supported site? Just click on the extension icon and you should see this in the popup:

![image](https://user-images.githubusercontent.com/1507205/155636066-38b294a4-6b9d-4db3-96ed-9693db136571.png)

**Comment by ahkelly** [comment]
OK,
So that is definitely an issue. No it is not showing as an audio supported site. This menu only shows the first 3 (Mode, Filter, Text). Anything setting I can change to alter the detection of audio?

**Comment by ahkelly** [comment]
Also thanks very much for your contributions to the community with this extension. I just noticed your donate button so sent a $10 donation.

**Comment by richardfrost** [comment]
Okay, I think it might need the `www` in front of it. Can you try this one?

```json
{
  "www.sbs.com.au": [
    {
      "className": "bmpui-subtitle-region-container",
      "mode": "element",
      "subtitleSelector": "DIV.bmpui-container-wrapper > SPAN.bmpui-ui-subtitle-label > SPAN",
      "tagName": "DIV"
    }
  ]
}
```

**Comment by richardfrost** [comment]
And thanks for the donation @ahkelly, as well as your suggestions and willingness to help out by adding support for these new sites!

**Comment by ahkelly** [comment]
Nice one, so that did the trick (www). Audio muting is now working! The supported site list can now grow by another one, using the exact json as you have it above. 
Thanks again!

**Comment by richardfrost** [comment]
@ahkelly Awesome, thanks for all your help! I'll get this added to the next version.

**Comment by richardfrost** [comment]
This was added in version [2.33.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.33.0). Thanks again for your help.
