### ISSUE TITLE
Domain list doesn't expect domain "localhost"

### ISSUE THREAD

**Issue by uthbees** [richardfrost/AdvancedProfanityFilter#390]
#### :bug: Description
When you have at least two domains disabled with one of them "localhost", you start to get errors in red popping up. (I've been ignoring these for a while now, but it looks like they actually do cause some bugs, like not being able to toggle substituted word marking, so I finally went ahead and took the time to find the problem.)

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Restore your config to the default settings
2. Replace `"domains": {},` with `"domains": {"en.wikipedia.org": {"disabled": true},"localhost": {"disabled": true}},`
3. Press the Import button
4. Observe the giant red box saying "Failed to import settings. Error: b.match(...) is null".

#### :heavy_check_mark: Expected behavior
Domain list should expect and allow for the presence of domains such as "localhost"

#### :computer: Details
 - **Device:** Dell XPS 17 9700
 - **OS:** Windows 10
 - **Browser:** Firefox 97.0.2

#### :pencil: Additional context
The wordlist and some settings still seem to save fine when this bug is active, although they still say something about the save failing.

I think this was my problem when I was testing the solution to #361.

**Comment by richardfrost** [comment]
Thanks for reporting and tracking down the issue. I actually had another user report a very similar bug. I'll get a bug fix release out tomorrow.

**Comment by richardfrost** [comment]
This should be fixed in version [2.33.2](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.33.2). Once you've updated to it let me know if it fixes the issue for you. Thanks!

**Comment by uthbees** [comment]
Looks good to me! Thanks for the quick fix!

**Comment by richardfrost** [comment]
You're welcome @uthbees! Thanks for letting me know it worked for you.
