### ISSUE TITLE
Marking substituted words fails with regex backreferencing

### ISSUE THREAD

**Issue by uthbees** [richardfrost/AdvancedProfanityFilter#391]
#### :bug: Description
Words that use the regex match method and include a backreference will not be marked with [ ], even when that setting is enabled.

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Enable Filter Method: Substitute, then enable Mark substituted words with [ ]
2. Create a new word using the regex match method, with the word/phrase as `(a)` and the substitution as `you typed: \1`
3. Type `a` into the test field
4. Notice that it's not marked with [ ]. You can also test some regular words in your word list to make sure that they're getting marked as normal.

#### :heavy_check_mark: Expected behavior
In my example, I would expect to get `[you typed: a]`.

#### :computer: Details
 - **Device:** XPS 17 9700
 - **OS:** Windows 10
 - **Browser:** Firefox
 - **Browser Version:** 97.0.2
 
#### :pencil: Additional context
I recognize that this exception may be intentional rather than oversight. If that is the case (or if it's too much trouble to fix such a tiny bug), I propose that the exception be documented somewhere - probably on the help page/wiki.

**Comment by richardfrost** [comment]
Thanks for reporting the bug. It looks like it was mostly an oversight. I'll try to have a fix out tomorrow.

**Comment by richardfrost** [comment]
This should be fixed in [version 2.33.3](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.33.3). Let me know if it works for you once you get the update.

**Comment by uthbees** [comment]
Looks good to me!

**Comment by richardfrost** [comment]
@uthbees Awesome, thanks for testing it out and reporting back here.
