### ISSUE TITLE
BBC Iplayer

### ISSUE THREAD

**Issue by 101w2in** [richardfrost/AdvancedProfanityFilter#397]
Hi,

BBC iPlayer seems to have updated its video player, and the code I was using to add it as a custom site is no longer working. I was using the code below? Can anyone suggest an update? Or another reason why its stopped working?

```json
{
  "www.bbc.co.uk": [
    {
      "mode": "element",
      "subtitleSelector": "div.p_cueDirUniWrapper span",
      "tagName": "div"
    }
  ]
}
```

**Comment by richardfrost** [comment]
Thanks for reporting the issue. I don't have access to BBC iPlayer right now, but maybe we could get someone with access that helped out with the original support for BBC (#336).

@ahkelly @lukefarr Have you run into any issues with the filter and BBC IPlayer?

**Comment by lukefarr** [comment]
Hiya

Yes i too have issues. It is filtering the text of the subtitle but not the
audio. This is my current custom config:

{
  "www.amazon.co.uk": [
    {
      "displayHide": "none",
      "displaySelector": "div.webPlayerContainer div.f35bt6a",
      "displayShow": "",
      "iframe": false,
      "mode": "watcher",
      "parentSelector": "div.webPlayerContainer div span > span",
      "videoSelector": "div.webPlayerElement video[src]"
    }
  ],
  "www.bbc.co.uk": [
    {
      "mode": "element",
      "subtitleSelector": "div.p_cueDirUniWrapper span",
      "tagName": "div"
    }
  ]
}

**Comment by richardfrost** [comment]
Thanks for reporting back @lukefarr. That is the last known working config, so I think they probably made a change to their site. Last time around @ahkelly was able to help gather the necessary info to create the filter. Maybe they can help us out again. If not, I am pretty swamped this week, but next week I will try to get access to take a look around.

**Comment by ahkelly** [comment]
Hi Richard,
Sorry for late reply on this. I just checked and yes the filtering is no longer working on bbc iplayer so I would say remove it from your supported sites until we figure out the changes. It appears the underlying code has changed quite a bit and they are now using web components. As a result I am unable to copy and paste the shadow dom but instead have taken some screenshots that may be helpful.

1. The js path to the subtitles is below
`document.querySelector("#toucan-bbcMediaPlayer0").shadowRoot.querySelector("smp-video-layout").shadowRoot.querySelector("div > smp-subtitles")`
2. A screenshot of the element where the subtitles is rendered is below

![shadow-root-bbc](https://user-images.githubusercontent.com/7065207/163094863-8e0de7df-7909-457d-98ea-e47ccf2f8a16.png)

3. A screenshot of the accompanying video used to find the subtitle element

![bbc-split-screenshot](https://user-images.githubusercontent.com/7065207/163094902-c2a8140a-ab48-4e1e-95b4-ff10a6f8ba9f.png)

Let me know any other clues I can pass on!

Regards,
Andrew

**Comment by richardfrost** [comment]
Thanks for the details @ahkelly, that really helps! Sorry its taken me so long to get back to you. I have been swamped with work and getting the filter released on the Apple App Store.

Yes, I think you are correct, they really did change it quite a bit. I'll try to get it removed from the next release if we haven't figured out an updated solution by then.

For the filter to work with web components like this it will likely require the filter to run in "Deep" mode. This can be changed from the popup menu while browsing the BBC iView page.

![image](https://user-images.githubusercontent.com/1507205/164990560-5cca39d2-6c23-4d79-8236-02e1cc24730c.png)

Once you have advanced mode turned on, you should be able to follow the steps outlined [here](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Audio-Muting:-Adding-a-Custom-Site#2-elementtext-mode)

If you can get me the `node` output again we should be able to get a working config out of it. I'll look into seeing if I can make some adjustments to allow the audio site config to set the filter mode so that could be taken care of as well.

Let me know if you have any other questions or run into trouble. Thanks again for your help!

**Comment by ahkelly** [comment]
So, I had trouble getting the Element/Text mode to work for some reason but tried again today and got the following result

`<div style="position: relative; width: 877px; height: 493px; margin: auto; inset: 0px; z-index: 0;">
    <div
        lang="en-GB"
        style="
            position: absolute;
            margin: 0px;
            display: flex;
            flex-direction: column;
            justify-content: flex-end;
            height: 77.1644px;
            width: 658.294px;
            opacity: 1;
            top: 391.186px;
            left: 105.24px;
            overflow: visible;
            padding: 0px;
            visibility: visible;
            writing-mode: horizontal-tb;
            z-index: auto;
        "
    >
        <div style="margin: 0px; visibility: visible;">
            <div style="margin: 0px; visibility: visible;">
                <p
                    style="
                        margin: 0px;
                        direction: ltr;
                        font-family: ReithSans, Arial, Roboto, Helvetica, 'Liberation Sans', sans-serif;
                        font-size: 20.6444px;
                        font-style: normal;
                        font-weight: normal;
                        line-height: 24.7733px;
                        text-align: center;
                        unicode-bidi: normal;
                        visibility: visible;
                        padding-left: 0px;
                        padding-right: 0px;
                        position: relative;
                        bottom: 0px;
                        left: 0px;
                    "
                >
                    <span
                        style="
                            margin: 0px;
                            color: rgb(0, 255, 0);
                            direction: ltr;
                            font-family: ReithSans, Arial, Roboto, Helvetica, 'Liberation Sans', sans-serif;
                            font-size: 20.6444px;
                            font-style: normal;
                            font-weight: normal;
                            text-decoration: none;
                            text-combine-upright: none;
                            unicode-bidi: normal;
                            visibility: visible;
                            white-space: normal;
                        "
                    >
                        <span style="margin-left: -8px; padding-left: 8px; margin-right: -8px; padding-right: 8px; background-color: rgba(0, 0, 0, 0.6); padding-bottom: 0.203125px;">Did you take Liv to get the pill</span>
                    </span>
                    <br style="margin: 0px;" />
                    <span
                        style="
                            margin: 0px;
                            color: rgb(0, 255, 0);
                            direction: ltr;
                            font-family: ReithSans, Arial, Roboto, Helvetica, 'Liberation Sans', sans-serif;
                            font-size: 20.6444px;
                            font-style: normal;
                            font-weight: normal;
                            text-decoration: none;
                            text-combine-upright: none;
                            unicode-bidi: normal;
                            visibility: visible;
                            white-space: normal;
                        "
                    >
                        <span style="margin-left: -8px; padding: 0.5625px 8px 0.4375px; margin-right: -8px; background-color: rgba(0, 0, 0, 0.6);">this morning?</span>
                    </span>
                </p>
            </div>
        </div>
    </div>
</div>
`

**Comment by richardfrost** [comment]
Hmm, that doesn't give a lot to go off of unfortunately, and doesn't fit very well in the current methods available.

A quick way to get it working would be to add support for the `lang` property on the outermost DIV, but that gets messy if people use other languages, or if they aren't labelled consistently across all videos.

I think I might need to devise another method for this implementation. Thanks for those details. I think I have enough to start working on it.

**Comment by ahkelly** [comment]
Yes, I noticed all elements have inline styling and no id's or classes. Sorry about that, definitely a wholesale change from their previous version.

**Comment by richardfrost** [comment]
Yeah, its definitely completely different lol.

Okay I have a pre-alpha level build that I'd like you to try if you get a chance @ahkelly.

[extension-prerelease-watcher_shadowroot.zip](https://github.com/richardfrost/AdvancedProfanityFilter/files/8597839/extension-prerelease-watcher_shadowroot.zip)

If you use this custom audio config with it, I'm curious to know how it works:

```json
{
  "www.bbc.co.uk": [
    {
      "mode": "watcher",
      "subtitleSelector": "#toucan-bbcMediaPlayer0 >>> smp-video-layout >>> smp-subtitles >>> div[lang] p span span ",
      "displaySelector": "#toucan-bbcMediaPlayer0 >>> smp-video-layout >>> smp-subtitles >>> div",
      "iframe": false
    }
  ]
}
```

The watcher mode isn't quite as fast as the default `element`/`elementChild` that it was before. Hiding captions/subtitles typically doesn't work as well, though because they have it in a separate shadowRoot it might actually work okay here. Anyway, let me know if it works at all, and if so how well.

Let me know if you need any help with running it, or have any other questions. Thanks for your help!

**Comment by ahkelly** [comment]
Very nice, swift, progress! So I have enabled the updated extension and updated the following

1. Set Mode to Deep
2. Added the new bbc custom site definition

I can report that subtitle filtering now works! see below

![bbc-update-filter](https://user-images.githubusercontent.com/7065207/166130640-b6f5db16-a1e9-4aaf-8333-23c84efbf93e.PNG)

However no audio muting yet, my settings are unchanged form default extension install

![afp-mute-config](https://user-images.githubusercontent.com/7065207/166130694-a3d86e37-310e-4fc1-9c02-65fb759d3400.png)

**Comment by richardfrost** [comment]
@ahkelly thanks for testing it! Could you try changing it from deep to normal and see if it's the same results? I'm hoping with this new build that deep shouldn't be needed, but I'm still experimenting.

**Comment by ahkelly** [comment]
Sorry, I didn't mention that previously. I did already try that and only mode that works (with subtitle filtering) is Deep mode, Normal mode does no filtering at all (subtitle or audio). As both extensions (current release and this pre-release) show the same version I removed the release build to ensure I am using only this pre-release version fyi.

**Comment by richardfrost** [comment]
Okay, thanks for clarifying that. could you possibly share an other screenshot of the developer tools elements tab? Just want to make sure I'm not missing anything. I set that up with the JS path you shared, but maybe I made a mistake on it. If its possible to show the full hierarchy in a screenshot that might help.

I will work on getting a new build that has some debug logging that will hopefully help us identify where its breaking.

**Comment by ahkelly** [comment]
Here is a better screenshot of the elements all the way up to main outer element. It is is 2 screenshots

![elements-01](https://user-images.githubusercontent.com/7065207/166152940-d4e4b03d-12de-4ddc-bf96-82e5f7d70edb.png)

![elements-02](https://user-images.githubusercontent.com/7065207/166152953-51e8035e-da00-4c03-bb31-0d858f807ae9.png)

Also I may have misled you a little on the element path as it appears the subtitles are split in 2 spans as shown in the screenshots. The JS path for each is

`document.querySelector("#toucan-bbcMediaPlayer0").shadowRoot.querySelector("smp-video-layout").shadowRoot.querySelector("div > smp-subtitles").shadowRoot.querySelector("div > div > div > div > div > p > span:nth-child(1)")`

and

`document.querySelector("#toucan-bbcMediaPlayer0").shadowRoot.querySelector("smp-video-layout").shadowRoot.querySelector("div > smp-subtitles").shadowRoot.querySelector("div > div > div > div > div > p > span:nth-child(3) > span")`

**Comment by richardfrost** [comment]
Here is a new build with some fixes, but its still a very early release and subject to change: [extension-mv3.zip](https://github.com/richardfrost/AdvancedProfanityFilter/files/8629085/extension-mv3.zip).

Aside from a couple bugs that I found in this, I realized I was missing a piece of information for the config. I need to know where the `<video>` element is. Below I'm just guessing that it could be inside `<smp-video-layout>`, which is one level up from where the captions are, but that's a total guess, and could definitely be wrong. If you could go to the "Elements" tab in DevTools and search  (CTRL+F) for `<video`, you'll probably be able to find it quickly. If you can get me a screenshot and/or the path for it I think we can get this working.

```json
{
  "www.bbc.co.uk": [
    {
      "displaySelector": "smp-toucan-player >>> smp-video-layout >>> smp-subtitles >>> div",
      "iframe": false,
      "mode": "watcher",
      "subtitleSelector": "smp-toucan-player >>> smp-video-layout >>> smp-subtitles >>> div[lang] p span span",
      "videoSelector": "smp-toucan-player >>> smp-video-layout >>> video"
    }
  ]
}
```

Thanks for your help and patience on this one.

**Comment by ahkelly** [comment]
Awesome, thanks for the follow up. So I can report little change

1. Words are still filtered only when I select Deep mode (Normal mode filters nothing)
2. Audio mute is still not working

It looks to me like the video tag is inside `<smp-playback>` element. See screenshot below

![video-element](https://user-images.githubusercontent.com/7065207/167039508-08a597dd-cb3c-4c6f-953f-f13ef9fe6b1f.PNG)

**Comment by richardfrost** [comment]
Awesome, can you give this a try (without deep mode enabled):

```json
{
  "www.bbc.co.uk": [
    {
      "displaySelector": "smp-toucan-player >>> smp-video-layout >>> smp-subtitles >>> div",
      "iframe": false,
      "mode": "watcher",
      "subtitleSelector": "smp-toucan-player >>> smp-video-layout >>> smp-subtitles >>> div[lang] p span span",
      "videoSelector": "smp-toucan-player >>> smp-playback >>> video"
    }
  ]
}
```

**Comment by ahkelly** [comment]
That nailed it!!

Word filtering and audio muting is now working again on the new bbc iplayer, using Normal mode! 

I read an article on how long they have been working on this new player (bbc) so hopefully no changes anytime soon.

![working-setting-1](https://user-images.githubusercontent.com/7065207/167042512-1e4b8411-122e-4ba0-b72c-9c7fea4edeb0.png)

![working-setting-2](https://user-images.githubusercontent.com/7065207/167042542-8068135d-5b37-4767-ab79-fd2b80031aef.png)

Once again, thanks a bunch for this.

**Comment by richardfrost** [comment]
[Version 1.35.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.35.0) has been released and should include the config for this now. Once you get the update, can you comment on how it works for you @ahkelly @101w2in? Thanks!

Also, @ahkelly you shouldn't need to have the config in your "Custom sites" (if you had it anywhere but your test build of the extension).

**Comment by ahkelly** [comment]
Hi @richardfrost I have just tested 2.35.0 in Chrome and can confirm it indeed works 100% as expected on the new BBC iplayer with word filtering and audio muting with default unmodified extension install. I also removed the test build before installing this new extension.

Thanks again for all your hard work!

**Comment by richardfrost** [comment]
That's excellent news it works without any customizations too! Thanks @ahkelly so much for reporting back, and all the legwork you did on this one. You definitely made things much easier on me to get this working.  I really wanted to avoid requiring Deep mode, so I'm glad it worked.
