### ISSUE TITLE
Doesn't work on discord

### ISSUE THREAD

**Issue by Abuda1** [richardfrost/AdvancedProfanityFilter#398]
#### :bug: Description
This chrome-extension completely doesn't work on the web version of discord

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Go to 'discord.com/app'
2. Login
3. Go to a channel/server

#### :heavy_check_mark: Expected behavior
Filtering should work on discord's web version

#### :computer: Details
 - **Device:** PC
 - **OS:** Windows 11
 - **Browser:** Edge Chromium
 - **Affected site(s):** discord.com/app

**Comment by richardfrost** [comment]
Sorry that its not working for you @Abuda1. I just tested it and it seemed to work just fine for me. Is the filter running on the page (not disabled for the domain, etc.)? Could you also try backup up your settings (If you've customized them) from the Options page > Config tab > Export button, and then on that same page click "Restore Defaults", then refresh the page on Discord and see if it works?

Another thing you could try is to add a word temporarily to the filter that is present on Discord. I just tested with adding the word `hello` to the filter, and then refreshed the page and it was filtered on Discord.

I feel pretty confident that it should work on the Discord webpage, so let me know how that goes and I'm hopeful we'll get it working for you too!

**Comment by Abuda1** [comment]
I tried all you mentioned, but nothing worked. I want to confirm, that I'm talking about the actual discord application, as a website rather than an installation.

**Comment by Abuda1** [comment]
I even tried it on google.com, and its not working

**Comment by richardfrost** [comment]
@Abuda1 Did you try resetting back to defaults in the extension's options page? Do you have any others extensions that might be interfering with it? I just tried a clean Edge install, installed the extension, and then went and did a Google search for "Google", and then added the word "google" to the filter. After a page refresh, google was removed from the page.

And yes, I was testing it on the Discord web app, and it does still work on my end as well.

**Comment by Abuda1** [comment]
> I just re-installed the extension and all is well.

**Comment by richardfrost** [comment]
@Abuda1 I'm glad it's working for you now! Sorry bi don't know what was wrong before. Did you install it from the Edge store, or the Chrome web store?

**Comment by Abuda1** [comment]
Chome I think

Sent from my Bell Samsung device over Canada’s largest network.
________________________________

**Comment by richardfrost** [comment]
Thanks for the info. I'll go ahead and close this issue now, but feel free to re-open it if the issue comes back. Take care!
