### ISSUE TITLE
Localhost domain "127.0.0.1" is not filtered

### ISSUE THREAD

**Issue by erspark2002** [richardfrost/AdvancedProfanityFilter#399]
_Instructions: This template is written in Markdown. Click the "Preview" tab to see what it will look like when submitted. Fill in the applicable sections (you can erase the examples if you'd like)._

#### :bug: Description
Adding domain "127.0.0.1" does not filter video running from a local webserver.

#### :twisted_rightwards_arrows: Steps To Reproduce
I added domain 127.0.0.1, ticked "Enabled", and selected:
Text Wordlist > Word list 1
Audio Wordlist > Word list 1
Running a local web server on port 80 using the html5 tag below, with the address: http://127.0.0.1/
The filter is enabled.
I have verified that certain words exist in the subtitles and have 
The video plays with subtitles, but the audio is never muted and keywords are not replaced.
Works fine for all other websites

```
    <video id="video" controls preload="metadata">
      <source src="video.mp4" type="video/mp4" />
      <track
        label="English"
        kind="subtitles"
        srclang="en"
        src="subtitles.vtt"
        default
      />
    </video>
```

**Comment by richardfrost** [comment]
I think I understand what you're doing, and this should work if you follow these steps (from a clean/default state):

1. Enable audio muting (Options page > Audio tab)
2. Add the following "Custom Sites" (Options page > Audio tab)
```json
{
  "127.0.0.1": {
    "mode": "cue"
  },
  "localhost": {
    "mode": "cue"
  }
}
```

Then, if you browse to that page at `http://localhost` or `http://127.0.0.1` it should work. Let me know how that works for you, and if you have any other questions.

**Comment by richardfrost** [comment]
@erspark2002 Did that work for you? Do you have any other questions?

**Comment by erspark2002** [comment]
Works perfectly. Cheers! (I was looking on the Domains tab for custom settings.)
Thankyou for making this plugin! 
![image](https://user-images.githubusercontent.com/6456779/165002925-248b0283-877d-4dd0-8a6a-113881e8a9e2.png)
