### ISSUE TITLE
Audio Muting for Stan.com.au

### ISSUE THREAD

**Issue by renae37** [richardfrost/AdvancedProfanityFilter#400]
_Instructions: This template is written in Markdown. Click the "Preview" tab to see what it will look like when submitted. Fill in the applicable sections (you can erase the examples if you'd like). For more information, please see [this page](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/New-Audio-Muting-Site)._

#### :movie_camera: The Site
www.stan.com.au
I have an issue with trying to add the stan.com.au website. I have gotten up to step 4 of Element/Text Mode but when I play the video a few seconds back until it reaches the word I included into the conditional breakpoint as soon as I hear the word I type into the console 'node' just like it said to but it comes up with an error saying Uncaught ReferenceError: node is not defined. I don't understand what I have done wrong. Please can you help me fix my error or potentially consider adding stan.com.au to the supported sites. I have tried multiple times to fix my error but I just can't find out what I've done wrong. Thank you!!!!!!!!!🙏🙏🙏
![Screen Shot 2022-04-15 at 9 23 55 pm](https://user-images.githubusercontent.com/103747212/163565232-e7190a4d-1330-42dc-8acd-34e88a8b13cd.png)

**Comment by richardfrost** [comment]
Sorry for the slow response @renae37, That is interesting. It looks like you've done everything right with it. I'll try to take a look at Stan and see if they have anything weird or out of the ordinary with it that might be messing up the process. Thanks again for reporting the issue. At one point Stan did work, and was a supported site, but they probably changed things that broke that functionality.

**Comment by Lhickox1** [comment]
This config works for me in chrome.
```json
 {
  "play.stan.com.au": [
    {
      "ignoreMutations": true,
      "mode": "elementChild",
      "parentSelector": "div.clpp-text-container",
      "simpleUnmute": true,
      "tagName": "DIV"
    }
  ]
}
```

**Comment by richardfrost** [comment]
@Lhickox1 Thanks for sharing a config that works for you here. I have a hard time getting into Stan (no account, and I'm based in the US), so I really appreciate the help. Could you try this config @renae37 and see how it works for you? I'm happy to update the internal config if they have made changes.

As @Lhickox1 points out, unfortunately the timing may not be perfect, and is really dependent on the timing of the captions/subtitles, but it will do the best it can.

**Comment by Lhickox1** [comment]
This one works on safari.

```json
{
  "play.stan.com.au": {
    "mode": "cue",
    "videoCueLanguage": "en",
    "videoCueSync": -0.6
  }
}
```
You can also change mute time with this one.

**Comment by richardfrost** [comment]
@Lhickox1 thanks for sharing that config as well!

I have a few questions:
- Does that work on the same video? Just wanting to confirm that the browser makes the difference and not the video that has different captions/subtitles.
- Did you test on iOS Safari, or the desktop (macOS), or both?

**Comment by Lhickox1** [comment]
Yes, it works on the same video. The same videos I tested with the chrome config I also used to test the iOS config. There is a difference between how the browsers display captions/subtitles. It could be that the captions/subtitles display differently between mobile and desktop browsers?

I tested it exclusively on iOS safari, not macOS. I dont know which config would work for maciOS.

**Comment by richardfrost** [comment]
Thanks for the update @Lhickox1! I'm working on introducing different audio site config based on the target browser/device, so this will probably be the first config to use that. Thanks again!

**Comment by richardfrost** [comment]
How confident are you @Lhickox1 with the `videoCueSync` timing? Does it seem pretty universal, or just on a movie or two? Just trying to decide if I should include it in the official config or not. Thanks!

**Comment by Lhickox1** [comment]
I went back and tested a few more movies and tv shows. It works with them as well. I just adjusted the sync timing in order to block bad words at the beginning of the caption/subtitles line, because it was not doing so before. The sync adjustment from my testing has not effected the muting of bad word at the middle or end of the captions/subtitles line. I dont know if other devices will act differently though. Its entirely up to you.

**Comment by richardfrost** [comment]
I included the config found by @Lhickox1 to the filter now. Can you confirm if its working for you @renae37?

I decided to leave off the `videoCueSync` timing adjustments since it could be different for certain videos or even vary by hardware.

Let me know if you have any other questions on this. Thanks!

**Comment by richardfrost** [comment]
I'm going to go ahead on close this now. If you do have more in put on this @renae37 feel free to respond here, or open a new issue. Thanks for your help @Lhickox1!

**Comment by renae37** [comment]
Sorry for the long delay in response, been very busy with uni! I have tried the updated version, it works on the captions I have found but I am still unsure as to whether or not it works on muting the audio because I did hear some words get through  but  then there were some instances where I did thought I did not hear the profanity being spoken but I wasn’t sure if that was just because the person in the movie spoke it quietly - this happened a few times which makes me think the audio can only really pick it up when it is not in the midst of other dialogue as it is easier to distinguish when it is spoken in isolation. Is there anything more we can do about this? Thanks!!

**Comment by Lhickox1** [comment]
Could you tell me the device you are watching it on and which config you are using?

**Comment by richardfrost** [comment]
@renae37 Could you share what an example video where this is happening for you? And possible a time as well? The filter only works based on the captions/subtitles, so if it is working correctly, if there is a phrase that includes a filtered word the audio will be completely muted while that phrase is present. It will not be able to typically filter just a single word, so based on what you described it sounds like it wasn't working at all, but if you could give an example that would definitely be helpful.

**Comment by renae37** [comment]
Thank you for the reply. The movie I was using with the filter was World War Z on Stan. The captions did actually filter out the bad words but the audio did not work. This was all throughout the movie that the audio did not work as I do not recall every hearing whole phrases muted.
Thanks.
Renae
