### ISSUE TITLE
Any way to add the site 9anime.se for audio muting?

### ISSUE THREAD

**Issue by richardfrost** [richardfrost/AdvancedProfanityFilter#402]
Any way to add the site 9anime.se for audio muting?

_Originally posted by @Lhickox1 in https://github.com/richardfrost/AdvancedProfanityFilter/discussions/310#discussioncomment-2606260_

**Comment by richardfrost** [comment]
Could you try adding this to your custom sites (Options page > Audio tab):

```json
{
  "9anime.se": [
    {
      "className": "jw-text-track-container",
      "mode": "element",
      "note": "see rule stream.opencdn.co",
      "subtitleSelector": "div.jw-text-track-cue",
      "tagName": "DIV"
    }
  ]
}
```

**Comment by Lhickox1** [comment]
Thank you so much! Works great. 
Sorry, I overlooked this page earlier.

**Comment by richardfrost** [comment]
You're welcome @Lhickox1, I'm glad its working for you! I've added it here to the [Additional Sites Config Page](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Audio-Muting:-Additional-Sites#additional-sites-config) for future reference.

I'll take a look at the Apple version in a bit.

**Comment by Lhickox1** [comment]
If it helps, I have noticed that in the apple extension when I enter the the 9anime.se JSON in the custom site box it always swaps (subtitleSelector : div.jw-text-track-cue) with (mode : element).

**Comment by richardfrost** [comment]
Thanks for the info. I had a few minutes last night to look at it, but unfortunately I'm running into an issue where the website is detecting that it is Safari, and then serving the subtitles differently than Chrome and Firefox. But unfortunately so far I haven't found a way to get the Safari devtools to open so I can see what's going on. I'll have to spend a bit more time with it, but that config unfortunately won't work with Safari.

**Comment by Lhickox1** [comment]
So I have been trying to find the location of the subtitles on 9anime.se in safari. I only have a ipad so I haven’t been able to use dev tools, that is until I found an app that lets me have dev tools on ipad. So I tried searching the same pathway as chrome and it is the same up until “iframe-embed” then it wont open no farther. 
![D8248BE7-5C22-4BF2-B39B-DF41385DBE1A](https://user-images.githubusercontent.com/104122226/165878257-66600a40-36b9-4f2d-a752-b76de1ea9d55.png)
But if you open the link in the “iframe-embed” and inspect that then this pathway is what I found. 
![2F8D96A8-B3E4-456D-914D-36FB7708E240](https://user-images.githubusercontent.com/104122226/165878443-a85dce7e-7d1f-4b67-8af8-61f219505270.png)
This is the only thing I have found that relates to subtitles. It may not help, but this is all I could find.

**Comment by richardfrost** [comment]
Thanks for the extra details! I haven't had much time to look at it yet,
but I should have time today or tomorrow and will hopefully have something
for you to test.

- Richard

**Comment by Lhickox1** [comment]
I found the subtitles. After opening the link in iframe embed in another window, because its the only way for me to inspect it farther, I found it in the network under eng-2.vtt.
![7CF2F4F1-CFA4-4C9F-9AC2-5C10C71F2B47](https://user-images.githubusercontent.com/104122226/166614945-02378cf7-acbd-4712-886c-8616129d1e67.png)
![37F5EF8E-1248-4E5F-9C9C-C7278F5EDBB5](https://user-images.githubusercontent.com/104122226/166614948-cedccdcd-75c2-457c-9a86-83cd74de2734.png)
However, I could not find it in the html. I am starting to wonder if it is even possible to get this to work on safari.

**Comment by richardfrost** [comment]
Thanks for getting it further. I'll try to take a look and let you know, but Its still in the realm of possibility to get it to work in Safari, so don't despair, hopefully we can get it!

**Comment by richardfrost** [comment]
@Lhickox1 How are you getting the developer tools/inspector on your iPad? I've typically connected it to a Mac running Safari, but unfortunately this site has a defense mechanism that won't allow me to inspect things.

**Comment by Lhickox1** [comment]
This safari extension app.
![4E451E6C-35F9-4481-906B-9B4084D24403](https://user-images.githubusercontent.com/104122226/166811353-feaeeac3-2fb0-48ed-bd09-81ad8204f3b0.png)
Its by far the best free option I have found.

**Comment by Lhickox1** [comment]
I have finally got the filter to halfway work on the site.

{
  "rapid-cloud.ru": {
    "mode": "cue",
    "videoCueLanguage": ""
  }
}

This will filter the subtitles, but it will not mute the audio.

**Comment by richardfrost** [comment]
WOW! Good work @Lhickox1! I'm sorry I've been so unresponsive on this issue. I've been really busy with a few other things, but you did great work with this! Do you have any questions, or anything outstanding on it?

**Comment by Lhickox1** [comment]
I have no more questions on this matter. However, I am curious to know how you got the config to look like that in my comments?

**Comment by richardfrost** [comment]
It's a feature of [Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax), specifically used for [formatting code](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code). To use it, you can open the code area with ` ``` ` (and optionally include a specific langauge, where I did `json` in your comment. Then you put your code, and finally close with another ` ``` `.

Example:

` ```json ` 
` {} `
` ``` `

Let me know if you have any other questions!

Thanks again for working through all of this. I've documented it [here](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Audio-Muting:-Additional-Sites#safari-ios).
