### ISSUE TITLE
Muting for Sling TV

### ISSUE THREAD

**Issue by richardfrost** [richardfrost/AdvancedProfanityFilter#403]
#### :movie_camera: The Site
watch.sling.com

#### :speech_balloon: Subtitle Element/Node
_Example:_
```html
<div class="bmpui-container-wrapper">
  <div id="bmpui-id-42" class="bmpui-subtitle-region-container bmpui-subtitle-position-default">
    <div class="bmpui-container-wrapper">
      <span id="bmpui-id-41" class="bmpui-ui-subtitle-label" style="left: 6.25%; top: 93.3333%; font-size: 79.7333px; letter-spacing: 65.7994px;">
        but we were trying to get
      </span>
    </div>
  </div>
</div>
```

#### :pencil: Additional notes
Requested on the Chrome Web Store Support section

**Comment by richardfrost** [comment]
I think this should work, if someone could try it out and let me know that would be great.

```json
{
  "watch.sling.com": [
    {
      "className": "bmpui-subtitle-region-container",
      "mode": "element",
      "subtitleSelector": "DIV.bmpui-container-wrapper > SPAN.bmpui-ui-subtitle-label",
      "tagName": "DIV"
    }
  ]
}
```

To use this, copy the above code to the Extension's Option page > Audio tab > Custom sites and then click the blue "Save" button underneath. After that, either refresh the related video tab (if you have one open), or open a new tab to the video site. Make sure captions are on and give it a test. 

**TIP:** _If you want to confirm the filter is working without the change of hearing an undesirable word, you can temporarily add a common word to the filter like "the", "dog", etc._

**Comment by Lhickox1** [comment]
I can confirm that it works on chrome. I did not test if it works with live tv, but it works for on demand. However, it is not an option for safari, because sling won’t stream on safari with current iOS 15. It will only play through the app on apple devices.

**Comment by richardfrost** [comment]
Thanks for confirming @Lhickox1.  I will get it added to the next version of the extension.

I'm sorry that it doesn't work in iOS Safari though. Unfortunately there isn't much that I can do about it if the service doesn't work in Safari though.
