### ISSUE TITLE
APF Bookmarklet not working on mobile. 

### ISSUE THREAD

**Issue by UserNamed0** [richardfrost/AdvancedProfanityFilter#414]
#### :bug: Description
APF Bookmarklet not working on mobile Chrome browser. 

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Go to any website
2. Tap on address bar
3. Type and select APF
4. No changes to the website

#### :heavy_check_mark: Expected behavior
Websites to be filtered. 

#### 📱: Details
 - **Device:** [Samsung Galaxy J3 2017 (SM-J330F)]
 - **OS:** [Android 9]
 - **Browser:** [Chrome]
 - **Browser Version:** [102.0.5005.78]
 - **Affected site(s):** [Any]

#### :pencil: Additional context
I really wish I could use Advanced Profanity Filter on my smartphone. I followed every step of the Bookmarklet Wiki but when I load a website and select APF on the address bar, nothing happens. Any help would be greatly appreciated. 
Best regards.

**Comment by richardfrost** [comment]
I'm sorry it isn't working for you. If you are trying your own bookmarklet, could you try using the one with the default config? I just tested it and it does seem to be working fine following the steps that you mentioned above. It would be helpful to know if it's an issue with the custom/personal version of the bookmarklet or the default one.

Since you are on Android, I would definitely recommend using a browser that supports actual extensions, such as [Kiwi](https://play.google.com/store/apps/details?id=com.kiwibrowser.browser) or [Firefox](https://github.com/richardfrost/AdvancedProfanityFilter/issues/243#issuecomment-726218625) if possible.

**Comment by UserNamed0** [comment]
I've tried using the bookmarklet with default config and it works, which means that something is wrong with my custom one but I don't know what could it be. I've also tried Firefox Android but it only allows me to install recommended add-ons and APF is not on the list.

**Comment by richardfrost** [comment]
For your personal bookmarklet, I'm betting it has to do with how it is hosted. Which hosting option did you choose? Also, if you could send me a link to the file you are hosting I would be happy to take a quick look at it.

For Firefox, its unfortunate that they removed the ability to install extensions that aren't recommended, but if you [follow the instructions here](https://github.com/richardfrost/AdvancedProfanityFilter/issues/243#issuecomment-726218625) you can get APF to work in Firefox Nightly on Android.

**Comment by UserNamed0** [comment]
I chose Google Drive, here is the link: https://drive.google.com/file/d/1E1t_tQbDtNTNfv9ifHTorpMSXFTiSF59/view?usp=sharing

That is what I did when trying on Firefox but still doesn't let me, it keeps saying that it's not compatible with Android.

**Comment by richardfrost** [comment]
It looks like Google Drive has changed the way their file hosting is working, and is now blocking the file from being downloadable for the bookmarklet. To fix it, can you try removing the `.js` from the file name in Google Drive and see if that works? If so, I'll make sure to update the instructions.

**Comment by UserNamed0** [comment]
That is not working either, I've even tried hosting a new file.

**Comment by richardfrost** [comment]
Did your new file have a file extension (`.js`)? Do you have a link to your new file you can share? Does it work on a desktop browser (you might need to temporarily disable the APF extension to see)?

Also, if you're still interested in Firefox Mobile (nightly), it does seem to still work. Did you go through the instructions above about creating the collection on AMO?

**Comment by UserNamed0** [comment]
Yes, but I removed it. I've tried with the file extension and without it. I tested it on desktop and it doesn't work. Here is the new link: https://drive.google.com/file/d/1BhKzufsOj7R4X9h0hWZMdc6fWPtyXPCX/view?usp=sharing

I went through all the instructions in Firefox Nightly, enabled general extension support through the debug menu, created a new collection on AMO and added APF in it, but when I try to install APF the button is grayed out and it shows a link to the add-ons compatible with Android. Below the install button there is an option called "Download file", I tap it and get an error "Nothing here/nothing to show". I don't remember exactly what the error says but it was something among those lines.

**Comment by richardfrost** [comment]
I'm sorry that the Firefox one isn't working. I'll try to test that out again from scratch later on, but maybe something changed so only an existing setup can work since I did it months ago. If  you would like, there is still Kiwi that you could try, or any other chromium-based browser for Android that supports extensions.

As for the bookmarklet, when I modify the link you shared to the one that is used by the bookmarklet: https://drive.google.com/uc?export=view&id=1BhKzufsOj7R4X9h0hWZMdc6fWPtyXPCX, I still get a warning message saying that it can't scan for viruses, which seems to be preventing it from actually being loaded. I was able to resolve that on my end by removing the ".js" from the end of the file before uploading it to Google Drive. Maybe you could try that again?

**Comment by UserNamed0** [comment]
It won't let me remove the ".js", not even from properties. The file extension is hidden and it's not allowing me to edit it. How can I do it?
![1](https://user-images.githubusercontent.com/106859188/172785069-5f41fc46-4672-4040-b553-8a4c2891972e.jpg)

**Comment by richardfrost** [comment]
Yeah, Windows may hide the extension by default. You should be able to edit the extension if you follow [these instructions](https://knowledge.autodesk.com/search-result/caas/sfdcarticles/sfdcarticles/How-to-enable-hidden-file-extensions-in-Windows.html).

**Comment by UserNamed0** [comment]
I am sorry, I was tired and I forgot I could do that. 

It works when I upload the bookmarklet to Google Drive without the file extension, but somehow it turns into the default config bookmarklet when I use it and I didn't upload that one.

**Comment by UserNamed0** [comment]
I don't want to keep taking up your time. I sincerely apologize for any inconvenience and thank you so much for creating this tool to help me stay more safe while browsing. I have been using it for around two years and I always wanted to thank you, now I have the opportunity. 

I will try Kiwi browser in case there isn't any way to fix custom config bookmarklets not working, or at least for me. If they work maybe there is something wrong with my file or it got corrupted for some reason. I could delete it, configure a new one from the beginning and tell you if it works.

**Comment by richardfrost** [comment]
Its no trouble at all. I am here to help and its one of my goals to make this project as useful as possible. The Bookmarklet is a feature that isn't used a lot, but I do want to have it work, so I appreciate you bringing this issue to my attention. I'm so glad you have been a long time user, and hope you'll continue in the future!

As for Kiwi, I've used it quite a bit and it seems to work really well for me, so hopefully it will for you as well.

After following up you're the issue you brought up, I found a bug and will be pushing a fix for it tonight or tomorrow morning, so hopefully when you get that it should work again. I'll let you know when its been uploaded.

**Comment by richardfrost** [comment]
[Version 2.36.2](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.36.2) has now been uploaded, and should hopefully be available soon. Once you've gotten the update, please try it again (remembering to remove the `.js` from the file name before uploading it to Google Drive) and let me know how it works for you.

**Comment by UserNamed0** [comment]
I updated it and now it's working perfectly, thank you so much for your time and help. 

Best regards.

**Comment by richardfrost** [comment]
You're very welcome @UserNamed0! Thanks for reporting the issue and for your patience in getting it fixed. Take care!
