### ISSUE TITLE
Disney+

### ISSUE THREAD

**Issue by hendrikbez** [richardfrost/AdvancedProfanityFilter#418]
Good day
Why does disney+ not working to take out the cursewords

**Comment by richardfrost** [comment]
Hi @hendrikbez,

Could you share some more details about what isn't working for you, and your situation?

- What country are you accessing from?
- What type of device are you using?
- What browser are you using?
- Is the muting working on other sites?
- Did you make sure the captions/subtitles are turned on?

I hope we can get to the bottom of this issue soon.

**Comment by hendrikbez** [comment]
Hi Richard

Sorry for replying now, but with all the power  of load shedding, my laptop is very slow, and I could not test disney+, at the moment I did get it to work on Brave and Firefox (YouTube videos) to take out the curse words.

1 South Africa
2 Laptop
3 Brave and Firefox
4 Did get it to work now, I think is is after the new release.
5. Yes it is working, must still test Disney+, will try it this week

Hendrik

**Comment by richardfrost** [comment]
@hendrikbez That's okay, thanks for letting me know. I've heard from a few other people that it should be working there in South Africa. But I'll keep this open a bit longer so you can have a chance to test it out. If it gets closed before you have a chance to test it, feel free to respond here still (even when its closed) and I'll still see it.

**Comment by hendrikbez** [comment]
Hi Richard

Thank you, I have tested it on Disney+ and it is working now.

**Comment by richardfrost** [comment]
@hendrikbez Thanks for reporting back. I'm glad its working for you now!
