### ISSUE TITLE
Disney+ Censors Subtitles, Does Not Mute Audio

### ISSUE THREAD

**Issue by PetrusV83** [richardfrost/AdvancedProfanityFilter#419]
_Instructions: This template is written in Markdown. Click the "Preview" tab to see what it will look like when submitted. Fill in the applicable sections (you can erase the examples if you'd like)._

#### :bug: Description
Currently the latest version seems to censor the words in the subtitles, however the audio still plays (not muted). Note that in my country the URL for Disney+ is "www.apps.disneyplus.com". I have added the following code to the custom code section which allowed the profanity extension in Firefox to work (before adding the custom code the extension was disabled and not able to turn on). It seems so far the many of Disney's English subtitles are English [CC]. Not sure if this has something to do with it. So yeah, seems to work in that it recognizes and removes the profanity from the subtitle sentences, but the audio part seems broken as it does not get muted. Hope this makes sense.

--- Code added to Custom Code
```json
{
  "www.disneyplus.com": {
    "mode": "cue",
    "videoSelector": "video.btm-media-client-element"
  }
}
```

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Go to 'Only Murders in the Building'
2. Click on 'Episode 8'
3. Scroll down to 'Profanity through out, towards end of episode'
4. See if audio still mutes

#### :heavy_check_mark: Expected behavior
Audio + Subtitles to be censored on Disney+

#### :computer: Details
 - PC
 - Win 10
 - Firefox
 - 102.0 (64-bit)
 - www.apps.disneyplus.com

#### :pencil: Additional context
My suspicion might be that I assume in the US the default URL is www.disneyplus.com, whereas outside of the US the URL might be www.apps.disneyplus.com. Possibly if the default code adds this URL to the Disney setup, maybe it will work.

**Comment by richardfrost** [comment]
Thanks for including all those details. Could you share which country/region you are trying to watch from? Which version of the extension do you have? I submitted [version 2.36.4](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.36.4) last night which should fix Disney+ for South Africa, which also uses [www.apps.disneyplus.com](http://www.apps.disneyplus.com/).

**Comment by PetrusV83** [comment]
Thanks Richard

Yip, from SA myself. I got ver 2.36.4 for Firefox. I see in the release
notes it says " - Audio muting for Disney+ South Africa".

I removed the custom code for disneyplus and it seems to work now! Amazing!

Thanks again for this awesome extension.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by PetrusV83** [comment]
Thanks Richard

Yip, from SA myself. I got ver 2.36.4 for Firefox. I see in the release notes it says " - Audio muting for Disney+ South Africa".

I removed the custom code for disneyplus and it seems to work now! Amazing!

Thanks again for this awesome extension.

**Comment by richardfrost** [comment]
You're welcome, Enjoy!
