### ISSUE TITLE
Raiplay 

### ISSUE THREAD

**Issue by Seby68** [richardfrost/AdvancedProfanityFilter#425]
_Instructions: This template is written in Markdown. Click the "Preview" tab to see what it will look like when submitted. Fill in the applicable sections (you can erase the examples if you'd like)._

#### :computer: Details
 - **Device:** [e.g. MacBook Pro, Google Pixel]
 - **OS:** [e.g. MacOS 10.14, Windows 10]
 - **Browser:** [e.g. Chrome, Firefox]
 - **Browser Version:** [e.g. 50]
 - **Affected site(s):** [e.g. www.google.com]

**Comment by Seby68** [comment]
Hi Richard, I contacted you to let you know that the rai no longer works. Since it is a GPL V3 program I have modified the files, Script, from the zip file, and uploaded it, but when I reload it, it does not change anything on the rai, it does not update it, it always gives me the one established by youCould you take a look on my email I sent you some screenshots. In addition, why, loading it from the zip file, modifying the rai does not change anything, have I modified three script files?

**Comment by Seby68** [comment]
Hi Richard, I contacted you to let you know that the rai no longer works. Since it is a GPL V3 program I have modified the files, Script, from the zip file, and uploaded it, but when I reload it, it does not change anything on the rai, it does not update it, it always gives me the one established by youCould you take a look on my email I sent you some screenshots. In addition, why, loading it from the zip file, modifying the rai does not change anything, have I modified three script files?

**Comment by richardfrost** [comment]
Sorry, I haven't had much time to work on the project the last few days. I'm not sure why it might not be updating for you. Did you follow the development steps outlined [here](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Development)? As long as you are modifying the `.ts` files, running `npm run build` and then pointing the browser to the `dist` folder, and then remembering to refresh the extension in your browser it should work.

**Comment by Seby68** [comment]
Yes Richard, thanks then I managed to change, all the files, and the raiplay appeared as modified by me and working, until the day before. I had solved this problem. Thanks for your commitment.

**Comment by Seby68** [comment]
Hi Richard, today or tomorrow, could you connect with me to fix the raiplay? Thanks.

**Comment by richardfrost** [comment]
This seems to be working now. I'll update the internal config in the extension with the next version.

```json
{
  "www.raiplay.it": [
    {
      "mode": "elementChild",
      "parentSelector": "div.theoplayer-texttracks div.theoplayer-webvtt-region-default",
      "subtitleSelector": "div span",
      "tagName": "DIV"
    }
  ]
}
```

**Comment by Seby68** [comment]
Il 06.08.2022 19:53 Richard Frost ha scritto: 

> This seems to be
working now. I'll update the internal config in the extension with the
next version. 
> 
> {
> "www.raiplay.it": [
> {
> "mode":
"elementChild",
> "parentSelector": "div.theoplayer-texttracks
div.theoplayer-webvtt-region-default",
> "subtitleSelector": "div
span",
> "tagName": "DIV"
> }
> ]
> }
> 
> -- 
> 
> Well, many thanks.
Very kind. I had tried it too, but was confined by your examples, that
the parentcontrols had to be found in the node.
> 
> Message ID:
@github.com>
  


Voucher MISE per P.IVA e PMI: fino a 2500€ per la Banda Ultralarga. https://casa.tiscali.it/promo/?u=https://promozioni.tiscali.it/voucher_business/?r=TS00000A00025&dm=link&p=tiscali&utm_source=tiscali&utm_medium=link&utm_campaign=voucherbusiness&wt_np=tiscali.link.footermail.voucherbusiness.btb..
