### ISSUE TITLE
Apple TV+ Not Muting Words

### ISSUE THREAD

**Issue by weidjoe** [richardfrost/AdvancedProfanityFilter#436]
_The audio on apple.tv+ is not muting curse words.
I followed instructions provided on #323 but nothing worked

There was no muting on any of the shows or movies provided through apple.tv+
```

**Comment by richardfrost** [comment]
@weidjoe thanks for reporting the issue. It looks like there has been a pretty big update to their site's underlying page structure. I've updated the status [here](https://apf.frostco.dev/status) and will update this issue when I have more to report.

**Comment by richardfrost** [comment]
This custom audio config should at least get muting working again:

```json
{
  "tv.apple.com": [
    {
      "mode": "elementChild",
      "parentSelector": "div.video-player div.video-container",
      "showSubtitles": 0,
      "subtitleSelector": ":scope div > div",
      "tagName": "DIV",
      "videoSelector": "div.video-player div.video-container video"
    }
  ]
}
```

Caveats:
1. Will only mute the first time seeing the captions/subtitles. If you want to re-watch part of the video with muting, you'll need to refresh the page.
2. Caption hiding isn't supported and might break filtering.

I will work to fix those remaining items, but wanted to share this in case someone wanted to use it now.

**Comment by richardfrost** [comment]
They have made updates to their site and [broken muting](https://github.com/FrostCo/AdvancedProfanityFilter/issues/689). See the new config that should work below:

```json
{
  "tv.apple.com": [
    {
      "apfCaptions": true,
      "apfCaptionsSelector": "[data-testid='video-container']",
      "captionControlStyle": true,
      "displaySelector": "[data-testid='video-container'] > div > div",
      "mode": "watcher",
      "subtitleSelector": "[data-testid='video-container'] > div > div > div > div",
      "videoSelector": "[data-testid='video-container'] video"
    }
  ]
}
```

To use this config, paste it into the Custom Sites area (Options page > Audio tab) and click the blue "SAVE" button underneath it. Then, make sure to refresh the tab for the video site (if you have it open still) and it will load this new configuration.

For best results, make sure to remove any custom config used for testing like this once it has been included in the official update.
