### ISSUE TITLE
Why is there so much profanity online? Afraid your extention won't work next year. 

### ISSUE THREAD

**Issue by tonyram57** [richardfrost/AdvancedProfanityFilter#450]
I am worried with Chrome changing next year your extention won't work anymore. I need it to work. Just read two random articles and they contained profanity which was unexpected but your filter worked completely.

I hear Chrome is making changes in the new year. I know that Firefox is not affected but Firefox mobile does not work with your extensions. I am a bit worried.

**Comment by richardfrost** [comment]
Yes, there sure is a lot of it out there. With regards to the upcoming Chrome changes next year, are you referring to [Manifest V3](https://developer.chrome.com/blog/mv2-transition/)? If so, APF was updated to Manifest V3 for Chrome-based browsers with version [2.31.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.31.0) back in February, so there shouldn't be any loss in functionality next year.

As for Firefox Mobile, I just saw that you can now install any add-on with Firefox Mobile Beta by [following these steps](https://www.androidpolice.com/firefox-beta-107-android-install-any-browser-add-on/). I followed a similar guide to get it working on Firefox Mobile's Developer edition, but its nice that its finally making its way to beta, and hopefully soon it can even go to stable. If you get a chance to try it out let me know how it goes for you.

Let me know if you have any more questions or concerns with it, but I do hope that I've already prepared it for the upcoming changes.

**Comment by tonyram57** [comment]
Thanks great to know. I will play around with Firefox beta.

**Comment by tonyram57** [comment]
Also any updates on blocking profanity in images? Just yesterday I saw it twice and today three times on YouTube.

**Comment by richardfrost** [comment]
@tonyram57 Did you have a chance to try APF the Firefox beta? Just curious how it worked.

**Comment by tonyram57** [comment]
I tried but it's too confusing.
