### ISSUE TITLE
Paramountplus

### ISSUE THREAD

**Issue by Seby68** [richardfrost/AdvancedProfanityFilter#459]
Hi Richard, I hope you are well. I wanted to ask you a question, I subscribed to Paramount Plus and here in Italy, with the PC I can't see it in HD or full HD. Since you can use Advanced profanity filter only on the PC, do you know if it's a problem that you also have in America? Many thanks.

**Comment by richardfrost** [comment]
From what I can tell, they adjust the playback quality automatically based on your network connection (and possibly the load they are having at the time). I don't see anywhere that shows what the current quality is, or to adjust it.

[Reference](https://help.paramountplus.com/s/article/PD-Are-shows-available-in-HD-with-Paramount)

[Reference](https://help.paramountplus.com/s/article/PD-Which-video-and-audio-streaming-formats-are-supported-for-streaming-Paramount)
