### ISSUE TITLE
Netflix Problems

### ISSUE THREAD

**Issue by bdc0der** [richardfrost/AdvancedProfanityFilter#462]
Whenever I try to watch Netflix, the censoring is glitched. The word is censored for about 1/10 of a second but stops muting it so you can still hear the censored word. Additionally, after the extension has been censored twice, Netflix boots me out and gives me the linked error. Do you think there are any settings/extensions that might be causing this? On Windows 10 on chrome, I tried disabling my adblocker, but it didn't work. 

**_Helpful information:_** 

- macOS Monterey 12.6.1 + Windows 10
- Chrome + OperaGX (other browsers might be affected, not sure)
- Netflix
- Closed captions/text censoring - ✅works✅
- Audio muting - ❌doesn't work❌
- (It didn't work on macOS with Opera GX, and it didn't work on Windows 10 with chrome)
- The audio/text muting/censoring works fine on other websites

<img width="1398" alt="Screen Shot 2022-12-01 at 5 06 29 PM" src="https://user-images.githubusercontent.com/119639394/205191828-0d8dd18d-6f35-44f9-ba9d-babecec4a4be.png">

If you have no plans to try to fix this bug, or if it for some reason isn't possible at the moment, maybe you can suggest something I might be able to do in the meantime to help. Thanks for looking into this, this extension is very helpful.

**Comment by richardfrost** [comment]
I'm sorry its not working for you @bdc0der. I haven't seen that issue before, but I'm happy to help get to the bottom of it.

Could you share an export of your config so I can test it using the same settings? If not, could you still export a copy of your config, reset the extension back to the defaults, enable audio muting again, and then test? Its definitely possible some settings could be interfering with it.

Another thing that might be good to test is see if another extension might be interfering with it. Just to confirm, you reported that muting is working on other sites such as YouTube, right? One thing you can try is setting up another browser profile (without other extensions) and see if it works there.

Which country are you watching Netflix from?

Let me know if you have any questions or have any feedback.

**Comment by bdc0der** [comment]
Wow, thanks for the fast response. Yes, I can confirm it's working for other websites, I'm watching from Oregon. Here is the opera backup: https://file.io/Nd3bJwiS3zcU
The backup for chrome windows 10 I might be able to get shared tomorrow, I'm not sure, I'll respond again when I get the chance
I will try creating another chrome profile without extensions. Thanks for the help

**Comment by richardfrost** [comment]
You're welcome @bdc0der. Thanks for confirming those details, and sharing the config.

I just imported the config into a new Chrome profile. It looks like that config had filtering disabled on www.netflix.com (Domains tab), but once I removed it I tested it on a couple videos and they all worked for me as expected. That tells me it shouldn't be an issue with your settings in the extension, so its likely something else. I'd still like to see if you could test it with a new profile, just to see if it might be another extension that could be preventing it from working correctly.

**Comment by bdc0der** [comment]
Here is the link for the version I use on chrome on windows 10: https://file.io/l542t59oTax8 

(I wouldn't be surprised if a problem with the extension was a result of other extensions on OperaGX, I have like 10, but it would seem strange on chrome as the only other thing I use is uBlock origin and I have it whitelisted for Netflix) 

Would it be enough to simply whitelist an extension, or would I have to manually disable it altogether?

**Comment by bdc0der** [comment]
Ok, I tried reinstalling on a different brand-new browser with the default extension settings, and the audio muting still didn't work. **_Are there any browser-based features or something else you know of that might interfere with it?_** It could very well be an extension, but seeing that it still doesn't work even with no other extensions installed on a brand-new browser can make me think it's 1 of 2 things: 

1.  It's tough luck and just an isolated case with something that can't be fixed
2. It's a problem with a specific browser function.

Thanks for sticking with me and continuing to help me

**Comment by richardfrost** [comment]
Thanks for @bdc0der testing on a new profile, that shows its likely not an issue with a conflict between another extension.

On that new Chrome profile, while on Netflix with a video playing and captions enabled, do you see this?

![image](https://user-images.githubusercontent.com/1507205/205403307-c832d13a-3ae7-4751-898a-51694f5bcbf6.png)

You should either see the extension's badge be purple, which means its actively watching for captions, but hasn't found them yet, or green (as shown in the screenshot), which means it has found the captions. So, when the Netflix page loads it should be purple, but does it ever change to green while playing the video?

**Comment by bdc0der** [comment]
One thing I do notice (this has always been the case) is the sentence with the bad word will be in bold font instead of the regular font like the rest. Yes, when I first load Netflix it's purple and when it then finds the word it turns green.
I have 2 screenshots that elaborate on this

<img width="258" alt="Screen Shot 2022-12-02 at 4 43 22 PM" src="https://user-images.githubusercontent.com/119639394/205413722-41535e8c-5905-449a-a68d-277848c82446.png">
<img width="467" alt="Screen Shot 2022-12-02 at 4 45 22 PM" src="https://user-images.githubusercontent.com/119639394/205413843-38086210-ff17-492f-9d4f-fcf3f9f13fcb.png">

**Comment by richardfrost** [comment]
Interesting find @bdc0der. Could you pause the video when that happens, right-click on the caption text and choose "Inspect", and then send me a screenshot of the HTML element it shows there?

I'm assuming you've tested it on multiple videos, right? If not, could you try on an episode of Stranger Things and see if that works?

**Comment by bdc0der** [comment]
I have not tried it on multiple videos, I have mainly been testing it on a single video. Here is the screenshot
<img width="1440" alt="Screen Shot 2022-12-02 at 6 53 28 PM" src="https://user-images.githubusercontent.com/119639394/205419090-a0ad5684-48c7-4a90-a86b-ba1dd5e3f0ed.png">

**Comment by richardfrost** [comment]
Could I have you search in that "Inspector" tab (CTRL+F) for a phrase shown in the captions, like this:

![image](https://user-images.githubusercontent.com/1507205/205421080-ea9e9ff7-064e-4798-bf49-347048e903fa.png)

**Comment by bdc0der** [comment]
<img width="1440" alt="Screen Shot 2022-12-03 at 6 53 34 AM" src="https://user-images.githubusercontent.com/119639394/205446978-67f6e8fb-55d8-4731-be88-1e77a7efedea.png">
Are there other parts of the HTML editor I might wanna have open for you to look at besides just the raw code in the inspector area?

**Comment by richardfrost** [comment]
Not that I can think of right now, but that did help @bdc0der. Could you share which video and approximate timestamp you have been testing with? I want to see if I can replicate it here, and I have a couple ideas that I'd like to try.

**Comment by bdc0der** [comment]
Jim Gaffigan: Obsessed - 32:04

**Comment by richardfrost** [comment]
What version of Firefox were those screenshots taken with? When I go to ~38:00 (about where I found those captions), I'm seeing this:

![image](https://user-images.githubusercontent.com/1507205/205459588-59fdd84d-c7c2-48f1-ba18-1cc3df12e9e5.png)

Not sure why they are different, but one difference I see is on my, the captions have a `font-size:34px`, and yours has `font-size:1px`. Not sure if that makes a difference, but it is a differences. Muting for me is also working fine on both Firefox (107.0.1) and Chrome with  the settings you shared (once I enable the Netflix domain again, as mentioned above). I haven't seen anywhere on Netflix to make changes to the captions display, but maybe I just missed it? Do you know if you changed anything that could have changed it for your account?

**Comment by bdc0der** [comment]
Version 107.0.1 (64-bit)
The firefox version I installed is brand-new. I didn't go to the settings and enable or disable anything new. 
Firefox and APF are both on the newest-installed default versions. (Only thing I changed for APF was enabling "Mute audio on supported video sites ")

One thing I did find though that allows me to change caption settings is by going to [Netflix Account](https://www.netflix.com/YourAccount), clicking the profile I want, and scrolling down until I found "Subtitle Appearance"

These are my caption preferences:
<img width="752" alt="Screen Shot 2022-12-03 at 1 28 04 PM" src="https://user-images.githubusercontent.com/119639394/205462876-efc9a315-28eb-468b-b201-42e3055a636e.png">

**Comment by richardfrost** [comment]
Thanks for sending those subtitle settings over @bdc0der. I haven't been able to replicate it to reflect what you are seeing. I've tried changing the settings, and also reset to default. No matter what I have selected, it is still muting for me correctly.

Could you try resetting those Netflix subtitle options back to default and see if its still not working for you? Also, do you have any other Add-ons/extensions running aside from APF? Do you have anything that might be changing/applying styles on the page?

![image](https://user-images.githubusercontent.com/1507205/206084637-6318f9cb-026f-4fb9-bd80-0ff1c4d6d73c.png)

**Comment by bdc0der** [comment]
By god, I think that did it! I'll have to try on other browsers and stuff to make sure an extension isn't causing it, but I think at long last we finally found an answer to the problem! Thanks for your help.

**Comment by richardfrost** [comment]
That's great @bdc0der! Let me know how it goes with testing on other browsers now.

**Comment by richardfrost** [comment]
You're welcome @bdc0der. Thanks for helping to get to the bottom of the issue. Take care!
