### ISSUE TITLE
Replace based on part of speech

### ISSUE THREAD

**Issue by RebelKeithy** [richardfrost/AdvancedProfanityFilter#69]
I'm attempting to use this to filter text in such a way that you can't tell it's been changed. The problem is, some words need to be replaced differently based on what part of speech it is. For example 'f***ing' can be removed entirely when it is a adjective or adverb, but needs to be replaced when it is a verb. Could we have the ability to do that?

**Comment by richardfrost** [comment]
Closing for now - but will check the Eventually tag when I have some time.
