### ISSUE TITLE
Chrome/Facebook/Comment - keyboard inputs not accepted

### ISSUE THREAD

**Issue by BWMorlan** [richardfrost/AdvancedProfanityFilter#70]
Issues are used primarily to track bugs in the project. Feature requests can be submitted either as an issue or [here](https://goo.gl/forms/LTqFpJ0mCTsrgGgf2).

## Description

Right after I installed I tried to post a Comment to Facebook and the response to my keyboard inputs was to open other tabs, and other actions, but no text in the Comment block.

### Details (Bugs Only)

Chrome Version: Version 64.0.3282.186 (Official Build) (32-bit)
Extension Version: 1.0.8
Operating System: Windows 7
Site(s) Affected: Facebook

### Steps to reproduce (Bugs only)

1. Installed Extension
2. Open Facebook
3. Click Comment

**Comment by BWMorlan** [comment]
Of course, I just went back and tried again and this time the keyboard worked, so for now, this is not an issue.

Sorry.

**Comment by richardfrost** [comment]
No worries! I don't think this extension should be causing that, but if it happens again let me know. Good luck!
