### ISSUE TITLE
Arstechnica forums slow loading can view profanity.

### ISSUE THREAD

**Issue by tonyram57** [richardfrost/AdvancedProfanityFilter#77]
Sites that are slo loading can take several seconds or I have to cancel the load before the profane words censor.

**Comment by richardfrost** [comment]
Once you get the new update (`1.0.13`), I'd be interested in knowing if this is less of a problem?

**Comment by tonyram57** [comment]
Got the update website loads a bit faster.
Example here
https://arstechnica.com/civis/viewtopic.php?f=15&t=1331445
Five profanities all blocked.

**Comment by richardfrost** [comment]
Well I am glad it working better at least. On my computer when I open it I see the profanities blocked immediately, but my computer may be faster than the average. I'll happily take any improvement though. Thanks!
