### ISSUE TITLE
It won't filter new words added

### ISSUE THREAD

**Issue by nunyabeeswax7** [richardfrost/AdvancedProfanityFilter#78]
Issues are used primarily to track bugs in the project. Feature requests can be submitted either as an issue or [here](https://goo.gl/forms/LTqFpJ0mCTsrgGgf2).

### Details (Bugs Only)

Chrome Version:
Extension Version:
Operating System:
Site(s) Affected:

### Steps to reproduce (Bugs only)

1.
2.
3.
4.

**Comment by richardfrost** [comment]
I'm sorry that its not working. I'm wondering if somehow your settings got into a bad state. Could you respond with your current configuration? You should be able to get it from the extension's `Config` tab and pressing the export button.

Failing that, if you could document which words you added you could try clicking the `Restore Defaults` button on that same `Config` tab in the extensions settings. Let me know if you have any other questions, I' happy to help!

**Comment by nunyabeeswax7** [comment]
Here's my configuration.
{
  "censorCharacter": "*",
  "censorFixedLength": 0,
  "defaultSubstitutions": [
    "censored",
    "expletive",
    "filtered"
  ],
  "disabledDomains": [
    "www.bigfishgames.com"
  ],
  "filterMethod": 0,
  "filterSubstring": true,
  "globalMatchMethod": 0,
  "password": null,
  "preserveFirst": false,
  "preserveLast": false,
  "showCounter": true,
  "substitutionMark": true,
  "words": {
    " nigga": {
      "matchMethod": 0,
      "words": []
    },
    "$hit": {
      "matchMethod": 0,
      "words": []
    },
    "@ss": {
      "matchMethod": 0,
      "words": []
    },
    "ASSWIPE": {
      "matchMethod": 0,
      "words": []
    },
    "BIIIIITCH": {
      "matchMethod": 0,
      "words": []
    },
    "Bulls&it": {
      "matchMethod": 0,
      "words": []
    },
    "Bytch": {
      "matchMethod": 0,
      "words": []
    },
    "Bítch": {
      "matchMethod": 0,
      "words": []
    },
    "DANM": {
      "matchMethod": 0,
      "words": []
    },
    "FUUUUUCKIN": {
      "matchMethod": 0,
      "words": []
    },
    "Half-assed": {
      "matchMethod": 0,
      "words": []
    },
    "MO T H ER FU C K ER﻿": {
      "matchMethod": 0,
      "words": []
    },
    "Mothafaka": {
      "matchMethod": 0,
      "words": []
    },
    "S H I T﻿": {
      "matchMethod": 0,
      "words": []
    },
    "Shiiit": {
      "matchMethod": 0,
      "words": []
    },
    "a$$": {
      "matchMethod": 0,
      "words": []
    },
    "aass": {
      "matchMethod": 0,
      "words": []
    },
    "apeshit": {
      "matchMethod": 0,
      "words": []
    },
    "arsehole": {
      "matchMethod": 0,
      "words": []
    },
    "arseholes": {
      "matchMethod": 0,
      "words": []
    },
    "arsehole﻿": {
      "matchMethod": 0,
      "words": []
    },
    "ass": {
      "matchMethod": 0,
      "words": []
    },
    "ass hole": {
      "matchMethod": 0,
      "words": []
    },
    "ass-hole": {
      "matchMethod": 0,
      "words": []
    },
    "assed": {
      "matchMethod": 0,
      "words": []
    },
    "asses": {
      "matchMethod": 0,
      "words": []
    },
    "assezz ": {
      "matchMethod": 0,
      "words": []
    },
    "asshat": {
      "matchMethod": 0,
      "words": []
    },
    "asshole": {
      "matchMethod": 1,
      "words": [
        "butthole",
        "jerk"
      ]
    },
    "assholes": {
      "matchMethod": 0,
      "words": []
    },
    "asss": {
      "matchMethod": 0,
      "words": []
    },
    "b1tch": {
      "matchMethod": 0,
      "words": []
    },
    "ballsy": {
      "matchMethod": 0,
      "words": []
    },
    "bastard": {
      "matchMethod": 1,
      "words": [
        "imperfect",
        "impure"
      ]
    },
    "bastardise": {
      "matchMethod": 0,
      "words": []
    },
    "bastardised": {
      "matchMethod": 0,
      "words": []
    },
    "bastardises": {
      "matchMethod": 0,
      "words": []
    },
    "bastardize": {
      "matchMethod": 0,
      "words": []
    },
    "bastardized": {
      "matchMethod": 0,
      "words": []
    },
    "bastardizes": {
      "matchMethod": 0,
      "words": []
    },
    "bastardizing": {
      "matchMethod": 0,
      "words": []
    },
    "bastards": {
      "matchMethod": 0,
      "words": []
    },
    "basterd": {
      "matchMethod": 0,
      "words": []
    },
    "basterdising": {
      "matchMethod": 0,
      "words": []
    },
    "basterds": {
      "matchMethod": 0,
      "words": []
    },
    "bastered": {
      "matchMethod": 0,
      "words": []
    },
    "basturd": {
      "matchMethod": 0,
      "words": []
    },
    "batshit": {
      "matchMethod": 0,
      "words": []
    },
    "bbiittcchheezz": {
      "matchMethod": 0,
      "words": []
    },
    "bejeezus": {
      "matchMethod": 0,
      "words": []
    },
    "bejesus": {
      "matchMethod": 0,
      "words": []
    },
    "biatch": {
      "matchMethod": 0,
      "words": []
    },
    "biotch": {
      "matchMethod": 0,
      "words": []
    },
    "bitch": {
      "matchMethod": 1,
      "words": [
        "jerk"
      ]
    },
    "bitched": {
      "matchMethod": 0,
      "words": []
    },
    "bitches": {
      "matchMethod": 0,
      "words": []
    },
    "bitchier": {
      "matchMethod": 0,
      "words": []
    },
    "bitchiest": {
      "matchMethod": 0,
      "words": []
    },
    "bitchin": {
      "matchMethod": 0,
      "words": []
    },
    "bitchin'": {
      "matchMethod": 0,
      "words": []
    },
    "bitching": {
      "matchMethod": 0,
      "words": []
    },
    "bitchy": {
      "matchMethod": 0,
      "words": []
    },
    "bittchezz": {
      "matchMethod": 0,
      "words": []
    },
    "bltch": {
      "matchMethod": 0,
      "words": []
    },
    "bollocks": {
      "matchMethod": 0,
      "words": []
    },
    "bullsh!t": {
      "matchMethod": 0,
      "words": []
    },
    "bullsh*t": {
      "matchMethod": 0,
      "words": []
    },
    "bullshit": {
      "matchMethod": 0,
      "words": []
    },
    "bullshits": {
      "matchMethod": 0,
      "words": []
    },
    "bullshitter": {
      "matchMethod": 0,
      "words": []
    },
    "bullshitters": {
      "matchMethod": 0,
      "words": []
    },
    "bullshittin": {
      "matchMethod": 0,
      "words": []
    },
    "bullshittin'": {
      "matchMethod": 0,
      "words": []
    },
    "bullshitting": {
      "matchMethod": 0,
      "words": []
    },
    "celebitchy": {
      "matchMethod": 0,
      "words": []
    },
    "chrissake": {
      "matchMethod": 0,
      "words": []
    },
    "christ": {
      "matchMethod": 0,
      "words": []
    },
    "cock": {
      "matchMethod": 0,
      "words": []
    },
    "cocks": {
      "matchMethod": 0,
      "words": []
    },
    "cocksuck": {
      "matchMethod": 0,
      "words": []
    },
    "cum": {
      "matchMethod": 0,
      "words": []
    },
    "cunt": {
      "matchMethod": 1,
      "words": [
        "explative"
      ]
    },
    "cunts": {
      "matchMethod": 0,
      "words": []
    },
    "d1ck": {
      "matchMethod": 0,
      "words": []
    },
    "daaaaammmmn": {
      "matchMethod": 0,
      "words": []
    },
    "dafuq": {
      "matchMethod": 0,
      "words": []
    },
    "dammit": {
      "matchMethod": 0,
      "words": []
    },
    "damn": {
      "matchMethod": 1,
      "words": [
        "dang",
        "darn"
      ]
    },
    "damned": {
      "matchMethod": 0,
      "words": []
    },
    "damnit": {
      "matchMethod": 0,
      "words": []
    },
    "dick": {
      "matchMethod": 0,
      "words": []
    },
    "dickhead": {
      "matchMethod": 0,
      "words": []
    },
    "dickheads": {
      "matchMethod": 0,
      "words": []
    },
    "dickin": {
      "matchMethod": 0,
      "words": []
    },
    "dickin'": {
      "matchMethod": 0,
      "words": []
    },
    "dicking": {
      "matchMethod": 0,
      "words": []
    },
    "dicks": {
      "matchMethod": 0,
      "words": []
    },
    "dumbass": {
      "matchMethod": 0,
      "words": []
    },
    "dumbasses": {
      "matchMethod": 0,
      "words": []
    },
    "dumbasses﻿": {
      "matchMethod": 0,
      "words": []
    },
    "dyke": {
      "matchMethod": 0,
      "words": []
    },
    "faceass": {
      "matchMethod": 0,
      "words": []
    },
    "fag": {
      "matchMethod": 0,
      "words": []
    },
    "faggot": {
      "matchMethod": 0,
      "words": []
    },
    "faggots": {
      "matchMethod": 0,
      "words": []
    },
    "fags": {
      "matchMethod": 0,
      "words": []
    },
    "fatass": {
      "matchMethod": 0,
      "words": []
    },
    "fffuuuccckkk": {
      "matchMethod": 0,
      "words": []
    },
    "ffuucckkiinngg": {
      "matchMethod": 0,
      "words": []
    },
    "fu(king": {
      "matchMethod": 0,
      "words": []
    },
    "fuck": {
      "matchMethod": 1,
      "words": [
        "freak",
        "fudge"
      ]
    },
    "fucked": {
      "matchMethod": 0,
      "words": []
    },
    "fuckedintheass": {
      "matchMethod": 0,
      "words": []
    },
    "fucker": {
      "matchMethod": 0,
      "words": []
    },
    "fuckin": {
      "matchMethod": 0,
      "words": []
    },
    "fuckin'": {
      "matchMethod": 0,
      "words": []
    },
    "fucking": {
      "matchMethod": 0,
      "words": []
    },
    "fucks": {
      "matchMethod": 0,
      "words": []
    },
    "fuked": {
      "matchMethod": 0,
      "words": []
    },
    "fukin": {
      "matchMethod": 0,
      "words": []
    },
    "fuking": {
      "matchMethod": 0,
      "words": []
    },
    "fukkin": {
      "matchMethod": 0,
      "words": []
    },
    "furfag": {
      "matchMethod": 0,
      "words": []
    },
    "fuuuccck": {
      "matchMethod": 0,
      "words": []
    },
    "fuuuucckkk": {
      "matchMethod": 0,
      "words": []
    },
    "fuuuuuuck": {
      "matchMethod": 1,
      "words": []
    },
    "fuuuuuuuuuck﻿": {
      "matchMethod": 0,
      "words": []
    },
    "fûcker": {
      "matchMethod": 0,
      "words": []
    },
    "god dam": {
      "matchMethod": 0,
      "words": []
    },
    "godam": {
      "matchMethod": 0,
      "words": []
    },
    "godammit": {
      "matchMethod": 0,
      "words": []
    },
    "goddam": {
      "matchMethod": 0,
      "words": []
    },
    "goddamed": {
      "matchMethod": 0,
      "words": []
    },
    "goddamit": {
      "matchMethod": 0,
      "words": []
    },
    "goddammit": {
      "matchMethod": 0,
      "words": []
    },
    "goddamn": {
      "matchMethod": 0,
      "words": []
    },
    "goddamned": {
      "matchMethod": 0,
      "words": []
    },
    "goddamnit": {
      "matchMethod": 0,
      "words": []
    },
    "hardass": {
      "matchMethod": 0,
      "words": []
    },
    "headass": {
      "matchMethod": 0,
      "words": []
    },
    "hell": {
      "matchMethod": 0,
      "words": []
    },
    "helluva": {
      "matchMethod": 0,
      "words": []
    },
    "jackass": {
      "matchMethod": 0,
      "words": []
    },
    "jerk ass": {
      "matchMethod": 0,
      "words": []
    },
    "jerkass": {
      "matchMethod": 0,
      "words": []
    },
    "jesus": {
      "matchMethod": 0,
      "words": []
    },
    "jesus christ": {
      "matchMethod": 0,
      "words": []
    },
    "lame-ass": {
      "matchMethod": 0,
      "words": []
    },
    "motherf*cker": {
      "matchMethod": 0,
      "words": []
    },
    "motherfcking": {
      "matchMethod": 0,
      "words": []
    },
    "motherfucker": {
      "matchMethod": 0,
      "words": []
    },
    "motherfuckin": {
      "matchMethod": 0,
      "words": []
    },
    "motherfucking": {
      "matchMethod": 0,
      "words": []
    },
    "motherfuker": {
      "matchMethod": 0,
      "words": []
    },
    "nigga": {
      "matchMethod": 0,
      "words": []
    },
    "niggas": {
      "matchMethod": 0,
      "words": []
    },
    "nigger": {
      "matchMethod": 0,
      "words": []
    },
    "niggers": {
      "matchMethod": 0,
      "words": []
    },
    "piiiiiiisssssssssssed": {
      "matchMethod": 0,
      "words": []
    },
    "piss": {
      "matchMethod": 1,
      "words": [
        "pee"
      ]
    },
    "pissed": {
      "matchMethod": 0,
      "words": [
        "ticked"
      ]
    },
    "pisses": {
      "matchMethod": 0,
      "words": []
    },
    "pissin": {
      "matchMethod": 0,
      "words": []
    },
    "pissin'": {
      "matchMethod": 0,
      "words": []
    },
    "pissing": {
      "matchMethod": 0,
      "words": []
    },
    "pissy": {
      "matchMethod": 0,
      "words": []
    },
    "prick": {
      "matchMethod": 0,
      "words": []
    },
    "pricks": {
      "matchMethod": 0,
      "words": []
    },
    "pu$$y": {
      "matchMethod": 0,
      "words": []
    },
    "punkass": {
      "matchMethod": 0,
      "words": []
    },
    "pussy": {
      "matchMethod": 0,
      "words": []
    },
    "retard": {
      "matchMethod": 0,
      "words": []
    },
    "retarded": {
      "matchMethod": 1,
      "words": []
    },
    "retards": {
      "matchMethod": 1,
      "words": []
    },
    "sh!t": {
      "matchMethod": 0,
      "words": []
    },
    "shat": {
      "matchMethod": 0,
      "words": []
    },
    "shiit": {
      "matchMethod": 0,
      "words": []
    },
    "shiitt": {
      "matchMethod": 0,
      "words": []
    },
    "shit": {
      "matchMethod": 1,
      "words": [
        "crap",
        "crud",
        "poop"
      ]
    },
    "shits": {
      "matchMethod": 0,
      "words": []
    },
    "shitstorm": {
      "matchMethod": 0,
      "words": []
    },
    "shittier": {
      "matchMethod": 0,
      "words": []
    },
    "shittiest": {
      "matchMethod": 0,
      "words": []
    },
    "shittin": {
      "matchMethod": 0,
      "words": []
    },
    "shittin'": {
      "matchMethod": 0,
      "words": []
    },
    "shitting": {
      "matchMethod": 0,
      "words": []
    },
    "shitty": {
      "matchMethod": 0,
      "words": []
    },
    "skank": {
      "matchMethod": 0,
      "words": []
    },
    "slut": {
      "matchMethod": 1,
      "words": [
        "imperfect",
        "impure"
      ]
    },
    "smartass": {
      "matchMethod": 0,
      "words": []
    },
    "smartasses": {
      "matchMethod": 0,
      "words": []
    },
    "sshhiitt": {
      "matchMethod": 0,
      "words": []
    },
    "tits": {
      "matchMethod": 1,
      "words": [
        "explative"
      ]
    },
    "titty": {
      "matchMethod": 0,
      "words": []
    },
    "twat": {
      "matchMethod": 0,
      "words": []
    },
    "twats": {
      "matchMethod": 0,
      "words": []
    },
    "wanker": {
      "matchMethod": 0,
      "words": []
    },
    "wankers": {
      "matchMethod": 0,
      "words": []
    },
    "whore": {
      "matchMethod": 1,
      "words": [
        "harlot",
        "tramp"
      ]
    },
    "ᖴᑌᑕk": {
      "matchMethod": 0,
      "words": []
    },
    "ᗷitᑕᕼ": {
      "matchMethod": 0,
      "words": []
    },
    "ᴮᴵᵀᶜᴴ": {
      "matchMethod": 0,
      "words": []
    },
    "ᶠᵁᶜᴷ": {
      "matchMethod": 0,
      "words": []
    }
  }
}

**Comment by richardfrost** [comment]
Thank you for supplying your config, that helps a lot when troubleshooting.

The issue that you are running into is that the word list has reached its maximum allowed size for a chrome sync object. I  knew that someone would hit it eventually, and have been trying to think of the best way to work around it. 

So far my plans are to implement at least one of the following:

- Allow to switch to local-storage only: (Supports `5,242,880 Bytes`, or about 655 times more words than currently supported)
- Split words apart. This will require a slightly more complex storage scheme under the hood, but likely not too bad. (Supports max `102,400 Bytes`, or about 12 times more words than currently supported)
- optimize word objects. This would reduce readability in the configuration and underlying code, but would be much lighter on storage. something like: 
  - `{"word": "matchMethod: 0, "words": []}` -> `{"word": "m": 0, "w": []}`, which would remove 14 redundant characters for each word added. Likely at least doubles the words that can be stored.
  - potentially work a word optimizer that could find a more optimal matching method for repeated words. By specifying a root word like "house" and setting a matchmethod of Partial, you would only need one word entry to match "house" or "houses".

For now, there isn't really much that you can do on your end, aside from trying to optimize your wordlist (adjusting matchMethods of root words.). This will need to be fixed in an update of the extension. I will work on getting an update out ASAP, but I don't have an estimate yet.

**Comment by richardfrost** [comment]
Sorry it has taken so long, but I am almost done testing the fix for this. Would you be interested in taking a look at it as well?

**Comment by richardfrost** [comment]
@nunyabeeswax7 I'm getting really close to having this feature ready to ship. Are you interesting in testing the new build out?

**Comment by richardfrost** [comment]
Here are some notes/snippets:

```
var oldWords = {
  "words": {
    "couch": { "matchMethod": 1, "words": ["explative"] },
    "this": { "matchMethod": 1, "words": ["explative"] },
    "isatest": { "matchMethod": 1, "words": ["harlot", "tramp"] }
  }
};

chrome.storage.sync.set(oldWords);

chrome.storage.sync.remove('_words0');
chrome.storage.sync.remove('_words1');
chrome.storage.sync.remove('_words2');

chrome.storage.sync.get(null, function(result) { console.log(result); });
```

**Comment by richardfrost** [comment]
The latest release has been published for both Chrome and Firefox. Please let me know if you have any comments about the release, otherwise I'll close this in a few days.

**Comment by tonyram57** [comment]
It filters new added words but only if they are spelled exact.  If they are spelled even with a s at the end for example they are not filtered.

**Comment by tonyram57** [comment]
Update.
Works fine filtering new words now.

**Comment by richardfrost** [comment]
I'm glad its working for you now! If you are having trouble with words only matching when they match completely, it is probably because by default when a new word is added it gets set to an **Exact** match method. The matching method can be customized per-word or globally. If set to **Partial**, words that contain a filtered word will be censored.

Exact Match Example:
```
Word: dog
Original sentence:  To the doghouse!
Filtered sentence: to the doghouse!
```

Partial Match Example:
```
Word: dog
Original sentence:  To the doghouse!
Filtered sentence: to the ***house!
```

Since you have said its working again I'm going to close this issue, but feel free to comment if you have any more questions or concerns, or open a new issue. Thanks!
