### ISSUE TITLE
Not working on this page.

### ISSUE THREAD

**Issue by tonyram57** [richardfrost/AdvancedProfanityFilter#79]
https://www.microsoft.com/en-us/p/feedback-hub/9nblggh4r32n#ratings-reviews
If you start to read the reviews after about five or six pages of clicks someone posts "F'ing updates".  It is not working.  I even checked the code and the horrible F word is still in tack in the code.  The filter is not working for that page.

**Comment by tonyram57** [comment]
Also not working on the new reddit page.
https://www.reddit.com/r/apple/comments/8rls4r/i_started_building_an_apple_music_web_player_with/

**Comment by richardfrost** [comment]
I'm sorry it isn't working for you. Could you share your current config? You can export the config by opening the extensions Options page, then navigate to the "Config" tab and click the export button. Then just simply copy and paste your configuration and add it as a comment here.

I added the word `Windows` to my filter to test the first link you shared and it seems to work on all the comment pages that I sampled.

On the second link you shared I also am seeing words being filtered.

If there is a problem with the config that can cause issues like this, so that's probably a good starting point. Thanks for your interest, I hope we can get this solved for you!

**Comment by tonyram57** [comment]
[pf.txt](https://github.com/richardfrost/AdvancedProfanityFilter/files/2153327/pf.txt)
Here is the export.  I will also reset the filter.

**Comment by richardfrost** [comment]
Thanks! With your config I am having success on the reddit page that you linked. Did you have a chance to try resetting to default settings?

I clicked through a bunch of those reviews for that first link, but I'm still not seeing the comment you were referencing. If you are still seeing it maybe you could send me a screenshot?

**Comment by tonyram57** [comment]
Reddit is more important.  As for the MS review I reported it so it must be gone as I can't find it either.  Anyway I hope for an update soon.

**Comment by richardfrost** [comment]
So is it still not working for you? Like I mentioned above, it is working for me on that reddit link you gave me.

**Comment by tonyram57** [comment]
Nope not working on the new Reddit but if I choose the old Reddit page it still works.
Also so you know I am running version 1.0.1.1.

**Comment by richardfrost** [comment]
Are you using Chrome, or Firefox?

**Comment by tonyram57** [comment]
Firefox but it does not work in Chrome either.  It is not filtering the s-word.  I dare not read anymore to see if it filters any more profanities.

**Comment by richardfrost** [comment]
Alright, I think I have identified the issue with the new Reddit design. I have a beta build that I'd like to have you test.

For Chrome, you'll need to [become a beta tester](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Beta-Testing).

For Firefox, unfortunately they removed their beta/testing system, so it's a little more involved. You'll have to [load a temporary Add-on](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox), which I have attached as a zip file.

Note: This also includes several other fixes that I'm beta testing. Other changes to watch for:
- Preserve case when using Substitutions
- Run at `document_start`, which should make the filter run sooner (typically you shouldn't even see unfiltered words on page load anymore)
- The new Reddit fix

Thanks for your feedback and help working through this issue!

**Comment by tonyram57** [comment]
Reddit works with the new beta extension.  It blocked 15 profanities which before the latest stable version only blocked 5 profanities.  Just hope it goes final soon.

**Comment by richardfrost** [comment]
The reason that it triples is in regards to how reddit is storing the text
now. They store 3 different copies of each comment, mostly with different
formatting. I looked at maybe targeting just one, but unfortunately it's
ultimately up to reddit to choose which one to present to the user, so I
figured for now I will just leave it as is,so all 3 formats are covered.
I'm glad to hear it's working! I am waiting for feedback from a couple more
people, but hope to get it released tomorrow. Let me know if you notice
anything else. Also, did you try Firefox, or Chrome?

**Comment by tonyram57** [comment]
Reddit is annoying it so vulgar I need a working profanity filter to even view but it is a necessary evil when I need solutions to certain problem but them always changing it so they make it hard to get it work.

**Comment by tonyram57** [comment]
Works in both browsers but I primary use Firefox as Chrome has blurry font rendering.

**Comment by richardfrost** [comment]
Alright - I have released the new version to both Chrome and Firefox, and it looks like it is working for me. Let me know how it goes for you!

**Comment by richardfrost** [comment]
Awesome! I'm going to go ahead and close this then. I am glad, because Reddit is definitely the most vulgar site I visit. Feel free to re-open this or create a new issue in the future if you need to. Thanks again for reporting this and helping me test the solution!
