### ISSUE TITLE
Retain capitalization

### ISSUE THREAD

**Issue by RebelKeithy** [richardfrost/AdvancedProfanityFilter#82]
A feature I would like to see is the ability to retain the capitalization of the word being substituted. This would make the substitutions harder to notice especially when someone is using all caps. 

There are three possibilities when replacing a word:
- The original word is all uppercase. The substituted word is all uppercase.
- The original word starts with a uppercase. The substituted word starts with a uppercase.
- The original word is all lowercase. The substituted word is all lowercase.

**Comment by RebelKeithy** [comment]
Wow, I just realized you have a pull request with this feature.

**Comment by richardfrost** [comment]
I do! But thanks for the suggestion! I hope to finish testing on it in the next day or two and will release an update. Thanks again for the input, and I'm glad I think my PR should address your criteria, so hopefully I got it right!

**Comment by richardfrost** [comment]
I just released a new version of the extension that includes this option (enabled by default). Let me know if it gives you any trouble, or if you have any other feedback!
