### ISSUE TITLE
Massive slowdown on pages with many profanities with Firefox & Chrome

### ISSUE THREAD

**Issue by tonyram57** [richardfrost/AdvancedProfanityFilter#93]
Yes the filter is blocking them but in Firefox if I go lets say to this page
https://productforums.google.com/forum/#!msg/youtube/32tHQqeTsIk/9Z1kEk6JFeUJ
as Google Product Forums have many profanities Firefox and Chrome slows down and when I scroll there is much lag.

Now there is no way I will turn off the filter on a vile form like the Google Product Forum.

**Comment by tonyram57** [comment]
Okay it is only web pages that keep scrolling on forever.  I hate those infinitive scrolling pages and I noticed it even with websites that don't have any profanities.

As for my config file here but it is just the stock script.  Nothing much different except I unchecked the box that says preserve the first letter ex:dog d** ***.
[filter.txt](https://github.com/richardfrost/AdvancedProfanityFilter/files/2320185/filter.txt)

**Comment by richardfrost** [comment]
I'll go ahead and leave this open for a bit longer then. If you can find a repeatable way to make it happen let me know. I tried it on a few of my computers and didn't ever see the kind of slowdown you are describing, so its hard to do more digging on my end.

Also, I just put out an update that, so let me know if you notice any change in the issue, or if you have any general feedback.

**Comment by tonyram57** [comment]
I did not notice a slow down either maybe an unrelated browser update fixed it or something.  Anyway I will update any site if I get a slowdown.  Thanks.

**Comment by richardfrost** [comment]
Thanks for responding! I will go ahead and close this for now then, but feel free to re-open it or create a new issue if the problem comes up again.
